name: OrbitalApp
options:
  bundleIdPrefix: io.orbitalsolver
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"

targets:
  OrbitalApp:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - README.md
          - "*.xcodeproj"
    settings:
      base:
        INFOPLIST_GENERATION_MODE: GeneratedFile
        PRODUCT_BUNDLE_IDENTIFIER: io.orbitalsolver.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_CFBundleDisplayName: "Orbital"
