"""
Auto-generated Manim scene (v3) with full visual support.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *
import json, os, math

# ── colours ──────────────────────────────────────────────────────
ORBITAL_VIOLET  = "#8B5CF6"
ORBITAL_CYAN    = "#22D3EE"
NEON_GREEN      = "#39FF14"
BOX_BORDER      = "#8B5CF6"
BOX_FILL        = "#1a1130"
LABEL_COLOR     = "#22D3EE"
CUT_LEFT        = "#4F46E5"
CUT_RIGHT       = "#F97316"
CUT_POINT       = "#FACC15"
SEQ_HIGHLIGHT   = "#F43F5E"
TABLE_HEADER    = "#8B5CF6"
TABLE_CELL      = "#1E1B4B"
GRAPH_BLUE      = "#3B82F6"
GRAPH_ORANGE    = "#F97316"
GRAPH_PINK      = "#EC4899"
GEOM_TEAL       = "#14B8A6"
SURFACE_LOW     = "#4F46E5"
SURFACE_HIGH    = "#F97316"

# ── layout constants ─────────────────────────────────────────────
MAX_BUILD_LINES  = 5
TOP_Y            = 3.0
LINE_SPACING     = 0.85
EXTRA_HOLD       = 0.8
ANIMATION_RATIO  = 0.35
WATERMARK_TEXT    = "ORBITAL"


# ═══════════════════════════════════════════════════════════════════
#  DIAGRAM BUILDERS (v2 — unchanged)
# ═══════════════════════════════════════════════════════════════════

def _build_number_line_cut(cfg: dict) -> VGroup:
    x_range   = cfg.get("x_range", [-4, 4, 1])
    cut_at    = cfg.get("cut_at", 0)
    left_lbl  = cfg.get("left_label", "A")
    right_lbl = cfg.get("right_label", "B")
    cut_lbl   = cfg.get("cut_label", "")
    show_pt   = cfg.get("show_point", True)

    nl = NumberLine(x_range=x_range, length=10, include_numbers=True,
                    include_tip=True, font_size=24, color=WHITE)
    group = VGroup(nl)

    left_start = nl.n2p(x_range[0])[0]
    cut_x      = nl.n2p(cut_at)[0]
    right_end  = nl.n2p(x_range[1])[0]
    line_y     = nl.get_center()[1]
    region_h = 0.5

    if cut_x - left_start > 0.1:
        left_rect = Rectangle(width=cut_x - left_start, height=region_h,
                              fill_color=CUT_LEFT, fill_opacity=0.35, stroke_width=0)
        left_rect.move_to([(left_start + cut_x) / 2, line_y, 0])
        group.add(left_rect)
        ll = MathTex(left_lbl, color=CUT_LEFT, font_size=36)
        ll.next_to(left_rect, UP, buff=0.3)
        group.add(ll)

    if right_end - cut_x > 0.1:
        right_rect = Rectangle(width=right_end - cut_x, height=region_h,
                               fill_color=CUT_RIGHT, fill_opacity=0.35, stroke_width=0)
        right_rect.move_to([(cut_x + right_end) / 2, line_y, 0])
        group.add(right_rect)
        rl = MathTex(right_lbl, color=CUT_RIGHT, font_size=36)
        rl.next_to(right_rect, UP, buff=0.3)
        group.add(rl)

    if show_pt:
        dot = Dot(nl.n2p(cut_at), color=CUT_POINT, radius=0.1)
        group.add(dot)
    if cut_lbl:
        cl = MathTex(cut_lbl, color=CUT_POINT, font_size=36)
        cl.next_to(nl.n2p(cut_at), DOWN, buff=0.35)
        group.add(cl)

    dash = DashedLine(start=nl.n2p(cut_at) + UP * 0.8, end=nl.n2p(cut_at) + DOWN * 0.2,
                      color=CUT_POINT, stroke_width=2)
    group.add(dash)
    group.scale(0.75)
    return group


def _build_set_containment(cfg: dict) -> VGroup:
    sets = cfg.get("sets", [
        {"label": "A", "radius": 1.5, "position": [-0.5, 0], "color": "#4F46E5"},
        {"label": "B", "radius": 1.5, "position": [0.5, 0], "color": "#F97316"},
    ])
    group = VGroup()
    for s in sets:
        circ = Circle(radius=s.get("radius", 1.5), color=s.get("color", WHITE),
                      fill_opacity=0.15, stroke_width=2)
        pos = s.get("position", [0, 0])
        circ.move_to([pos[0], pos[1], 0])
        lbl = MathTex(s.get("label", ""), color=s.get("color", WHITE), font_size=36)
        lbl.move_to(circ.get_center() + UP * (s.get("radius", 1.5) + 0.3))
        group.add(circ, lbl)
    group.scale(0.8)
    return group


def _build_sequence_list(cfg: dict) -> VGroup:
    items     = cfg.get("items", ["r_1", "r_2", "r_3", "\\dots"])
    highlight = cfg.get("highlight", [])
    label     = cfg.get("label", "")
    parts = []
    for i, item in enumerate(items):
        color = SEQ_HIGHLIGHT if i in highlight else WHITE
        m = MathTex(item, color=color, font_size=40)
        parts.append(m)
        if i < len(items) - 1:
            comma = MathTex(",", color=GREY, font_size=40)
            parts.append(comma)
    row = VGroup(*parts).arrange(RIGHT, buff=0.2)
    group = VGroup(row)
    if label:
        lbl = Tex(label, color=LABEL_COLOR, font_size=32)
        lbl.next_to(row, UP, buff=0.4)
        group.add(lbl)
    group.scale(0.85)
    return group


def _build_table(cfg: dict) -> VGroup:
    headers = cfg.get("headers", [])
    rows    = cfg.get("rows", [])
    hl      = cfg.get("highlight_cells", [])
    all_rows = []
    if headers:
        all_rows.append(headers)
    all_rows.extend(rows)

    group = VGroup()
    cell_w = 1.4
    cell_h = 0.6
    for r, row in enumerate(all_rows):
        for c, cell in enumerate(row):
            m = MathTex(cell, font_size=30)
            if r == 0 and headers:
                m.set_color(LABEL_COLOR)
            for hr, hc in hl:
                adj_r = hr + (1 if headers else 0)
                if r == adj_r and c == hc:
                    m.set_color(SEQ_HIGHLIGHT)
            x = (c - len(row) / 2 + 0.5) * cell_w
            y = -r * cell_h
            m.move_to([x, y, 0])
            bg = Rectangle(width=cell_w - 0.05, height=cell_h - 0.05,
                           fill_color=TABLE_HEADER if (r == 0 and headers) else TABLE_CELL,
                           fill_opacity=0.4, stroke_color=GREY_D, stroke_width=1)
            bg.move_to(m.get_center())
            group.add(bg, m)
    group.scale(0.8)
    return group


DIAGRAM_BUILDERS = {
    "number_line_cut": _build_number_line_cut,
    "set_containment": _build_set_containment,
    "sequence_list":   _build_sequence_list,
    "table":           _build_table,
}


# ═══════════════════════════════════════════════════════════════════
#  GRAPH BUILDERS (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_graph(cfg: dict) -> VGroup:
    """
    Function graphing with axes.
    cfg keys:
        kind: "function_plot" | "tangent_line" | "area_under"
        x_range: [min, max, step]
        y_range: [min, max, step]
        functions: [{expr, color, label, dashed}]
        points: [{x, y, label, color}]
        shaded_area: {func_index, x_range, color, opacity}
        show_grid: bool
        axis_labels: [x_label, y_label]
    """
    kind       = cfg.get("kind", "function_plot")
    x_range    = cfg.get("x_range", [-5, 5, 1])
    y_range    = cfg.get("y_range", [-5, 5, 1])
    functions  = cfg.get("functions", [])
    points     = cfg.get("points", [])
    shaded     = cfg.get("shaded_area", None)
    show_grid  = cfg.get("show_grid", False)
    axis_labels = cfg.get("axis_labels", ["x", "y"])

    if show_grid:
        plane = NumberPlane(
            x_range=x_range, y_range=y_range,
            x_length=8, y_length=5,
            background_line_style={"stroke_color": GREY_D, "stroke_opacity": 0.4},
        )
        axes = plane
    else:
        axes = Axes(
            x_range=x_range, y_range=y_range,
            x_length=8, y_length=5,
            axis_config={"color": WHITE, "include_numbers": True, "font_size": 20},
        )

    group = VGroup(axes)

    # Axis labels
    if axis_labels:
        x_lbl = axes.get_x_axis_label(axis_labels[0], direction=RIGHT)
        y_lbl = axes.get_y_axis_label(axis_labels[1], direction=UP)
        group.add(x_lbl, y_lbl)

    # Plot functions
    # NOTE: expr strings are eval'd here. Input is controlled by our pipeline,
    # but this should be sandboxed if we ever accept user-provided expressions.
    default_colors = [ORBITAL_VIOLET, ORBITAL_CYAN, GRAPH_ORANGE, GRAPH_PINK, NEON_GREEN]
    plotted_funcs = []
    for i, fn in enumerate(functions):
        expr_str = fn.get("expr", "lambda x: x")
        color    = fn.get("color", default_colors[i % len(default_colors)])
        label    = fn.get("label", "")
        dashed   = fn.get("dashed", False)
        fn_obj   = eval(expr_str)  # Security: controlled input only

        if dashed:
            graph = DashedVMobject(axes.plot(fn_obj, color=color), num_dashes=40)
        else:
            graph = axes.plot(fn_obj, color=color)
        plotted_funcs.append((graph, fn_obj))
        group.add(graph)

        if label:
            lbl = MathTex(label, color=color, font_size=28)
            lbl.next_to(graph, UR, buff=0.15)
            group.add(lbl)

    # Shaded area under curve
    if shaded and plotted_funcs:
        fi = shaded.get("func_index", 0)
        sr = shaded.get("x_range", [x_range[0], x_range[1]])
        sc = shaded.get("color", NEON_GREEN)
        so = shaded.get("opacity", 0.3)
        if fi < len(plotted_funcs):
            fn_obj = plotted_funcs[fi][1]
            area = axes.get_area(
                axes.plot(fn_obj, color=sc),
                x_range=sr, color=sc, opacity=so,
            )
            group.add(area)

    # Points / dots
    for pt in points:
        px, py = pt.get("x", 0), pt.get("y", 0)
        pc = pt.get("color", CUT_POINT)
        pl = pt.get("label", "")
        dot = Dot(axes.c2p(px, py), color=pc, radius=0.08)
        group.add(dot)
        if pl:
            plbl = MathTex(pl, color=pc, font_size=24)
            plbl.next_to(dot, UR, buff=0.12)
            group.add(plbl)

    group.scale(0.75)
    return group


# ═══════════════════════════════════════════════════════════════════
#  TRANSFORM BUILDER (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_transform_data(cfg: dict) -> dict:
    """
    Returns a dict with 'from_mob', 'to_mob', 'intermediates' for the scene
    to animate. We return data rather than a single VGroup because transforms
    need to be animated sequentially in construct().
    """
    return cfg  # Handled specially in the scene — see _animate_transform


# ═══════════════════════════════════════════════════════════════════
#  GEOMETRIC BUILDERS (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_geometric(cfg: dict) -> VGroup:
    """
    Geometric constructions.
    cfg keys:
        shapes: [{type, ...params}]
          - polygon: vertices, color, label, fill_opacity
          - circle: center, radius, color, fill_opacity
          - line: start, end, color, dashed
          - angle: vertex, ray1, ray2, label, radius, color
        labels: [{text, position, color}]
    """
    shapes = cfg.get("shapes", [])
    labels = cfg.get("labels", [])
    group = VGroup()

    for s in shapes:
        stype = s.get("type", "line")

        if stype == "polygon":
            verts = s.get("vertices", [[0,0], [2,0], [1,1.7]])
            color = s.get("color", ORBITAL_VIOLET)
            fill_op = s.get("fill_opacity", 0.15)
            poly = Polygon(*[np.array([v[0], v[1], 0]) for v in verts],
                           color=color, fill_opacity=fill_op, stroke_width=2)
            group.add(poly)
            lbl = s.get("label", "")
            if lbl:
                # Label each vertex
                for i, char in enumerate(lbl):
                    if i < len(verts):
                        v = verts[i]
                        # Push label away from centroid
                        cx = sum(vv[0] for vv in verts) / len(verts)
                        cy = sum(vv[1] for vv in verts) / len(verts)
                        dx = v[0] - cx
                        dy = v[1] - cy
                        norm = max((dx**2 + dy**2)**0.5, 0.01)
                        t = MathTex(char, color=color, font_size=28)
                        t.move_to([v[0] + dx/norm*0.4, v[1] + dy/norm*0.4, 0])
                        group.add(t)

        elif stype == "circle":
            cx, cy = s.get("center", [0, 0])
            r = s.get("radius", 1.5)
            color = s.get("color", ORBITAL_CYAN)
            fill_op = s.get("fill_opacity", 0.1)
            circ = Circle(radius=r, color=color, fill_opacity=fill_op, stroke_width=2)
            circ.move_to([cx, cy, 0])
            group.add(circ)

        elif stype == "line":
            st = s.get("start", [-3, 0])
            en = s.get("end", [3, 0])
            color = s.get("color", WHITE)
            dashed = s.get("dashed", False)
            if dashed:
                ln = DashedLine([st[0], st[1], 0], [en[0], en[1], 0],
                                color=color, stroke_width=2)
            else:
                ln = Line([st[0], st[1], 0], [en[0], en[1], 0],
                          color=color, stroke_width=2)
            group.add(ln)

        elif stype == "angle":
            vertex = s.get("vertex", [0, 0])
            ray1   = s.get("ray1", [2, 0])
            ray2   = s.get("ray2", [1, 1.7])
            label  = s.get("label", "")
            radius = s.get("radius", 0.6)
            color  = s.get("color", GEOM_TEAL)

            v = np.array([vertex[0], vertex[1], 0])
            r1 = np.array([ray1[0], ray1[1], 0])
            r2 = np.array([ray2[0], ray2[1], 0])

            l1 = Line(v, r1, color=WHITE, stroke_width=2)
            l2 = Line(v, r2, color=WHITE, stroke_width=2)
            group.add(l1, l2)

            angle = Angle(l1, l2, radius=radius, color=color)
            group.add(angle)

            if label:
                mid_angle = (angle.get_start() + angle.get_end()) / 2
                direction = mid_angle - v
                norm = max(np.linalg.norm(direction), 0.01)
                lbl = MathTex(label, color=color, font_size=28)
                lbl.move_to(v + direction / norm * (radius + 0.35))
                group.add(lbl)

    # Extra labels
    for lb in labels:
        txt = lb.get("text", "")
        pos = lb.get("position", [0, 0])
        col = lb.get("color", WHITE)
        t = MathTex(txt, color=col, font_size=28)
        t.move_to([pos[0], pos[1], 0])
        group.add(t)

    group.scale(0.85)
    return group


# ═══════════════════════════════════════════════════════════════════
#  3D BUILDERS (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_threed_data(cfg: dict) -> dict:
    """
    Returns config for 3D scene rendering. Handled in construct() because
    ThreeDScene needs camera manipulation.
    """
    return cfg  # Handled in scene construct()


# ═══════════════════════════════════════════════════════════════════
#  MOBJECT FACTORY
# ═══════════════════════════════════════════════════════════════════

def _make_mobject(step: dict):
    """Create the correct Manim object for a step type."""
    stype   = step.get("type", "math")
    content = step.get("content") or step.get("latex", "")
    label   = step.get("label", "")

    if stype == "math":
        mob = MathTex(content, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "text":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "mixed":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "box":
        inner = Tex(content, color=WHITE)
        inner.scale(0.85)
        lbl = Tex(r"\textbf{" + label + "}", color=LABEL_COLOR)
        lbl.scale(0.7)
        box_rect = SurroundingRectangle(
            inner, color=BOX_BORDER, fill_color=BOX_FILL,
            fill_opacity=0.6, buff=0.35, corner_radius=0.12, stroke_width=2,
        )
        lbl.next_to(box_rect, UP, buff=0.15).align_to(box_rect, LEFT).shift(RIGHT * 0.2)
        return VGroup(box_rect, lbl, inner)

    if stype == "diagram":
        diagram_cfg = step.get("diagram", {})
        kind = diagram_cfg.get("kind", "number_line_cut")
        builder = DIAGRAM_BUILDERS.get(kind)
        if builder:
            return builder(diagram_cfg)
        return Text(f"[diagram: {kind}]", color=GREY, font_size=28)

    if stype == "graph":
        graph_cfg = step.get("graph", {})
        return _build_graph(graph_cfg)

    if stype == "geometric":
        geom_cfg = step.get("geometric", {})
        return _build_geometric(geom_cfg)

    # "transform" and "threed" are handled specially in construct()
    # but we provide a fallback static mob for safety
    if stype == "transform":
        from_latex = step.get("transform", {}).get("from_latex", content)
        mob = MathTex(from_latex, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "threed":
        mob = Text("[3D scene]", color=GREY, font_size=28)
        return mob

    # fallback
    mob = MathTex(content, color=WHITE)
    mob.scale(1.4)
    return mob


# ═══════════════════════════════════════════════════════════════════
#  SCENE
# ═══════════════════════════════════════════════════════════════════

class SyncedProofScene(Scene):
    def construct(self):
        self.camera.background_color = "#000000"

        wm = Text(WATERMARK_TEXT, font_size=14, color=WHITE).set_opacity(0.35)
        wm.to_corner(DR, buff=0.3)
        self.add(wm)

        steps = [
        {
                "step": 0,
                "narration": "Our goal is to show that the real numbers, constructed via Dedekind cuts, are uncountable.",
                "latex": "",
                "content": "Using Dedekind cuts, show that $\\mathbb{R}$ is uncountable.",
                "type": "box",
                "mode": "replace",
                "label": "Goal",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_00.mp3",
                "duration": 5.9
        },
        {
                "step": 1,
                "narration": "First, let's recall what a Dedekind cut is. A Dedekind cut is a partition of the rationals into two nonempty sets A and B,",
                "latex": "",
                "content": "A Dedekind cut is a pair $(A, B)$ where $A \\cup B = \\mathbb{Q}$, $A \\neq \\emptyset$, $B \\neq \\emptyset$,",
                "type": "box",
                "mode": "replace",
                "label": "Definition",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_01.mp3",
                "duration": 9.1
        },
        {
                "step": 2,
                "narration": "where every element of A is less than every element of B,",
                "latex": "",
                "content": "every element of $A$ is less than every element of $B$,",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_02.mp3",
                "duration": 4.04
        },
        {
                "step": 3,
                "narration": "and A has no greatest element.",
                "latex": "",
                "content": "and $A$ has no greatest element.",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_03.mp3",
                "duration": 2.0
        },
        {
                "step": 4,
                "narration": "Here's a picture. The number line is split into two regions. Everything to the left is A, everything to the right is B. The cut itself represents the square root of two. There's no gap here \u2014 the partition of the rationals IS the real number.",
                "latex": "",
                "content": "",
                "type": "diagram",
                "mode": "replace",
                "label": "",
                "diagram": {
                        "kind": "number_line_cut",
                        "x_range": [
                                -4,
                                4,
                                1
                        ],
                        "cut_at": 1.414,
                        "left_label": "A",
                        "right_label": "B",
                        "cut_label": "\\sqrt{2}",
                        "show_point": False
                },
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_04.mp3",
                "duration": 16.49
        },
        {
                "step": 5,
                "narration": "Each such cut defines a real number alpha. This is how we construct the reals from the rationals.",
                "latex": "",
                "content": "Each cut $(A, B)$ defines a real number $\\alpha$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_05.mp3",
                "duration": 6.36
        },
        {
                "step": 6,
                "narration": "The set of all Dedekind cuts is the real numbers.",
                "latex": "",
                "content": "The set of all Dedekind cuts $\\textit{is}$ $\\mathbb{R}$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_06.mp3",
                "duration": 3.2
        },
        {
                "step": 7,
                "narration": "Now we prove our theorem: the reals are uncountable.",
                "latex": "",
                "content": "$\\mathbb{R}$ is uncountable.",
                "type": "box",
                "mode": "replace",
                "label": "Theorem",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_07.mp3",
                "duration": 3.58
        },
        {
                "step": 8,
                "narration": "Assume, for the sake of contradiction, that the reals are countable.",
                "latex": "",
                "content": "Assume for contradiction that $\\mathbb{R}$ is countable.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_08.mp3",
                "duration": 4.09
        },
        {
                "step": 9,
                "narration": "Then we could list every real number as alpha one, alpha two, alpha three, and so on.",
                "latex": "",
                "content": "Then we can list all real numbers as $\\alpha_1, \\alpha_2, \\alpha_3, \\dots$",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_09.mp3",
                "duration": 6.13
        },
        {
                "step": 10,
                "narration": "Here is our supposed complete listing of all real numbers.",
                "latex": "",
                "content": "",
                "type": "diagram",
                "mode": "replace",
                "label": "",
                "diagram": {
                        "kind": "sequence_list",
                        "items": [
                                "\\alpha_1",
                                "\\alpha_2",
                                "\\alpha_3",
                                "\\alpha_4",
                                "\\dots"
                        ],
                        "highlight": [],
                        "label": "Supposed enumeration of $\\mathbb{R}$"
                },
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_10.mp3",
                "duration": 3.67
        },
        {
                "step": 11,
                "narration": "Remember, each alpha n is a Dedekind cut \u2014 a pair A n, B n partitioning the rationals.",
                "latex": "",
                "content": "Each $\\alpha_n$ is a Dedekind cut $(A_n, B_n)$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_11.mp3",
                "duration": 6.69
        },
        {
                "step": 12,
                "narration": "We will now construct a new Dedekind cut, A star and B star, that cannot appear anywhere in the list.",
                "latex": "",
                "content": "We will build a new cut $(A^*, B^*)$ not in the list.",
                "type": "box",
                "mode": "replace",
                "label": "Construction",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_12.mp3",
                "duration": 7.11
        },
        {
                "step": 13,
                "narration": "Our strategy: we'll construct a shrinking sequence of intervals, each one carefully chosen to dodge the next real number on the list. We're not invoking any completeness theorem here \u2014 we'll build the cut directly.",
                "latex": "",
                "content": "We construct a shrinking sequence of intervals, each one dodging the next real on the list.",
                "type": "text",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_13.mp3",
                "duration": 12.59
        },
        {
                "step": 14,
                "narration": "Start by picking a closed interval a one, b one with rational endpoints, chosen so that alpha one does not lie in this interval. For instance, if alpha one happens to be 2.7, we might pick the interval from 3 to 4. We can always find such an interval \u2014 divide any starting interval into thirds and pick a third that avoids alpha one.",
                "latex": "",
                "content": "Pick a closed interval $[a_1, b_1]$ with $a_1, b_1 \\in \\mathbb{Q}$ such that $\\alpha_1 \\notin [a_1, b_1]$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_14.mp3",
                "duration": 21.45
        },
        {
                "step": 15,
                "narration": "Next, pick a smaller interval a two, b two inside the first one, avoiding alpha two. Again, divide into thirds and dodge.",
                "latex": "",
                "content": "Pick $[a_2, b_2] \\subset [a_1, b_1]$ with $\\alpha_2 \\notin [a_2, b_2]$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_15.mp3",
                "duration": 8.68
        },
        {
                "step": 16,
                "narration": "Continue this process. We get a nested sequence of closed intervals, each one inside the last, each one avoiding the next alpha on our list.",
                "latex": "",
                "content": "Continue: $[a_1, b_1] \\supset [a_2, b_2] \\supset [a_3, b_3] \\supset \\cdots$",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_16.mp3",
                "duration": 9.52
        },
        {
                "step": 17,
                "narration": "Notice that the left endpoints form a non-decreasing sequence \u2014 a one is at most a two, which is at most a three, and so on. They march steadily to the right.",
                "latex": "",
                "content": "$a_1 \\leq a_2 \\leq a_3 \\leq \\cdots$ \u2014 the left endpoints march rightward.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_17.mp3",
                "duration": 10.87
        },
        {
                "step": 18,
                "narration": "At step n, the interval a n, b n is chosen to exclude alpha n.",
                "latex": "",
                "content": "At step $n$: $\\alpha_n \\notin [a_n, b_n]$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_18.mp3",
                "duration": 5.39
        },
        {
                "step": 19,
                "narration": "Now define A star as the set of all rationals q that are less than some left endpoint a n. Think of it this way: as we drill deeper with each interval, the left endpoints creep rightward. A star collects everything to the left of where they're heading.",
                "latex": "",
                "content": "Define $A^* = \\{ q \\in \\mathbb{Q} : q < a_n \\text{ for some } n \\}$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_19.mp3",
                "duration": 16.95
        },
        {
                "step": 20,
                "narration": "Equivalently, A star is the union of all the sets of rationals less than a n.",
                "latex": "",
                "content": "Equivalently, $A^* = \\bigcup_{n=1}^{\\infty} \\{ q \\in \\mathbb{Q} : q < a_n \\}$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_20.mp3",
                "duration": 6.08
        },
        {
                "step": 21,
                "narration": "And B star is everything in the rationals not in A star.",
                "latex": "",
                "content": "Let $B^* = \\mathbb{Q} \\setminus A^*$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_21.mp3",
                "duration": 3.48
        },
        {
                "step": 22,
                "narration": "We claim that A star, B star is a valid Dedekind cut \u2014 that is, a real number.",
                "latex": "",
                "content": "$(A^*, B^*)$ is a valid Dedekind cut.",
                "type": "box",
                "mode": "replace",
                "label": "Claim",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_22.mp3",
                "duration": 6.04
        },
        {
                "step": 23,
                "narration": "A star is nonempty because it contains a one minus one. B star is nonempty because it contains b one \u2014 since b one is at least as big as every a n, it's never less than any a n.",
                "latex": "",
                "content": "$A^*$ is nonempty (contains $a_1 - 1$) and $B^*$ is nonempty (contains $b_1$).",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_23.mp3",
                "duration": 12.35
        },
        {
                "step": 24,
                "narration": "Every element of A star is less than every element of B star, by construction \u2014 A star is a downward-closed set.",
                "latex": "",
                "content": "Every element of $A^*$ is less than every element of $B^*$.",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_24.mp3",
                "duration": 8.03
        },
        {
                "step": 25,
                "narration": "And A star has no greatest element \u2014 if q is less than a n, we can always find a rational q prime between q and a n, by density of the rationals.",
                "latex": "",
                "content": "$A^*$ has no greatest element (if $q < a_n$, then $q < q' < a_n$ for some $q'$).",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_25.mp3",
                "duration": 10.4
        },
        {
                "step": 26,
                "narration": "So we've built a completely legitimate real number \u2014 alpha star \u2014 directly from the nested intervals. No completeness theorem invoked, no magic. Just a union of rational sets that satisfies the three conditions of a Dedekind cut.",
                "latex": "",
                "content": "So $(A^*, B^*)$ defines a real number $\\alpha^*$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_26.mp3",
                "duration": 15.74
        },
        {
                "step": 27,
                "narration": "And HERE is the punchline. Alpha star is different from every single alpha n on our list.",
                "latex": "",
                "content": "$\\alpha^* \\neq \\alpha_n$ for any $n$.",
                "type": "box",
                "mode": "replace",
                "label": "Key Step",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_27.mp3",
                "duration": 5.85
        },
        {
                "step": 28,
                "narration": "Why? Because alpha n was excluded from the interval a n, b n by construction. But alpha star lies inside every interval a n, b n \u2014 it's the real number defined by the left endpoints of all these intervals.",
                "latex": "",
                "content": "Since $\\alpha_n \\notin [a_n, b_n]$ but $\\alpha^* \\in [a_n, b_n]$ for all $n$:",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_28.mp3",
                "duration": 16.35
        },
        {
                "step": 29,
                "narration": "Therefore alpha star is not equal to alpha n, for any natural number n.",
                "latex": "",
                "content": "\\alpha^* \\neq \\alpha_n \\quad \\text{for all } n \\in \\mathbb{N}",
                "type": "math",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_29.mp3",
                "duration": 5.11
        },
        {
                "step": 30,
                "narration": "But alpha star is a real number, and it's not anywhere in our list.",
                "latex": "",
                "content": "But $\\alpha^* \\in \\mathbb{R}$ and $\\alpha^*$ is not in the list.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_30.mp3",
                "duration": 4.32
        },
        {
                "step": 31,
                "narration": "This contradicts our assumption that the list contained every real number.",
                "latex": "",
                "content": "This contradicts the assumption that the list contains all of $\\mathbb{R}$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_31.mp3",
                "duration": 4.13
        },
        {
                "step": 32,
                "narration": "Therefore, the reals are uncountable.",
                "latex": "",
                "content": "Therefore $\\mathbb{R}$ is uncountable. $\\blacksquare$",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_32.mp3",
                "duration": 2.28
        },
        {
                "step": 33,
                "narration": "Let's recap. We assumed the reals were countable and listed them all. Then we constructed a Dedekind cut using nested intervals \u2014 each interval dodging the next real on the list. The resulting cut is a real number not on the list. Contradiction. The reals are uncountable.",
                "latex": "",
                "content": "Assumed $\\mathbb{R}$ countable $\\to$ listed all reals $\\to$ built a Dedekind cut dodging every entry $\\to$ contradiction.",
                "type": "box",
                "mode": "replace",
                "label": "Recap",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/dedekind_uncountable_v2/audio/step_33.mp3",
                "duration": 18.9
        }
]

        build_lines = []
        previous_replace = None
        total = len(steps)

        for idx, step in enumerate(steps):
            duration   = step.get("duration", 2.0)
            audio_path = step.get("audio_path", "")
            mode       = step.get("mode", "replace")
            stype      = step.get("type", "math")

            if audio_path and os.path.exists(audio_path):
                self.add_sound(audio_path)

            anim_time = max(0.8, duration * ANIMATION_RATIO)

            # ── TRANSFORM (special animation) ────────────────────
            if stype == "transform":
                tcfg = step.get("transform", {})
                from_latex = tcfg.get("from_latex", "")
                to_latex   = tcfg.get("to_latex", "")
                intermediates = tcfg.get("intermediate_steps", [])
                highlights = tcfg.get("highlight_parts", [])

                # Clear previous
                if build_lines:
                    self.play(*[FadeOut(ln, shift=UP*0.3) for ln in build_lines], run_time=0.3)
                    build_lines.clear()
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP*0.3), run_time=0.35)

                # Show FROM expression
                from_mob = MathTex(from_latex, color=WHITE).scale(1.4)
                self.play(Write(from_mob), run_time=anim_time * 0.5)

                # Apply highlights
                for hl in highlights:
                    tex = hl.get("tex", "")
                    hcolor = hl.get("color", ORBITAL_VIOLET)
                    for part in from_mob:
                        for sub in part:
                            if hasattr(sub, 'get_tex_string') and tex in sub.get_tex_string():
                                sub.set_color(hcolor)

                # Build chain: from → intermediates → to
                chain = intermediates + [to_latex] if to_latex else intermediates
                current_mob = from_mob
                time_per_step = max(0.6, (duration - anim_time * 0.5) / max(len(chain), 1))

                for expr in chain:
                    next_mob = MathTex(expr, color=WHITE).scale(1.4)
                    self.play(TransformMatchingTex(current_mob, next_mob), run_time=time_per_step)
                    self.wait(0.3)
                    current_mob = next_mob

                previous_replace = current_mob
                remaining = max(0.1, duration - anim_time)
                self.wait(remaining * 0.3)
                if idx < total - 1:
                    self.wait(EXTRA_HOLD)
                continue

            # ── THREED (special scene handling) ──────────────────
            if stype == "threed":
                tcfg = step.get("threed", {})
                kind = tcfg.get("kind", "surface")

                # Clear previous
                if build_lines:
                    self.play(*[FadeOut(ln, shift=UP*0.3) for ln in build_lines], run_time=0.3)
                    build_lines.clear()
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP*0.3), run_time=0.35)

                # Camera angle
                cam = tcfg.get("camera_angle", {"phi": 60, "theta": -45})
                phi = cam.get("phi", 60) * DEGREES
                theta = cam.get("theta", -45) * DEGREES
                self.set_camera_orientation(phi=phi, theta=theta)

                # 3D Axes
                if tcfg.get("axes", True):
                    axes_3d = ThreeDAxes(
                        x_range=tcfg.get("x_range", [-3, 3, 1]),
                        y_range=tcfg.get("y_range", [-3, 3, 1]),
                        z_range=tcfg.get("z_range", [-3, 3, 1]),
                    )
                    self.play(Create(axes_3d), run_time=anim_time * 0.4)

                if kind == "surface":
                    # Surface plot
                    # Security: eval controlled input only
                    func_str = tcfg.get("surface_func", "lambda u, v: np.array([u, v, u**2 + v**2])")
                    u_range = tcfg.get("u_range", [-2, 2])
                    v_range = tcfg.get("v_range", [-2, 2])
                    opacity = tcfg.get("opacity", 0.7)
                    colors = tcfg.get("color_gradient", [SURFACE_LOW, SURFACE_HIGH])

                    surf_func = eval(func_str)
                    surface = Surface(
                        surf_func,
                        u_range=u_range, v_range=v_range,
                        resolution=(32, 32),
                        fill_opacity=opacity,
                    )
                    surface.set_color_by_gradient(colors[0], colors[-1] if len(colors) > 1 else colors[0])
                    self.play(Create(surface), run_time=anim_time)
                    previous_replace = VGroup(axes_3d, surface) if tcfg.get("axes", True) else surface

                elif kind == "solid_of_revolution":
                    func_str = tcfg.get("curve_func", "lambda t: np.array([t, t**2, 0])")
                    t_range = tcfg.get("t_range", [0, 2])
                    opacity = tcfg.get("opacity", 0.6)
                    colors = tcfg.get("color_gradient", [SURFACE_LOW, SURFACE_HIGH])

                    curve_func = eval(func_str)
                    surface = Surface(
                        lambda u, v: np.array([
                            curve_func(u)[1] * np.cos(v),
                            curve_func(u)[1] * np.sin(v),
                            curve_func(u)[0],
                        ]),
                        u_range=t_range, v_range=[0, TAU],
                        resolution=(32, 32),
                        fill_opacity=opacity,
                    )
                    surface.set_color_by_gradient(colors[0], colors[-1] if len(colors) > 1 else colors[0])
                    self.play(Create(surface), run_time=anim_time)
                    previous_replace = VGroup(axes_3d, surface) if tcfg.get("axes", True) else surface

                elif kind == "coordinate_system":
                    # Just show the axes with labels
                    x_lbl = axes_3d.get_x_axis_label("x")
                    y_lbl = axes_3d.get_y_axis_label("y")
                    z_lbl = axes_3d.get_z_axis_label("z")
                    self.play(Write(x_lbl), Write(y_lbl), Write(z_lbl), run_time=0.5)
                    previous_replace = VGroup(axes_3d, x_lbl, y_lbl, z_lbl)

                else:
                    mob = Text(f"[3D: {kind}]", color=GREY, font_size=28)
                    self.play(FadeIn(mob), run_time=0.5)
                    previous_replace = mob

                remaining = max(0.2, duration - anim_time)
                self.wait(remaining)

                # Gentle camera rotation for visual interest
                if duration > 3:
                    self.begin_ambient_camera_rotation(rate=0.15)
                    self.wait(min(duration * 0.3, 2))
                    self.stop_ambient_camera_rotation()

                if idx < total - 1:
                    self.wait(EXTRA_HOLD)
                continue

            # ── STANDARD TYPES (text/math/mixed/box/diagram/graph/geometric) ─
            mob = _make_mobject(step)

            if mode == "build":
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace), run_time=0.3)
                    previous_replace = None

                build_lines.append(mob)
                if len(build_lines) > MAX_BUILD_LINES:
                    oldest = build_lines.pop(0)
                    self.play(FadeOut(oldest, shift=UP * 0.4), run_time=0.25)

                for i, ln in enumerate(build_lines):
                    target_y = TOP_Y - i * LINE_SPACING
                    ln.move_to([0, target_y, 0])

                mob.set_opacity(0)
                self.add(mob)
                self.play(mob.animate.set_opacity(1), run_time=anim_time)

            else:
                if build_lines:
                    self.play(*[FadeOut(ln, shift=UP * 0.3) for ln in build_lines], run_time=0.3)
                    build_lines.clear()

                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP * 0.3), run_time=0.35)

                mob.move_to(ORIGIN)
                if stype in ("box", "diagram", "graph", "geometric"):
                    self.play(FadeIn(mob, shift=UP * 0.3), run_time=anim_time)
                else:
                    self.play(Write(mob), run_time=anim_time)
                previous_replace = mob

            remaining = max(0.2, duration - anim_time - 0.35)
            self.wait(remaining)

            if idx < total - 1:
                self.wait(EXTRA_HOLD)

        # ── FINALE ──────────────────────────────────────────────
        final_mob = previous_replace or (build_lines[-1] if build_lines else None)
        if final_mob:
            box = SurroundingRectangle(
                final_mob, color=NEON_GREEN, buff=0.3,
                stroke_width=4, corner_radius=0.1,
            )
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)
            extras = [FadeOut(box)]
            if previous_replace:
                extras.append(FadeOut(previous_replace))
            for ln in build_lines:
                extras.append(FadeOut(ln))
            self.play(*extras, run_time=0.5)


if __name__ == "__main__":
    print("Render with:  manim -ql this_file.py SyncedProofScene")
