"""
bridge.py — Question Engine → Video Engine Bridge
==================================================
Connects the Axiom Question Engine (TypeScript) to the Orbital Video Engine
(Python). Given a question templateId and seed, it generates the question
and maps it to a video manifest.

Two modes:
  1. JSON file mode:  reads a pre-exported question JSON file
  2. Live mode:       calls the TypeScript engine via Node.js subprocess

The bridge handles the impedance mismatch between the TS and Python worlds:
  - Runs `npx tsx` to execute a small TS shim that generates the question
  - Falls back to reading a JSON file if Node.js or the TS engine aren't available
  - Normalizes the output to Python dict format

Usage
-----
    from bridge import Bridge

    bridge = Bridge()

    # From a JSON file (most reliable)
    manifest = bridge.from_json("sample_questions/examples.json", index=0)

    # From the live TypeScript engine (requires Node.js + Axiom Platform)
    manifest = bridge.from_template("solve-linear-1step", seed=42)

    # Full pipeline with rendering
    video_path = bridge.render("solve-linear-1step", seed=42, output="out.mp4")

Architecture
------------
The TS engine generates questions like:
    {
        "templateId": "solve-linear-1step",
        "questionText": "Solve: 3x + 7 = 22",
        "correctAnswer": "5",
        "solution": "Step 1: ...",
        ...
    }

This JSON is passed to VideoEngine.generate_manifest() to get a Manim manifest,
which is then passed to render.render_manifest() to get a video.
"""

import json
import os
import sys
import subprocess
from pathlib import Path
from typing import Optional

# Ensure video-engine modules are importable
sys.path.insert(0, str(Path(__file__).parent))

from video_engine import VideoEngine, generate_manifest as _generate_manifest
from render import render_manifest, preview_manifest


# ─── Path Constants ───────────────────────────────────────────────────────────

# Axiom Platform TypeScript project
AXIOM_PLATFORM = Path.home() / "Desktop" / "Axiom-Platform"
AXIOM_APP      = AXIOM_PLATFORM / "app"

# Node.js / TypeScript executor
# Try tsx (fast TS runner) then ts-node then npx tsx
TS_SHIM_PATH = Path(__file__).parent / "_ts_shim.mjs"


# ─── TypeScript Shim ──────────────────────────────────────────────────────────

# Minimal Node.js shim that generates one question and prints JSON.
# This is written to disk and executed via subprocess.
TS_SHIM_TEMPLATE = '''
// _ts_shim.mjs — Temporary shim to call Axiom Question Engine from Python
// Generated by bridge.py — do not edit manually

import {{ execSync }} from 'child_process';
import {{ writeFileSync }} from 'fs';

// Dynamic import for the question engine (Next.js/TS module)
const templateId = process.argv[2] || 'solve-linear-1step';
const seed = parseInt(process.argv[3] || '42');

// Try to use the Axiom engine via tsx
try {{
    const result = execSync(
        `npx tsx -e "
            import {{ generateQuestion }} from './src/lib/question-engine.ts';
            const q = generateQuestion('${{templateId}}', ${{seed}});
            console.log(JSON.stringify(q));
        "`,
        {{ cwd: '{axiom_app}', encoding: 'utf-8', timeout: 30000 }}
    );
    process.stdout.write(result);
}} catch (e) {{
    process.stderr.write('TS engine failed: ' + e.message);
    process.exit(1);
}}
'''


# ─── Bridge Class ─────────────────────────────────────────────────────────────

class Bridge:
    """
    Connects the Axiom Question Engine to the Orbital Video Engine.

    Provides multiple ways to feed question data into the video engine:
      - from_json():     load from a JSON file
      - from_dict():     pass question data directly as a Python dict
      - from_template(): call the live TypeScript engine
    """

    def __init__(self):
        self.engine = VideoEngine()
        self._node_available = self._check_node()
        self._ts_available   = self._check_ts()

    def _check_node(self) -> bool:
        """Check if Node.js is available."""
        try:
            result = subprocess.run(
                ["node", "--version"],
                capture_output=True, text=True, timeout=5
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def _check_ts(self) -> bool:
        """Check if tsx (TypeScript runner) is available in Axiom Platform."""
        if not self._node_available:
            return False
        if not AXIOM_APP.exists():
            return False
        try:
            result = subprocess.run(
                ["npx", "tsx", "--version"],
                capture_output=True, text=True, timeout=10,
                cwd=str(AXIOM_APP)
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    # ── Public Methods ─────────────────────────────────────────────────────

    def from_dict(self, question_data: dict) -> list[dict]:
        """
        Generate a manifest directly from a question data dict.
        This is the simplest path — no file I/O or subprocess needed.

        Args:
            question_data: dict matching the Axiom GeneratedQuestion interface

        Returns:
            Manim manifest (list of step dicts)
        """
        print(f"  🌉 Bridge: processing {question_data.get('templateId', '?')}")
        return self.engine.generate_manifest(question_data)

    def from_json(self, json_path: str, index: int = 0) -> list[dict]:
        """
        Load a question from a JSON file and generate its manifest.

        The JSON file can be:
          - A single question object: { "templateId": ..., "questionText": ... }
          - A list of questions: [ {...}, {...}, ... ]
          - An object with an "examples" key: { "examples": [...] }

        Args:
            json_path: Path to the JSON file
            index:     Which question to use (if file contains a list)

        Returns:
            Manim manifest
        """
        with open(json_path) as f:
            data = json.load(f)

        # Handle different JSON structures
        if isinstance(data, list):
            question_data = data[index]
        elif isinstance(data, dict) and "examples" in data:
            question_data = data["examples"][index]
        elif isinstance(data, dict) and "templateId" in data:
            question_data = data
        else:
            raise ValueError(
                f"Unexpected JSON structure in {json_path}. "
                f"Expected a question dict or list of questions."
            )

        print(f"  🌉 Bridge: loaded '{question_data.get('templateId', '?')}' from {json_path}")
        return self.engine.generate_manifest(question_data)

    def from_template(self, template_id: str, seed: int = 42) -> list[dict]:
        """
        Generate a question using the live TypeScript Axiom engine and get its manifest.

        Falls back to a static example if the TS engine isn't available.

        Args:
            template_id: Axiom question template ID (e.g. "solve-linear-1step")
            seed:        Random seed for deterministic question generation

        Returns:
            Manim manifest
        """
        print(f"  🌉 Bridge: generating question from TS engine...")
        print(f"     template_id={template_id}, seed={seed}")

        if not self._node_available:
            print("  ⚠️  Node.js not available — using fallback sample question")
            return self._fallback_question(template_id)

        if not self._ts_available:
            print("  ⚠️  TypeScript runner not available — using fallback sample question")
            return self._fallback_question(template_id)

        # Try calling the TS engine
        question_data = self._call_ts_engine(template_id, seed)
        if question_data is None:
            print("  ⚠️  TS engine call failed — using fallback sample question")
            return self._fallback_question(template_id)

        return self.engine.generate_manifest(question_data)

    def render(
        self,
        template_id: str,
        seed: int = 42,
        output: str = "output/video.mp4",
        question_data: Optional[dict] = None,
    ) -> str:
        """
        Full pipeline: question → manifest → video.

        Args:
            template_id:    Axiom template ID (used if question_data not given)
            seed:           Random seed
            output:         Output path for the rendered mp4
            question_data:  Direct question data (skips TS engine if provided)

        Returns:
            Path to rendered video
        """
        if question_data is not None:
            manifest = self.from_dict(question_data)
        else:
            manifest = self.from_template(template_id, seed)

        print(f"  🎬 Rendering {len(manifest)} steps → {output}")
        return render_manifest(manifest, output)

    def preview(self, template_id: str, seed: int = 42) -> str:
        """Preview a manifest without rendering."""
        manifest = self.from_template(template_id, seed)
        return preview_manifest(manifest)

    # ── Internal Helpers ────────────────────────────────────────────────────

    def _call_ts_engine(self, template_id: str, seed: int) -> Optional[dict]:
        """
        Call the Axiom TypeScript engine via subprocess.

        Executes a small TS snippet that imports question-engine.ts and
        generates a question, then returns the JSON output.

        Returns:
            Parsed question dict, or None on failure
        """
        ts_code = (
            f"import {{ generateQuestion }} from './src/lib/question-engine.ts';"
            f"const q = generateQuestion('{template_id}', {seed});"
            f"console.log(JSON.stringify(q));"
        )

        try:
            result = subprocess.run(
                ["npx", "tsx", "-e", ts_code],
                capture_output=True, text=True, timeout=30,
                cwd=str(AXIOM_APP)
            )

            if result.returncode != 0:
                print(f"  ⚠️  tsx error: {result.stderr[:300]}")
                return None

            return json.loads(result.stdout.strip())

        except (subprocess.TimeoutExpired, json.JSONDecodeError, FileNotFoundError) as e:
            print(f"  ⚠️  TS engine error: {e}")
            return None

    def _fallback_question(self, template_id: str) -> list[dict]:
        """
        Return a manifest for a hardcoded fallback question.
        Used when the TS engine isn't available.
        """
        # Map common templateIds to fallback questions
        fallbacks = {
            "solve-linear-1step": {
                "templateId": "solve-linear-1step",
                "questionText": "Solve: 3x + 7 = 22",
                "correctAnswer": "5",
                "solution": (
                    "Step 1: Subtract 7 from both sides.\n"
                    "3x + 7 - 7 = 22 - 7\n"
                    "3x = 15\n"
                    "Step 2: Divide both sides by 3.\n"
                    "x = 15/3\n"
                    "x = 5"
                ),
                "difficulty": "easy",
                "skill": "linear-equations",
                "hint": "Isolate the variable step by step.",
                "section": "Algebra",
            },
            "factor-quadratic-leading-1": {
                "templateId": "factor-quadratic-leading-1",
                "questionText": "Factor: x² + 5x + 6",
                "correctAnswer": "(x + 2)(x + 3)",
                "solution": (
                    "Step 1: Find two numbers that multiply to 6 and add to 5.\n"
                    "Factors of 6: 1×6=6, 2×3=6\n"
                    "2 + 3 = 5\n"
                    "Step 2: Write the factored form.\n"
                    "x² + 5x + 6 = (x + 2)(x + 3)"
                ),
                "difficulty": "medium",
                "skill": "factoring-quadratics",
                "hint": "Find factor pairs of the constant term.",
                "section": "Algebra",
            },
        }

        # Use specific fallback, or try to find a reasonable one by category
        question_data = fallbacks.get(template_id)
        if not question_data:
            # Category-based fallback
            if "factor" in template_id:
                question_data = fallbacks["factor-quadratic-leading-1"]
            else:
                question_data = fallbacks["solve-linear-1step"]

        print(f"  📌 Using fallback question for '{template_id}'")
        return self.engine.generate_manifest(question_data)

    def info(self) -> dict:
        """Return bridge diagnostics."""
        return {
            "node_available": self._node_available,
            "ts_available": self._ts_available,
            "axiom_platform_path": str(AXIOM_PLATFORM),
            "axiom_app_path": str(AXIOM_APP),
            "axiom_app_exists": AXIOM_APP.exists(),
            "registered_templates": self.engine.get_template_info(),
        }


# ─── CLI Entry Point ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Bridge: Axiom Question Engine → Orbital Video Engine"
    )
    parser.add_argument(
        "template_id",
        nargs="?",
        default="solve-linear-1step",
        help="Axiom question template ID"
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed for question generation (default: 42)"
    )
    parser.add_argument(
        "--render", metavar="OUTPUT.mp4",
        help="Render the video to this path"
    )
    parser.add_argument(
        "--json", metavar="QUESTION.json",
        help="Load question from JSON file instead of TS engine"
    )
    parser.add_argument(
        "--index", type=int, default=0,
        help="Index into JSON array (when using --json with a list)"
    )
    parser.add_argument(
        "--info", action="store_true",
        help="Show bridge diagnostics"
    )

    args = parser.parse_args()
    bridge = Bridge()

    if args.info:
        print(json.dumps(bridge.info(), indent=2))
        sys.exit(0)

    if args.json:
        manifest = bridge.from_json(args.json, index=args.index)
    else:
        manifest = bridge.from_template(args.template_id, seed=args.seed)

    if args.render:
        video_path = render_manifest(manifest, args.render)
        print(f"\n  ✓ Video rendered: {video_path}")
    else:
        print(preview_manifest(manifest))
        print("\nAdd --render OUTPUT.mp4 to render the video.")
