"""
Auto-generated Manim scene with audio-synced timings.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *

ORBITAL_VIOLET = "#8B5CF6"
ORBITAL_CYAN = "#22D3EE"

# Timing configuration
EXTRA_HOLD_PER_STEP = 0.8  # extra pause after each step
ANIMATION_RATIO = 0.35  # animation takes this % of step duration

class SyncedMathScene(Scene):
    """
    Math scene with timings synced to audio.
    Intro duration: 2.0s (handled separately)
    """
    
    def construct(self):
        self.camera.background_color = "#000000"
        
        # Step timings from audio (in seconds)
        steps = [
        {
                "step": 0,
                "narration": "Let's simplify the expression x plus three times x minus two.",
                "latex": "(x + 3)(x - 2)",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_00.mp3",
                "duration": 3.65
        },
        {
                "step": 1,
                "narration": "We can use the FOIL method to multiply these two binomials. FOIL stands for First, Outer, Inner, Last.",
                "latex": "\\text{FOIL: First, Outer, Inner, Last}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_01.mp3",
                "duration": 5.78
        },
        {
                "step": 2,
                "narration": "First, multiply the First terms from each binomial: x from the first and x from the second.",
                "latex": "\\text{First: } x \\cdot x = x^2",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_02.mp3",
                "duration": 5.54
        },
        {
                "step": 3,
                "narration": "Outer, multiply the Outer terms: x from the first and negative two from the second.",
                "latex": "\\text{Outer: } x \\cdot (-2) = -2x",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_03.mp3",
                "duration": 5.11
        },
        {
                "step": 4,
                "narration": "Inner, multiply the Inner terms: three from the first and x from the second.",
                "latex": "\\text{Inner: } 3 \\cdot x = 3x",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_04.mp3",
                "duration": 4.61
        },
        {
                "step": 5,
                "narration": "Last, multiply the Last terms: three from the first and negative two from the second.",
                "latex": "\\text{Last: } 3 \\cdot (-2) = -6",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_05.mp3",
                "duration": 5.3
        },
        {
                "step": 6,
                "narration": "Now, let's write all four terms we got from FOIL.",
                "latex": "x^2 + (-2x) + 3x + (-6)",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_06.mp3",
                "duration": 2.81
        },
        {
                "step": 7,
                "narration": "We can rewrite this without the parentheses around the negative terms.",
                "latex": "x^2 - 2x + 3x - 6",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_07.mp3",
                "duration": 3.5
        },
        {
                "step": 8,
                "narration": "Now, we combine like terms. The like terms are negative two x and positive three x.",
                "latex": "-2x + 3x = 1x",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_08.mp3",
                "duration": 5.06
        },
        {
                "step": 9,
                "narration": "One x is usually just written as x.",
                "latex": "1x = x",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_09.mp3",
                "duration": 2.14
        },
        {
                "step": 10,
                "narration": "So, our simplified expression is x squared plus x minus six.",
                "latex": "x^2 + x - 6",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/f72d78be/audio/step_10.mp3",
                "duration": 3.79
        }
]
        
        previous = None
        total_steps = len(steps)
        
        for i, step in enumerate(steps):
            latex = step["latex"]
            duration = step["duration"]
            
            # Calculate animation time (slower write at 35% of duration)
            anim_time = max(1.2, duration * ANIMATION_RATIO)
            # Pause syncs with remaining audio time
            pause_time = max(0.3, duration - anim_time)
            
            # Create math object
            math = MathTex(latex, color=WHITE)
            math.scale(1.6)
            
            if previous is None:
                # First step: write on
                self.play(Write(math), run_time=anim_time)
            else:
                # Transform or fade transition
                self.play(
                    FadeOut(previous, shift=UP * 0.3),
                    run_time=0.4
                )
                self.play(Write(math), run_time=anim_time)
            
            # Pause to match audio duration
            self.wait(pause_time)
            
            # Extra hold time after each step (let viewer absorb)
            if i < total_steps - 1:  # not on final step
                self.wait(EXTRA_HOLD_PER_STEP)
            
            previous = math
        
        # Final answer: highlight box and hold
        if previous:
            box = SurroundingRectangle(previous, color=ORBITAL_VIOLET, buff=0.25)
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)  # hold final answer
            self.play(FadeOut(previous), FadeOut(box), run_time=0.5)


if __name__ == "__main__":
    print("Render with: manim -ql {this_file} SyncedMathScene")
