"""
Auto-generated Manim scene (v2) with proof/text support.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *
import json, os

ORBITAL_VIOLET  = "#8B5CF6"
ORBITAL_CYAN    = "#22D3EE"
NEON_GREEN      = "#39FF14"
BOX_BORDER      = "#8B5CF6"
BOX_FILL        = "#1a1130"
LABEL_COLOR     = "#22D3EE"

MAX_BUILD_LINES  = 5
TOP_Y            = 3.0
LINE_SPACING     = 0.85
EXTRA_HOLD       = 0.8
ANIMATION_RATIO  = 0.35
WATERMARK_TEXT    = "ORBITAL"


def _make_mobject(step: dict):
    """Create the correct Manim object for a step type."""
    stype   = step.get("type", "math")
    content = step.get("content") or step.get("latex", "")
    label   = step.get("label", "")

    if stype == "math":
        mob = MathTex(content, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "text":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "mixed":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "box":
        inner = Tex(content, color=WHITE)
        inner.scale(0.85)
        lbl = Tex(r"\textbf{" + label + "}", color=LABEL_COLOR)
        lbl.scale(0.7)

        box_rect = SurroundingRectangle(
            inner, color=BOX_BORDER, fill_color=BOX_FILL,
            fill_opacity=0.6, buff=0.35, corner_radius=0.12,
            stroke_width=2,
        )
        lbl.next_to(box_rect, UP, buff=0.15).align_to(box_rect, LEFT).shift(RIGHT * 0.2)
        group = VGroup(box_rect, lbl, inner)
        return group

    # fallback
    mob = MathTex(content, color=WHITE)
    mob.scale(1.4)
    return mob


class SyncedProofScene(Scene):
    def construct(self):
        self.camera.background_color = "#000000"

        wm = Text(WATERMARK_TEXT, font_size=14, color=WHITE).set_opacity(0.35)
        wm.to_corner(DR, buff=0.3)
        self.add(wm)

        steps = [
        {
                "step": 0,
                "narration": "Let's prove that every group of order fifteen is cyclic, without using the Sylow theorems.",
                "latex": "",
                "content": "Every group of order 15 is cyclic.",
                "type": "box",
                "mode": "replace",
                "label": "Theorem",
                "audio_path": "jobs/group_order_15/audio/step_00.mp3",
                "duration": 5.8
        },
        {
                "step": 1,
                "narration": "Let G be a group with order fifteen. Note that fifteen factors as three times five.",
                "latex": "",
                "content": "Let $G$ be a group with $|G| = 15 = 3 \\cdot 5$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_01.mp3",
                "duration": 5.8
        },
        {
                "step": 2,
                "narration": "By Cauchy's Theorem, since three divides the order of G,",
                "latex": "",
                "content": "By Cauchy's Theorem, since 3 divides $|G|$,",
                "type": "text",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_02.mp3",
                "duration": 3.67
        },
        {
                "step": 3,
                "narration": "there exists an element a in G of order three.",
                "latex": "",
                "content": "$\\exists\\, a \\in G$ with $\\text{ord}(a) = 3$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_03.mp3",
                "duration": 3.25
        },
        {
                "step": 4,
                "narration": "Similarly, since five divides the order of G,",
                "latex": "",
                "content": "Similarly, since 5 divides $|G|$,",
                "type": "text",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_04.mp3",
                "duration": 3.3
        },
        {
                "step": 5,
                "narration": "there exists an element b in G of order five.",
                "latex": "",
                "content": "$\\exists\\, b \\in G$ with $\\text{ord}(b) = 5$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_05.mp3",
                "duration": 3.58
        },
        {
                "step": 6,
                "narration": "Let H be the cyclic subgroup generated by a. Then H has order three.",
                "latex": "",
                "content": "Let $H = \\langle a \\rangle$, so $|H| = 3$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_06.mp3",
                "duration": 5.57
        },
        {
                "step": 7,
                "narration": "The index of H in G is fifteen over three, which equals five.",
                "latex": "",
                "content": "$[G : H] = \\frac{|G|}{|H|} = \\frac{15}{3} = 5$",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_07.mp3",
                "duration": 4.41
        },
        {
                "step": 8,
                "narration": "Now here's the key fact: if the index of a subgroup equals the smallest prime dividing the order of G, then that subgroup is normal.",
                "latex": "",
                "content": "If $[G : H]$ is the smallest prime dividing $|G|$, then $H \\trianglelefteq G$.",
                "type": "box",
                "mode": "build",
                "label": "Key Fact",
                "audio_path": "jobs/group_order_15/audio/step_08.mp3",
                "duration": 8.78
        },
        {
                "step": 9,
                "narration": "The smallest prime dividing fifteen is three, but the index is five, which is bigger than three. So this fact doesn't apply to H directly.",
                "latex": "",
                "content": "The smallest prime dividing $15$ is $3$, and $[G:H] = 5 > 3$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_09.mp3",
                "duration": 9.01
        },
        {
                "step": 10,
                "narration": "Instead, let K be the cyclic subgroup generated by b. Then K has order five, and the index of K in G is three.",
                "latex": "",
                "content": "Let $K = \\langle b \\rangle$, so $|K| = 5$ and $[G:K] = 3$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_10.mp3",
                "duration": 8.31
        },
        {
                "step": 11,
                "narration": "Three is indeed the smallest prime dividing fifteen.",
                "latex": "",
                "content": "$3$ is the smallest prime dividing $|G| = 15$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_11.mp3",
                "duration": 3.53
        },
        {
                "step": 12,
                "narration": "Therefore, K is a normal subgroup of G.",
                "latex": "",
                "content": "Therefore $K \\trianglelefteq G$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_12.mp3",
                "duration": 2.93
        },
        {
                "step": 13,
                "narration": "Now, since the orders of H and K are three and five, and gcd of three and five is one:",
                "latex": "",
                "content": "Since $|H| = 3$ and $|K| = 5$, and $\\gcd(3,5) = 1$:",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_13.mp3",
                "duration": 5.94
        },
        {
                "step": 14,
                "narration": "H and K intersect only at the identity.",
                "latex": "",
                "content": "H \\cap K = \\{e\\}",
                "type": "math",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_14.mp3",
                "duration": 3.02
        },
        {
                "step": 15,
                "narration": "By the product formula, the size of H K equals three times five over one, which is fifteen. That's the entire group.",
                "latex": "",
                "content": "|HK| = \\frac{|H| \\cdot |K|}{|H \\cap K|} = \\frac{3 \\cdot 5}{1} = 15 = |G|",
                "type": "math",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_15.mp3",
                "duration": 8.08
        },
        {
                "step": 16,
                "narration": "So G equals H K, with trivial intersection and K normal.",
                "latex": "",
                "content": "So $G = HK$ with $H \\cap K = \\{e\\}$ and $K \\trianglelefteq G$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_16.mp3",
                "duration": 4.69
        },
        {
                "step": 17,
                "narration": "Since K is normal, for any h in H and k in K,",
                "latex": "",
                "content": "Since K is normal, for any h in H and k in K:",
                "type": "text",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_17.mp3",
                "duration": 4.13
        },
        {
                "step": 18,
                "narration": "the commutator h k h inverse k inverse lies in K,",
                "latex": "",
                "content": "hkh^{-1}k^{-1} \\in K",
                "type": "math",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_18.mp3",
                "duration": 4.74
        },
        {
                "step": 19,
                "narration": "and by rearranging, we can show it also lies in H.",
                "latex": "",
                "content": "and by rearranging, it also lies in H.",
                "type": "text",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_19.mp3",
                "duration": 3.9
        },
        {
                "step": 20,
                "narration": "So the commutator lies in H intersect K, which is just the identity.",
                "latex": "",
                "content": "So $hkh^{-1}k^{-1} \\in H \\cap K = \\{e\\}$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_20.mp3",
                "duration": 5.25
        },
        {
                "step": 21,
                "narration": "Therefore h k equals k h. Every element of H commutes with every element of K.",
                "latex": "",
                "content": "hk = kh \\quad \\forall\\, h \\in H,\\; k \\in K",
                "type": "math",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_21.mp3",
                "duration": 6.69
        },
        {
                "step": 22,
                "narration": "Now consider the element a b. Since gcd of three and five is one:",
                "latex": "",
                "content": "Consider $ab \\in G$. Since $\\gcd(3,5) = 1$:",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_22.mp3",
                "duration": 4.74
        },
        {
                "step": 23,
                "narration": "the order of a b equals the order of a times the order of b, which is three times five, equals fifteen.",
                "latex": "",
                "content": "\\text{ord}(ab) = \\text{ord}(a) \\cdot \\text{ord}(b) = 3 \\cdot 5 = 15",
                "type": "math",
                "mode": "build",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_23.mp3",
                "duration": 7.29
        },
        {
                "step": 24,
                "narration": "So a b generates all of G, which means G is cyclic. And that completes our proof.",
                "latex": "",
                "content": "$\\langle ab \\rangle = G$, so $G$ is cyclic. $\\blacksquare$",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "audio_path": "jobs/group_order_15/audio/step_24.mp3",
                "duration": 5.57
        }
]

        build_lines = []
        previous_replace = None
        total = len(steps)

        for idx, step in enumerate(steps):
            duration   = step.get("duration", 2.0)
            audio_path = step.get("audio_path", "")
            mode       = step.get("mode", "replace")
            stype      = step.get("type", "math")

            if audio_path and os.path.exists(audio_path):
                self.add_sound(audio_path)

            anim_time = max(0.8, duration * ANIMATION_RATIO)
            mob = _make_mobject(step)

            if mode == "build":
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace), run_time=0.3)
                    previous_replace = None

                build_lines.append(mob)

                if len(build_lines) > MAX_BUILD_LINES:
                    oldest = build_lines.pop(0)
                    self.play(FadeOut(oldest, shift=UP * 0.4), run_time=0.25)

                for i, ln in enumerate(build_lines):
                    target_y = TOP_Y - i * LINE_SPACING
                    ln.move_to([0, target_y, 0])

                mob.set_opacity(0)
                self.add(mob)
                self.play(mob.animate.set_opacity(1), run_time=anim_time)

            else:
                if build_lines:
                    self.play(
                        *[FadeOut(ln, shift=UP * 0.3) for ln in build_lines],
                        run_time=0.3
                    )
                    build_lines.clear()

                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP * 0.3), run_time=0.35)

                mob.move_to(ORIGIN)
                if stype == "box":
                    self.play(FadeIn(mob, shift=UP * 0.3), run_time=anim_time)
                else:
                    self.play(Write(mob), run_time=anim_time)
                previous_replace = mob

            remaining = max(0.2, duration - anim_time - 0.35)
            self.wait(remaining)

            if idx < total - 1:
                self.wait(EXTRA_HOLD)

        # finale
        final_mob = previous_replace or (build_lines[-1] if build_lines else None)
        if final_mob:
            box = SurroundingRectangle(
                final_mob, color=NEON_GREEN, buff=0.3,
                stroke_width=4, corner_radius=0.1,
            )
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)
            extras = [FadeOut(box)]
            if previous_replace:
                extras.append(FadeOut(previous_replace))
            for ln in build_lines:
                extras.append(FadeOut(ln))
            self.play(*extras, run_time=0.5)


if __name__ == "__main__":
    print("Render with:  manim -ql this_file.py SyncedProofScene")
