"""
Auto-generated Manim scene with audio-synced timings.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *

ORBITAL_VIOLET = "#8B5CF6"
ORBITAL_CYAN = "#22D3EE"

# Timing configuration
EXTRA_HOLD_PER_STEP = 0.8  # extra pause after each step
ANIMATION_RATIO = 0.35  # animation takes this % of step duration

class SyncedMathScene(Scene):
    """
    Math scene with timings synced to audio.
    Intro duration: 2.0s (handled separately)
    """
    
    def construct(self):
        self.camera.background_color = "#000000"
        
        # Step timings from audio (in seconds)
        steps = [
        {
                "step": 0,
                "narration": "Let's prove by induction that the sum of the first n natural numbers is n times n plus one over two.",
                "latex": "1 + 2 + 3 + \\ldots + n = \\frac{n(n+1)}{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_00.mp3",
                "duration": 6.55
        },
        {
                "step": 1,
                "narration": "First, we'll check the base case where n equals one.",
                "latex": "1 = \\frac{1(1+1)}{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_01.mp3",
                "duration": 3.53
        },
        {
                "step": 2,
                "narration": "Simplifying the right side, we get one equals one, which is true.",
                "latex": "1 = 1",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_02.mp3",
                "duration": 4.46
        },
        {
                "step": 3,
                "narration": "Now, assume the formula is true for some positive integer k. This is our induction hypothesis.",
                "latex": "1 + 2 + 3 + \\ldots + k = \\frac{k(k+1)}{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_03.mp3",
                "duration": 6.69
        },
        {
                "step": 4,
                "narration": "We need to prove it's true for k plus one. So, consider the sum up to k plus one.",
                "latex": "1 + 2 + 3 + \\ldots + k + (k+1)",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_04.mp3",
                "duration": 4.69
        },
        {
                "step": 5,
                "narration": "Using our hypothesis, replace the sum up to k with k times k plus one over two.",
                "latex": "\\frac{k(k+1)}{2} + (k+1)",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_05.mp3",
                "duration": 6.18
        },
        {
                "step": 6,
                "narration": "Let's combine these terms over a common denominator.",
                "latex": "\\frac{k(k+1) + 2(k+1)}{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_06.mp3",
                "duration": 3.16
        },
        {
                "step": 7,
                "narration": "Factor out k plus one from the numerator.",
                "latex": "\\frac{(k+1)(k+2)}{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_07.mp3",
                "duration": 2.93
        },
        {
                "step": 8,
                "narration": "This matches the formula for n equals k plus one. So, the formula holds for k plus one.",
                "latex": "\\frac{(k+1)((k+1)+1)}{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_08.mp3",
                "duration": 6.32
        },
        {
                "step": 9,
                "narration": "Since both the base case and the induction step are true, the formula is proven for all positive integers n.",
                "latex": "1 + 2 + 3 + \\ldots + n = \\frac{n(n+1)}{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/b990d88c/audio/step_09.mp3",
                "duration": 7.2
        }
]
        
        previous = None
        total_steps = len(steps)
        
        for i, step in enumerate(steps):
            latex = step["latex"]
            duration = step["duration"]
            
            # Calculate animation time (slower write at 35% of duration)
            anim_time = max(1.2, duration * ANIMATION_RATIO)
            # Pause syncs with remaining audio time
            pause_time = max(0.3, duration - anim_time)
            
            # Create math object
            math = MathTex(latex, color=WHITE)
            math.scale(1.6)
            
            if previous is None:
                # First step: write on
                self.play(Write(math), run_time=anim_time)
            else:
                # Transform or fade transition
                self.play(
                    FadeOut(previous, shift=UP * 0.3),
                    run_time=0.4
                )
                self.play(Write(math), run_time=anim_time)
            
            # Pause to match audio duration
            self.wait(pause_time)
            
            # Extra hold time after each step (let viewer absorb)
            if i < total_steps - 1:  # not on final step
                self.wait(EXTRA_HOLD_PER_STEP)
            
            previous = math
        
        # Final answer: highlight box and hold
        if previous:
            box = SurroundingRectangle(previous, color=ORBITAL_VIOLET, buff=0.25)
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)  # hold final answer
            self.play(FadeOut(previous), FadeOut(box), run_time=0.5)


if __name__ == "__main__":
    print("Render with: manim -ql {this_file} SyncedMathScene")
