"""
Auto-generated Manim scene (v3) with full visual support.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *
import json, os, math

# ── colours ──────────────────────────────────────────────────────
ORBITAL_VIOLET  = "#8B5CF6"
ORBITAL_CYAN    = "#22D3EE"
NEON_GREEN      = "#39FF14"
BOX_BORDER      = "#8B5CF6"
BOX_FILL        = "#1a1130"
LABEL_COLOR     = "#22D3EE"
CUT_LEFT        = "#4F46E5"
CUT_RIGHT       = "#F97316"
CUT_POINT       = "#FACC15"
SEQ_HIGHLIGHT   = "#F43F5E"
TABLE_HEADER    = "#8B5CF6"
TABLE_CELL      = "#1E1B4B"
GRAPH_BLUE      = "#3B82F6"
GRAPH_ORANGE    = "#F97316"
GRAPH_PINK      = "#EC4899"
GEOM_TEAL       = "#14B8A6"
SURFACE_LOW     = "#4F46E5"
SURFACE_HIGH    = "#F97316"

# ── layout constants ─────────────────────────────────────────────
MAX_BUILD_LINES  = 5
TOP_Y            = 3.0
LINE_SPACING     = 0.85
EXTRA_HOLD       = 0.8
ANIMATION_RATIO  = 0.35
WATERMARK_TEXT    = "ORBITAL"


# ═══════════════════════════════════════════════════════════════════
#  DIAGRAM BUILDERS (v2 — unchanged)
# ═══════════════════════════════════════════════════════════════════

def _build_number_line_cut(cfg: dict) -> VGroup:
    x_range   = cfg.get("x_range", [-4, 4, 1])
    cut_at    = cfg.get("cut_at", 0)
    left_lbl  = cfg.get("left_label", "A")
    right_lbl = cfg.get("right_label", "B")
    cut_lbl   = cfg.get("cut_label", "")
    show_pt   = cfg.get("show_point", True)

    nl = NumberLine(x_range=x_range, length=10, include_numbers=True,
                    include_tip=True, font_size=24, color=WHITE)
    group = VGroup(nl)

    left_start = nl.n2p(x_range[0])[0]
    cut_x      = nl.n2p(cut_at)[0]
    right_end  = nl.n2p(x_range[1])[0]
    line_y     = nl.get_center()[1]
    region_h = 0.5

    if cut_x - left_start > 0.1:
        left_rect = Rectangle(width=cut_x - left_start, height=region_h,
                              fill_color=CUT_LEFT, fill_opacity=0.35, stroke_width=0)
        left_rect.move_to([(left_start + cut_x) / 2, line_y, 0])
        group.add(left_rect)
        ll = MathTex(left_lbl, color=CUT_LEFT, font_size=36)
        ll.next_to(left_rect, UP, buff=0.3)
        group.add(ll)

    if right_end - cut_x > 0.1:
        right_rect = Rectangle(width=right_end - cut_x, height=region_h,
                               fill_color=CUT_RIGHT, fill_opacity=0.35, stroke_width=0)
        right_rect.move_to([(cut_x + right_end) / 2, line_y, 0])
        group.add(right_rect)
        rl = MathTex(right_lbl, color=CUT_RIGHT, font_size=36)
        rl.next_to(right_rect, UP, buff=0.3)
        group.add(rl)

    if show_pt:
        dot = Dot(nl.n2p(cut_at), color=CUT_POINT, radius=0.1)
        group.add(dot)
    if cut_lbl:
        cl = MathTex(cut_lbl, color=CUT_POINT, font_size=36)
        cl.next_to(nl.n2p(cut_at), DOWN, buff=0.35)
        group.add(cl)

    dash = DashedLine(start=nl.n2p(cut_at) + UP * 0.8, end=nl.n2p(cut_at) + DOWN * 0.2,
                      color=CUT_POINT, stroke_width=2)
    group.add(dash)
    group.scale(0.75)
    return group


def _build_set_containment(cfg: dict) -> VGroup:
    sets = cfg.get("sets", [
        {"label": "A", "radius": 1.5, "position": [-0.5, 0], "color": "#4F46E5"},
        {"label": "B", "radius": 1.5, "position": [0.5, 0], "color": "#F97316"},
    ])
    group = VGroup()
    for s in sets:
        circ = Circle(radius=s.get("radius", 1.5), color=s.get("color", WHITE),
                      fill_opacity=0.15, stroke_width=2)
        pos = s.get("position", [0, 0])
        circ.move_to([pos[0], pos[1], 0])
        lbl = MathTex(s.get("label", ""), color=s.get("color", WHITE), font_size=36)
        lbl.move_to(circ.get_center() + UP * (s.get("radius", 1.5) + 0.3))
        group.add(circ, lbl)
    group.scale(0.8)
    return group


def _build_sequence_list(cfg: dict) -> VGroup:
    items     = cfg.get("items", ["r_1", "r_2", "r_3", "\\dots"])
    highlight = cfg.get("highlight", [])
    label     = cfg.get("label", "")
    parts = []
    for i, item in enumerate(items):
        color = SEQ_HIGHLIGHT if i in highlight else WHITE
        m = MathTex(item, color=color, font_size=40)
        parts.append(m)
        if i < len(items) - 1:
            comma = MathTex(",", color=GREY, font_size=40)
            parts.append(comma)
    row = VGroup(*parts).arrange(RIGHT, buff=0.2)
    group = VGroup(row)
    if label:
        lbl = Tex(label, color=LABEL_COLOR, font_size=32)
        lbl.next_to(row, UP, buff=0.4)
        group.add(lbl)
    group.scale(0.85)
    return group


def _build_table(cfg: dict) -> VGroup:
    headers = cfg.get("headers", [])
    rows    = cfg.get("rows", [])
    hl      = cfg.get("highlight_cells", [])
    all_rows = []
    if headers:
        all_rows.append(headers)
    all_rows.extend(rows)

    group = VGroup()
    cell_w = 1.4
    cell_h = 0.6
    for r, row in enumerate(all_rows):
        for c, cell in enumerate(row):
            m = MathTex(cell, font_size=30)
            if r == 0 and headers:
                m.set_color(LABEL_COLOR)
            for hr, hc in hl:
                adj_r = hr + (1 if headers else 0)
                if r == adj_r and c == hc:
                    m.set_color(SEQ_HIGHLIGHT)
            x = (c - len(row) / 2 + 0.5) * cell_w
            y = -r * cell_h
            m.move_to([x, y, 0])
            bg = Rectangle(width=cell_w - 0.05, height=cell_h - 0.05,
                           fill_color=TABLE_HEADER if (r == 0 and headers) else TABLE_CELL,
                           fill_opacity=0.4, stroke_color=GREY_D, stroke_width=1)
            bg.move_to(m.get_center())
            group.add(bg, m)
    group.scale(0.8)
    return group


DIAGRAM_BUILDERS = {
    "number_line_cut": _build_number_line_cut,
    "set_containment": _build_set_containment,
    "sequence_list":   _build_sequence_list,
    "table":           _build_table,
}


# ═══════════════════════════════════════════════════════════════════
#  GRAPH BUILDERS (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_graph(cfg: dict) -> VGroup:
    """
    Function graphing with axes.
    cfg keys:
        kind: "function_plot" | "tangent_line" | "area_under" | "between_curves"
        x_range: [min, max, step]
        y_range: [min, max, step]
        functions: [{expr, color, label, dashed}]
        points: [{x, y, label, color}]
        shaded_area: {func_index, x_range, color, opacity}
        show_grid: bool
        axis_labels: [x_label, y_label]
    """
    kind       = cfg.get("kind", "function_plot")
    x_range    = cfg.get("x_range", [-5, 5, 1])
    y_range    = cfg.get("y_range", [-5, 5, 1])
    functions  = cfg.get("functions", [])
    points     = cfg.get("points", [])
    shaded     = cfg.get("shaded_area", None)
    show_grid  = cfg.get("show_grid", False)
    axis_labels = cfg.get("axis_labels", ["x", "y"])

    if show_grid:
        plane = NumberPlane(
            x_range=x_range, y_range=y_range,
            x_length=8, y_length=5,
            background_line_style={"stroke_color": GREY_D, "stroke_opacity": 0.4},
        )
        axes = plane
    else:
        axes = Axes(
            x_range=x_range, y_range=y_range,
            x_length=8, y_length=5,
            axis_config={"color": WHITE, "include_numbers": True, "font_size": 20},
        )

    group = VGroup(axes)

    # Axis labels
    if axis_labels:
        x_lbl = axes.get_x_axis_label(axis_labels[0], direction=RIGHT)
        y_lbl = axes.get_y_axis_label(axis_labels[1], direction=UP)
        group.add(x_lbl, y_lbl)

    # Plot functions
    # NOTE: expr strings are eval'd here. Input is controlled by our pipeline,
    # but this should be sandboxed if we ever accept user-provided expressions.
    default_colors = [ORBITAL_VIOLET, ORBITAL_CYAN, GRAPH_ORANGE, GRAPH_PINK, NEON_GREEN]
    plotted_funcs = []
    for i, fn in enumerate(functions):
        expr_str = fn.get("expr", "lambda x: x")
        color    = fn.get("color", default_colors[i % len(default_colors)])
        label    = fn.get("label", "")
        dashed   = fn.get("dashed", False)
        fn_obj   = eval(expr_str)  # Security: controlled input only

        if dashed:
            graph = DashedVMobject(axes.plot(fn_obj, color=color), num_dashes=40)
        else:
            graph = axes.plot(fn_obj, color=color)
        plotted_funcs.append((graph, fn_obj))
        group.add(graph)

        if label:
            lbl = MathTex(label, color=color, font_size=28)
            lbl.next_to(graph, UR, buff=0.15)
            group.add(lbl)

    # Shaded area — supports both "area_under" (single curve to x-axis)
    # and "between_curves" (shades between two functions)
    if shaded and plotted_funcs:
        fi = shaded.get("func_index", 0)
        fi2 = shaded.get("func_index_2", None)  # second function for between_curves
        sr = shaded.get("x_range", [x_range[0], x_range[1]])
        sc = shaded.get("color", NEON_GREEN)
        so = shaded.get("opacity", 0.3)
        if fi < len(plotted_funcs):
            fn_obj = plotted_funcs[fi][1]
            top_graph = axes.plot(fn_obj, color=sc)
            if fi2 is not None and fi2 < len(plotted_funcs):
                # Between curves: shade between func_index (top) and func_index_2 (bottom)
                fn_obj2 = plotted_funcs[fi2][1]
                bottom_graph = axes.plot(fn_obj2, color=sc)
                area = axes.get_area(
                    top_graph,
                    x_range=sr, color=sc, opacity=so,
                    bounded_graph=bottom_graph,
                )
            else:
                # Area under single curve to x-axis (original behavior)
                area = axes.get_area(
                    top_graph,
                    x_range=sr, color=sc, opacity=so,
                )
            group.add(area)

    # Points / dots
    for pt in points:
        px, py = pt.get("x", 0), pt.get("y", 0)
        pc = pt.get("color", CUT_POINT)
        pl = pt.get("label", "")
        dot = Dot(axes.c2p(px, py), color=pc, radius=0.08)
        group.add(dot)
        if pl:
            plbl = MathTex(pl, color=pc, font_size=24)
            plbl.next_to(dot, UR, buff=0.12)
            group.add(plbl)

    group.scale(0.75)
    return group


# ═══════════════════════════════════════════════════════════════════
#  TRANSFORM BUILDER (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_transform_data(cfg: dict) -> dict:
    """
    Returns a dict with 'from_mob', 'to_mob', 'intermediates' for the scene
    to animate. We return data rather than a single VGroup because transforms
    need to be animated sequentially in construct().
    """
    return cfg  # Handled specially in the scene — see _animate_transform


# ═══════════════════════════════════════════════════════════════════
#  GEOMETRIC BUILDERS (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_geometric(cfg: dict) -> VGroup:
    """
    Geometric constructions.
    cfg keys:
        shapes: [{type, ...params}]
          - polygon: vertices, color, label, fill_opacity
          - circle: center, radius, color, fill_opacity
          - line: start, end, color, dashed
          - angle: vertex, ray1, ray2, label, radius, color
        labels: [{text, position, color}]
    """
    shapes = cfg.get("shapes", [])
    labels = cfg.get("labels", [])
    group = VGroup()

    for s in shapes:
        stype = s.get("type", "line")

        if stype == "polygon":
            verts = s.get("vertices", [[0,0], [2,0], [1,1.7]])
            color = s.get("color", ORBITAL_VIOLET)
            fill_op = s.get("fill_opacity", 0.15)
            poly = Polygon(*[np.array([v[0], v[1], 0]) for v in verts],
                           color=color, fill_opacity=fill_op, stroke_width=2)
            group.add(poly)
            lbl = s.get("label", "")
            if lbl:
                # Label each vertex
                for i, char in enumerate(lbl):
                    if i < len(verts):
                        v = verts[i]
                        # Push label away from centroid
                        cx = sum(vv[0] for vv in verts) / len(verts)
                        cy = sum(vv[1] for vv in verts) / len(verts)
                        dx = v[0] - cx
                        dy = v[1] - cy
                        norm = max((dx**2 + dy**2)**0.5, 0.01)
                        t = MathTex(char, color=color, font_size=28)
                        t.move_to([v[0] + dx/norm*0.4, v[1] + dy/norm*0.4, 0])
                        group.add(t)

        elif stype == "circle":
            cx, cy = s.get("center", [0, 0])
            r = s.get("radius", 1.5)
            color = s.get("color", ORBITAL_CYAN)
            fill_op = s.get("fill_opacity", 0.1)
            circ = Circle(radius=r, color=color, fill_opacity=fill_op, stroke_width=2)
            circ.move_to([cx, cy, 0])
            group.add(circ)

        elif stype == "line":
            st = s.get("start", [-3, 0])
            en = s.get("end", [3, 0])
            color = s.get("color", WHITE)
            dashed = s.get("dashed", False)
            if dashed:
                ln = DashedLine([st[0], st[1], 0], [en[0], en[1], 0],
                                color=color, stroke_width=2)
            else:
                ln = Line([st[0], st[1], 0], [en[0], en[1], 0],
                          color=color, stroke_width=2)
            group.add(ln)

        elif stype == "angle":
            vertex = s.get("vertex", [0, 0])
            ray1   = s.get("ray1", [2, 0])
            ray2   = s.get("ray2", [1, 1.7])
            label  = s.get("label", "")
            radius = s.get("radius", 0.6)
            color  = s.get("color", GEOM_TEAL)

            v = np.array([vertex[0], vertex[1], 0])
            r1 = np.array([ray1[0], ray1[1], 0])
            r2 = np.array([ray2[0], ray2[1], 0])

            l1 = Line(v, r1, color=WHITE, stroke_width=2)
            l2 = Line(v, r2, color=WHITE, stroke_width=2)
            group.add(l1, l2)

            angle = Angle(l1, l2, radius=radius, color=color)
            group.add(angle)

            if label:
                mid_angle = (angle.get_start() + angle.get_end()) / 2
                direction = mid_angle - v
                norm = max(np.linalg.norm(direction), 0.01)
                lbl = MathTex(label, color=color, font_size=28)
                lbl.move_to(v + direction / norm * (radius + 0.35))
                group.add(lbl)

    # Extra labels
    for lb in labels:
        txt = lb.get("text", "")
        pos = lb.get("position", [0, 0])
        col = lb.get("color", WHITE)
        t = MathTex(txt, color=col, font_size=28)
        t.move_to([pos[0], pos[1], 0])
        group.add(t)

    group.scale(0.85)
    return group


# ═══════════════════════════════════════════════════════════════════
#  3D BUILDERS (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_threed_data(cfg: dict) -> dict:
    """
    Returns config for 3D scene rendering. Handled in construct() because
    ThreeDScene needs camera manipulation.
    """
    return cfg  # Handled in scene construct()


# ═══════════════════════════════════════════════════════════════════
#  MOBJECT FACTORY
# ═══════════════════════════════════════════════════════════════════

def _make_mobject(step: dict):
    """Create the correct Manim object for a step type."""
    stype   = step.get("type", "math")
    content = step.get("content") or step.get("latex", "")
    label   = step.get("label", "")

    if stype == "math":
        mob = MathTex(content, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "text":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "mixed":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "box":
        inner = MathTex(content, color=WHITE)
        inner.scale(0.85)
        lbl = Tex(r"\textbf{" + label + "}", color=LABEL_COLOR)
        lbl.scale(0.7)
        box_rect = SurroundingRectangle(
            inner, color=BOX_BORDER, fill_color=BOX_FILL,
            fill_opacity=0.6, buff=0.35, corner_radius=0.12, stroke_width=2,
        )
        lbl.next_to(box_rect, UP, buff=0.15).align_to(box_rect, LEFT).shift(RIGHT * 0.2)
        return VGroup(box_rect, lbl, inner)

    if stype == "diagram":
        diagram_cfg = step.get("diagram", {})
        kind = diagram_cfg.get("kind", "number_line_cut")
        builder = DIAGRAM_BUILDERS.get(kind)
        if builder:
            return builder(diagram_cfg)
        return Text(f"[diagram: {kind}]", color=GREY, font_size=28)

    if stype == "graph":
        graph_cfg = step.get("graph", {})
        return _build_graph(graph_cfg)

    if stype == "geometric":
        geom_cfg = step.get("geometric", {})
        return _build_geometric(geom_cfg)

    # "transform" and "threed" are handled specially in construct()
    # but we provide a fallback static mob for safety
    if stype == "transform":
        from_latex = step.get("transform", {}).get("from_latex", content)
        mob = MathTex(from_latex, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "threed":
        mob = Text("[3D scene]", color=GREY, font_size=28)
        return mob

    # fallback
    mob = MathTex(content, color=WHITE)
    mob.scale(1.4)
    return mob


# ═══════════════════════════════════════════════════════════════════
#  SCENE
# ═══════════════════════════════════════════════════════════════════

class SyncedProofScene(Scene):
    def construct(self):
        self.camera.background_color = "#000000"

        wm = Text(WATERMARK_TEXT, font_size=14, color=WHITE).set_opacity(0.35)
        wm.to_corner(DR, buff=0.3)
        self.add(wm)

        steps = [
        {
                "step": 0,
                "narration": "Alright, team. Let's tackle a classic area between curves problem. We need the area of the region trapped between a straight line and a parabola. The key here is figuring out where they cross and which one is on top.",
                "latex": "",
                "content": "Find the area enclosed by the line $y = x + 2$ and the parabola $y = x^2$.",
                "type": "text",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_00.mp3",
                "duration": 13.7
        },
        {
                "step": 1,
                "narration": "First, let's visualize the setup. I'll plot both functions so we can see the region we're after. The line has a slope of 1 and a y-intercept at 2. The parabola is our standard x squared, opening upwards.",
                "latex": "",
                "content": "",
                "type": "graph",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_01.mp3",
                "duration": 13.1
        },
        {
                "step": 2,
                "narration": "To find the boundaries of our region, we need the x-coordinates where the two graphs intersect. We set the equations equal to each other.",
                "latex": "",
                "content": "x+2 = x^2",
                "type": "math",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_02.mp3",
                "duration": 7.57
        },
        {
                "step": 3,
                "narration": "Now, let's solve for x. We'll move all terms to one side to get a quadratic equation.",
                "latex": "",
                "content": "",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_03.mp3",
                "duration": 5.67
        },
        {
                "step": 4,
                "narration": "This factors nicely. We're looking for two numbers that multiply to -2 and add to -1. That's -2 and +1.",
                "latex": "",
                "content": "",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_04.mp3",
                "duration": 8.13
        },
        {
                "step": 5,
                "narration": "So our intersection points are at x equals negative one and x equals two. Plugging into either equation, the intersection points are negative 1 comma 1, and 2 comma 4. For the area calculation, the x-values give us our left and right boundaries.",
                "latex": "",
                "content": "x = 2 \\quad \\text{or} \\quad x = -1",
                "type": "math",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_05.mp3",
                "duration": 15.6
        },
        {
                "step": 6,
                "narration": "Crucial step: which curve forms the 'ceiling' of our region? We need to know what to subtract from what. Let's check a point inside our interval, say x equals zero.",
                "latex": "",
                "content": "On the interval $[-1, 2]$, which function is on top? Let's test a point, like $x=0$.",
                "type": "text",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_06.mp3",
                "duration": 10.4
        },
        {
                "step": 7,
                "narration": "For the line, we get 2. For the parabola, we get 0. So on this interval, the line $y=x+2$ is above the parabola $y=x^2$. The line is the top function.",
                "latex": "",
                "content": "\\text{At } x=0: \\quad y = 0+2 = 2 \\quad \\text{and} \\quad y = 0^2 = 0.",
                "type": "math",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_07.mp3",
                "duration": 13.98
        },
        {
                "step": 8,
                "narration": "Here's the core formula. The area is the integral from the left intersection to the right intersection of (top function minus bottom function). Always subtract the lower curve from the upper one.",
                "latex": "",
                "content": "\\text{Area Between Curves} = \\int_{a}^{b} [\\text{Top}(x) - \\text{Bottom}(x)] \\, dx",
                "type": "box",
                "mode": "replace",
                "label": "Area Formula",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_08.mp3",
                "duration": 12.45
        },
        {
                "step": 9,
                "narration": "Now we plug in our specifics. Our limits are from -1 to 2. Our top function is (x+2), our bottom function is x^2. So the integrand is (x+2) minus (x^2).",
                "latex": "",
                "content": "A = \\int_{-1}^{2} \\left[ (x+2) - (x^2) \\right] \\, dx",
                "type": "math",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_09.mp3",
                "duration": 13.0
        },
        {
                "step": 10,
                "narration": "Let's simplify the expression inside the integral before we integrate. Combine like terms.",
                "latex": "",
                "content": "",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_10.mp3",
                "duration": 5.67
        },
        {
                "step": 11,
                "narration": "Time to find the antiderivative. We'll integrate term by term. Remember the power rule: increase the exponent by one and divide by the new exponent.",
                "latex": "",
                "content": "",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_11.mp3",
                "duration": 10.73
        },
        {
                "step": 12,
                "narration": "Now we evaluate at the upper limit x equals 2, then subtract the value at x equals negative one. Watch the signs carefully \u2014 this is where most mistakes happen.",
                "latex": "",
                "content": "",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_12.mp3",
                "duration": 11.8
        },
        {
                "step": 13,
                "narration": "Careful with the signs! For F of 2, combine the constants 2 and 4 to get 6. For F of negative 1, the signs are already simplified \u2014 we have one-third plus one-half minus 2.",
                "latex": "",
                "content": "",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_13.mp3",
                "duration": 12.59
        },
        {
                "step": 14,
                "narration": "Let's write 6 as 18 over 3 for the first part. For the second part, get a common denominator of 6 to combine those fractions.",
                "latex": "",
                "content": "",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_14.mp3",
                "duration": 8.03
        },
        {
                "step": 15,
                "narration": "Simplify the numerators. First part becomes 10/3. Second part inside becomes (2+3-12)/6 = -7/6.",
                "latex": "",
                "content": "",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_15.mp3",
                "duration": 12.26
        },
        {
                "step": 16,
                "narration": "Subtracting a negative is adding a positive. So we have 10/3 plus 7/6. Let's get a common denominator of 6.",
                "latex": "",
                "content": "",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_16.mp3",
                "duration": 9.38
        },
        {
                "step": 17,
                "narration": "Add the numerators: 20 plus 7 is 27 over 6. This simplifies to 9 halves.",
                "latex": "",
                "content": "A = \\frac{27}{6} = \\frac{9}{2}",
                "type": "math",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_17.mp3",
                "duration": 7.2
        },
        {
                "step": 18,
                "narration": "And there's our answer. The area of the region enclosed by the line and the parabola is nine-halves, or four and a half, square units.",
                "latex": "",
                "content": "\\text{Area} = \\frac{9}{2} \\text{ square units}",
                "type": "box",
                "mode": "replace",
                "label": "Answer",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_18.mp3",
                "duration": 8.68
        },
        {
                "step": 19,
                "narration": "One important takeaway: the area between curves is always positive. If you ever get a negative answer, that's a red flag \u2014 it means you probably subtracted in the wrong order. Always make sure it's top function minus bottom function.",
                "latex": "",
                "content": "Remember: the area between curves is always positive. If you get a negative number, check that you subtracted in the right order \u2014 top minus bottom.",
                "type": "text",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_19.mp3",
                "duration": 15.14
        },
        {
                "step": 20,
                "narration": "Let's look at the final picture. The shaded region between x equals -1 and 2, bounded above by the line and below by the parabola, has the area we just calculated.",
                "latex": "",
                "content": "",
                "type": "graph",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/area_between_curves_revised/audio/step_20.mp3",
                "duration": 10.68
        }
]

        build_lines = []
        previous_replace = None
        total = len(steps)

        for idx, step in enumerate(steps):
            duration   = step.get("duration", 2.0)
            audio_path = step.get("audio_path", "")
            mode       = step.get("mode", "replace")
            stype      = step.get("type", "math")

            if audio_path and os.path.exists(audio_path):
                self.add_sound(audio_path)

            anim_time = max(0.8, duration * ANIMATION_RATIO)

            # ── TRANSFORM (special animation) ────────────────────
            if stype == "transform":
                tcfg = step.get("transform", {})
                from_latex = tcfg.get("from_latex", "")
                to_latex   = tcfg.get("to_latex", "")
                intermediates = tcfg.get("intermediate_steps", [])
                highlights = tcfg.get("highlight_parts", [])

                # Clear previous
                if build_lines:
                    self.play(*[FadeOut(ln, shift=UP*0.3) for ln in build_lines], run_time=0.3)
                    build_lines.clear()
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP*0.3), run_time=0.35)

                # Show FROM expression
                from_mob = MathTex(from_latex, color=WHITE).scale(1.4)
                self.play(Write(from_mob), run_time=anim_time * 0.5)

                # Apply highlights
                for hl in highlights:
                    tex = hl.get("tex", "")
                    hcolor = hl.get("color", ORBITAL_VIOLET)
                    for part in from_mob:
                        for sub in part:
                            if hasattr(sub, 'get_tex_string') and tex in sub.get_tex_string():
                                sub.set_color(hcolor)

                # Build chain: from → intermediates → to
                chain = intermediates + [to_latex] if to_latex else intermediates
                current_mob = from_mob
                time_per_step = max(0.6, (duration - anim_time * 0.5) / max(len(chain), 1))

                for expr in chain:
                    next_mob = MathTex(expr, color=WHITE).scale(1.4)
                    self.play(TransformMatchingTex(current_mob, next_mob), run_time=time_per_step)
                    self.wait(0.3)
                    current_mob = next_mob

                previous_replace = current_mob
                remaining = max(0.1, duration - anim_time)
                self.wait(remaining)
                if idx < total - 1:
                    self.wait(EXTRA_HOLD)
                continue

            # ── THREED (special scene handling) ──────────────────
            if stype == "threed":
                tcfg = step.get("threed", {})
                kind = tcfg.get("kind", "surface")

                # Clear previous
                if build_lines:
                    self.play(*[FadeOut(ln, shift=UP*0.3) for ln in build_lines], run_time=0.3)
                    build_lines.clear()
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP*0.3), run_time=0.35)

                # Camera angle
                cam = tcfg.get("camera_angle", {"phi": 60, "theta": -45})
                phi = cam.get("phi", 60) * DEGREES
                theta = cam.get("theta", -45) * DEGREES
                self.set_camera_orientation(phi=phi, theta=theta)

                # 3D Axes
                if tcfg.get("axes", True):
                    axes_3d = ThreeDAxes(
                        x_range=tcfg.get("x_range", [-3, 3, 1]),
                        y_range=tcfg.get("y_range", [-3, 3, 1]),
                        z_range=tcfg.get("z_range", [-3, 3, 1]),
                    )
                    self.play(Create(axes_3d), run_time=anim_time * 0.4)

                if kind == "surface":
                    # Surface plot
                    # Security: eval controlled input only
                    func_str = tcfg.get("surface_func", "lambda u, v: np.array([u, v, u**2 + v**2])")
                    u_range = tcfg.get("u_range", [-2, 2])
                    v_range = tcfg.get("v_range", [-2, 2])
                    opacity = tcfg.get("opacity", 0.7)
                    colors = tcfg.get("color_gradient", [SURFACE_LOW, SURFACE_HIGH])

                    surf_func = eval(func_str)
                    surface = Surface(
                        surf_func,
                        u_range=u_range, v_range=v_range,
                        resolution=(32, 32),
                        fill_opacity=opacity,
                    )
                    surface.set_color_by_gradient(colors[0], colors[-1] if len(colors) > 1 else colors[0])
                    self.play(Create(surface), run_time=anim_time)
                    previous_replace = VGroup(axes_3d, surface) if tcfg.get("axes", True) else surface

                elif kind == "solid_of_revolution":
                    func_str = tcfg.get("curve_func", "lambda t: np.array([t, t**2, 0])")
                    t_range = tcfg.get("t_range", [0, 2])
                    opacity = tcfg.get("opacity", 0.6)
                    colors = tcfg.get("color_gradient", [SURFACE_LOW, SURFACE_HIGH])

                    curve_func = eval(func_str)
                    surface = Surface(
                        lambda u, v: np.array([
                            curve_func(u)[1] * np.cos(v),
                            curve_func(u)[1] * np.sin(v),
                            curve_func(u)[0],
                        ]),
                        u_range=t_range, v_range=[0, TAU],
                        resolution=(32, 32),
                        fill_opacity=opacity,
                    )
                    surface.set_color_by_gradient(colors[0], colors[-1] if len(colors) > 1 else colors[0])
                    self.play(Create(surface), run_time=anim_time)
                    previous_replace = VGroup(axes_3d, surface) if tcfg.get("axes", True) else surface

                elif kind == "coordinate_system":
                    # Just show the axes with labels
                    x_lbl = axes_3d.get_x_axis_label("x")
                    y_lbl = axes_3d.get_y_axis_label("y")
                    z_lbl = axes_3d.get_z_axis_label("z")
                    self.play(Write(x_lbl), Write(y_lbl), Write(z_lbl), run_time=0.5)
                    previous_replace = VGroup(axes_3d, x_lbl, y_lbl, z_lbl)

                else:
                    mob = Text(f"[3D: {kind}]", color=GREY, font_size=28)
                    self.play(FadeIn(mob), run_time=0.5)
                    previous_replace = mob

                remaining = max(0.2, duration - anim_time)
                self.wait(remaining)

                # Gentle camera rotation for visual interest
                if duration > 3:
                    self.begin_ambient_camera_rotation(rate=0.15)
                    self.wait(min(duration * 0.3, 2))
                    self.stop_ambient_camera_rotation()

                if idx < total - 1:
                    self.wait(EXTRA_HOLD)
                continue

            # ── STANDARD TYPES (text/math/mixed/box/diagram/graph/geometric) ─
            mob = _make_mobject(step)

            if mode == "build":
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace), run_time=0.3)
                    previous_replace = None

                build_lines.append(mob)
                if len(build_lines) > MAX_BUILD_LINES:
                    oldest = build_lines.pop(0)
                    self.play(FadeOut(oldest, shift=UP * 0.4), run_time=0.25)

                for i, ln in enumerate(build_lines):
                    target_y = TOP_Y - i * LINE_SPACING
                    ln.move_to([0, target_y, 0])

                mob.set_opacity(0)
                self.add(mob)
                self.play(mob.animate.set_opacity(1), run_time=anim_time)

            else:
                if build_lines:
                    self.play(*[FadeOut(ln, shift=UP * 0.3) for ln in build_lines], run_time=0.3)
                    build_lines.clear()

                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP * 0.3), run_time=0.35)

                mob.move_to(ORIGIN)
                if stype in ("box", "diagram", "graph", "geometric"):
                    self.play(FadeIn(mob, shift=UP * 0.3), run_time=anim_time)
                else:
                    self.play(Write(mob), run_time=anim_time)
                previous_replace = mob

            remaining = max(0.2, duration - anim_time - 0.35)
            self.wait(remaining)

            if idx < total - 1:
                self.wait(EXTRA_HOLD)

        # ── FINALE ──────────────────────────────────────────────
        final_mob = previous_replace or (build_lines[-1] if build_lines else None)
        if final_mob:
            box = SurroundingRectangle(
                final_mob, color=NEON_GREEN, buff=0.3,
                stroke_width=4, corner_radius=0.1,
            )
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)
            extras = [FadeOut(box)]
            if previous_replace:
                extras.append(FadeOut(previous_replace))
            for ln in build_lines:
                extras.append(FadeOut(ln))
            self.play(*extras, run_time=0.5)


if __name__ == "__main__":
    print("Render with:  manim -ql this_file.py SyncedProofScene")
