"""
Auto-generated Manim scene (v2) with proof/text/diagram support.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *
import json, os

# ── colours ──────────────────────────────────────────────────────
ORBITAL_VIOLET  = "#8B5CF6"
ORBITAL_CYAN    = "#22D3EE"
NEON_GREEN      = "#39FF14"
BOX_BORDER      = "#8B5CF6"
BOX_FILL        = "#1a1130"
LABEL_COLOR     = "#22D3EE"
CUT_LEFT        = "#4F46E5"   # indigo — left region of Dedekind cut
CUT_RIGHT       = "#F97316"   # orange — right region
CUT_POINT       = "#FACC15"   # yellow — cut point
SEQ_HIGHLIGHT   = "#F43F5E"   # rose — highlighted element in sequence
TABLE_HEADER    = "#8B5CF6"
TABLE_CELL      = "#1E1B4B"

# ── layout constants ─────────────────────────────────────────────
MAX_BUILD_LINES  = 5
TOP_Y            = 3.0
LINE_SPACING     = 0.85
EXTRA_HOLD       = 0.8
ANIMATION_RATIO  = 0.35
WATERMARK_TEXT    = "ORBITAL"


# ═══════════════════════════════════════════════════════════════════
#  DIAGRAM BUILDERS
# ═══════════════════════════════════════════════════════════════════

def _build_number_line_cut(cfg: dict) -> VGroup:
    """
    Number line with a Dedekind cut.
    cfg keys:
        x_range: [min, max, step]  (default [-3, 3, 1])
        cut_at:  float             (where the cut happens)
        left_label:  str           (label for left region, e.g. "A")
        right_label: str           (label for right region, e.g. "B")
        cut_label:   str           (label at the cut point, e.g. "\\sqrt{2}")
        show_point:  bool          (draw dot at cut point, default True)
    """
    x_range   = cfg.get("x_range", [-4, 4, 1])
    cut_at    = cfg.get("cut_at", 0)
    left_lbl  = cfg.get("left_label", "A")
    right_lbl = cfg.get("right_label", "B")
    cut_lbl   = cfg.get("cut_label", "")
    show_pt   = cfg.get("show_point", True)

    nl = NumberLine(
        x_range=x_range,
        length=10,
        include_numbers=True,
        include_tip=True,
        font_size=24,
        color=WHITE,
    )

    group = VGroup(nl)

    # Colored regions (translucent rectangles behind the line)
    left_start = nl.n2p(x_range[0])[0]
    cut_x      = nl.n2p(cut_at)[0]
    right_end  = nl.n2p(x_range[1])[0]
    line_y     = nl.get_center()[1]

    region_h = 0.5
    if cut_x - left_start > 0.1:
        left_rect = Rectangle(
            width=cut_x - left_start, height=region_h,
            fill_color=CUT_LEFT, fill_opacity=0.35,
            stroke_width=0,
        )
        left_rect.move_to([(left_start + cut_x) / 2, line_y, 0])
        group.add(left_rect)

        ll = MathTex(left_lbl, color=CUT_LEFT, font_size=36)
        ll.next_to(left_rect, UP, buff=0.3)
        group.add(ll)

    if right_end - cut_x > 0.1:
        right_rect = Rectangle(
            width=right_end - cut_x, height=region_h,
            fill_color=CUT_RIGHT, fill_opacity=0.35,
            stroke_width=0,
        )
        right_rect.move_to([(cut_x + right_end) / 2, line_y, 0])
        group.add(right_rect)

        rl = MathTex(right_lbl, color=CUT_RIGHT, font_size=36)
        rl.next_to(right_rect, UP, buff=0.3)
        group.add(rl)

    # Cut point
    if show_pt:
        dot = Dot(nl.n2p(cut_at), color=CUT_POINT, radius=0.1)
        group.add(dot)

    if cut_lbl:
        cl = MathTex(cut_lbl, color=CUT_POINT, font_size=36)
        cl.next_to(nl.n2p(cut_at), DOWN, buff=0.35)
        group.add(cl)

    # Dashed vertical line at cut
    dash = DashedLine(
        start=nl.n2p(cut_at) + UP * 0.8,
        end=nl.n2p(cut_at) + DOWN * 0.2,
        color=CUT_POINT, stroke_width=2,
    )
    group.add(dash)

    group.scale(0.75)
    return group


def _build_set_containment(cfg: dict) -> VGroup:
    """
    Nested or overlapping circles.
    cfg keys:
        sets: list of {label, radius, position, color}
        — position is [x, y] offset from center
    """
    sets = cfg.get("sets", [
        {"label": "A", "radius": 1.5, "position": [-0.5, 0], "color": "#4F46E5"},
        {"label": "B", "radius": 1.5, "position": [0.5, 0], "color": "#F97316"},
    ])

    group = VGroup()
    for s in sets:
        circ = Circle(
            radius=s.get("radius", 1.5),
            color=s.get("color", WHITE),
            fill_opacity=0.15,
            stroke_width=2,
        )
        pos = s.get("position", [0, 0])
        circ.move_to([pos[0], pos[1], 0])
        lbl = MathTex(s.get("label", ""), color=s.get("color", WHITE), font_size=36)
        lbl.move_to(circ.get_center() + UP * (s.get("radius", 1.5) + 0.3))
        group.add(circ, lbl)

    group.scale(0.8)
    return group


def _build_sequence_list(cfg: dict) -> VGroup:
    """
    Show a sequence like  r₁, r₂, r₃, ...  with optional highlighting.
    cfg keys:
        items:     list of str (LaTeX)  e.g. ["r_1", "r_2", "r_3", "\\dots"]
        highlight: list of int (indices to highlight)
        label:     str (optional label above)
    """
    items     = cfg.get("items", ["r_1", "r_2", "r_3", "\\dots"])
    highlight = cfg.get("highlight", [])
    label     = cfg.get("label", "")

    parts = []
    for i, item in enumerate(items):
        color = SEQ_HIGHLIGHT if i in highlight else WHITE
        m = MathTex(item, color=color, font_size=40)
        parts.append(m)
        if i < len(items) - 1:
            comma = MathTex(",", color=GREY, font_size=40)
            parts.append(comma)

    row = VGroup(*parts).arrange(RIGHT, buff=0.2)

    group = VGroup(row)
    if label:
        lbl = Tex(label, color=LABEL_COLOR, font_size=32)
        lbl.next_to(row, UP, buff=0.4)
        group.add(lbl)

    group.scale(0.85)
    return group


def _build_table(cfg: dict) -> VGroup:
    """
    Simple table/grid.
    cfg keys:
        headers: list of str
        rows:    list of list of str
        highlight_cells: list of [row, col] to highlight
    """
    headers = cfg.get("headers", [])
    rows    = cfg.get("rows", [])
    hl      = cfg.get("highlight_cells", [])

    all_rows = []
    if headers:
        all_rows.append(headers)
    all_rows.extend(rows)

    # Build as MathTable
    entries = []
    for r, row in enumerate(all_rows):
        row_entries = []
        for c, cell in enumerate(row):
            m = MathTex(cell, font_size=30)
            # Highlight header row
            if r == 0 and headers:
                m.set_color(LABEL_COLOR)
            # Highlight specific cells
            for hr, hc in hl:
                adj_r = hr + (1 if headers else 0)
                if r == adj_r and c == hc:
                    m.set_color(SEQ_HIGHLIGHT)
            row_entries.append(m)
        entries.append(row_entries)

    # Use VGroup grid layout
    group = VGroup()
    cell_w = 1.4
    cell_h = 0.6
    for r, row in enumerate(entries):
        for c, entry in enumerate(row):
            x = (c - len(row) / 2 + 0.5) * cell_w
            y = -r * cell_h
            entry.move_to([x, y, 0])
            bg = Rectangle(
                width=cell_w - 0.05, height=cell_h - 0.05,
                fill_color=TABLE_HEADER if (r == 0 and headers) else TABLE_CELL,
                fill_opacity=0.4,
                stroke_color=GREY_D, stroke_width=1,
            )
            bg.move_to(entry.get_center())
            group.add(bg, entry)

    group.scale(0.8)
    return group


DIAGRAM_BUILDERS = {
    "number_line_cut": _build_number_line_cut,
    "set_containment": _build_set_containment,
    "sequence_list":   _build_sequence_list,
    "table":           _build_table,
}


# ═══════════════════════════════════════════════════════════════════
#  MOBJECT FACTORY
# ═══════════════════════════════════════════════════════════════════

def _make_mobject(step: dict):
    """Create the correct Manim object for a step type."""
    stype   = step.get("type", "math")
    content = step.get("content") or step.get("latex", "")
    label   = step.get("label", "")

    if stype == "math":
        mob = MathTex(content, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "text":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "mixed":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "box":
        inner = Tex(content, color=WHITE)
        inner.scale(0.85)
        lbl = Tex(r"\textbf{" + label + "}", color=LABEL_COLOR)
        lbl.scale(0.7)

        box_rect = SurroundingRectangle(
            inner, color=BOX_BORDER, fill_color=BOX_FILL,
            fill_opacity=0.6, buff=0.35, corner_radius=0.12,
            stroke_width=2,
        )
        lbl.next_to(box_rect, UP, buff=0.15).align_to(box_rect, LEFT).shift(RIGHT * 0.2)
        group = VGroup(box_rect, lbl, inner)
        return group

    if stype == "diagram":
        diagram_cfg = step.get("diagram", {})
        kind = diagram_cfg.get("kind", "number_line_cut")
        builder = DIAGRAM_BUILDERS.get(kind)
        if builder:
            return builder(diagram_cfg)
        # fallback: show kind name
        return Text(f"[diagram: {kind}]", color=GREY, font_size=28)

    # fallback
    mob = MathTex(content, color=WHITE)
    mob.scale(1.4)
    return mob


# ═══════════════════════════════════════════════════════════════════
#  SCENE
# ═══════════════════════════════════════════════════════════════════

class SyncedProofScene(Scene):
    def construct(self):
        self.camera.background_color = "#000000"

        wm = Text(WATERMARK_TEXT, font_size=14, color=WHITE).set_opacity(0.35)
        wm.to_corner(DR, buff=0.3)
        self.add(wm)

        steps = [
        {
                "step": 0,
                "narration": "Let's prove that every group of order fifteen is cyclic. This is a special case of a beautiful pattern: whenever p and q are primes with p not dividing q minus one, every group of order p q is cyclic. Let's see why it works for fifteen.",
                "latex": "",
                "content": "Every group of order 15 is cyclic.",
                "type": "box",
                "mode": "replace",
                "label": "Theorem",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_00.mp3",
                "duration": 18.3
        },
        {
                "step": 1,
                "narration": "Let G be a group with order fifteen. Note that fifteen factors as three times five.",
                "latex": "",
                "content": "Let $G$ be a group with $|G| = 15 = 3 \\cdot 5$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_01.mp3",
                "duration": 6.13
        },
        {
                "step": 2,
                "narration": "By Cauchy's Theorem \u2014 which guarantees that prime divisors of the group order always show up as element orders \u2014",
                "latex": "",
                "content": "By Cauchy's Theorem, since 3 divides $|G|$,",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_02.mp3",
                "duration": 6.92
        },
        {
                "step": 3,
                "narration": "since three divides fifteen, there exists an element a in G of order three.",
                "latex": "",
                "content": "$\\exists\\, a \\in G$ with $\\text{ord}(a) = 3$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_03.mp3",
                "duration": 5.53
        },
        {
                "step": 4,
                "narration": "Similarly, since five divides fifteen,",
                "latex": "",
                "content": "Similarly, since 5 divides $|G|$,",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_04.mp3",
                "duration": 2.69
        },
        {
                "step": 5,
                "narration": "there exists an element b in G of order five.",
                "latex": "",
                "content": "$\\exists\\, b \\in G$ with $\\text{ord}(b) = 5$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_05.mp3",
                "duration": 3.3
        },
        {
                "step": 6,
                "narration": "Let H be the cyclic subgroup generated by a. Then H has order three.",
                "latex": "",
                "content": "Let $H = \\langle a \\rangle$, so $|H| = 3$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_06.mp3",
                "duration": 5.48
        },
        {
                "step": 7,
                "narration": "The index of H in G is fifteen over three, which equals five.",
                "latex": "",
                "content": "$[G : H] = \\frac{|G|}{|H|} = \\frac{15}{3} = 5$",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_07.mp3",
                "duration": 4.6
        },
        {
                "step": 8,
                "narration": "Now here's a key theorem from the theory of group actions: if the index of a subgroup equals the smallest prime dividing the order of G, then that subgroup must be normal. This is proved using the permutation representation on cosets \u2014 we'll take it as given.",
                "latex": "",
                "content": "If $[G : H]$ is the smallest prime dividing $|G|$, then $H \\trianglelefteq G$.",
                "type": "box",
                "mode": "build",
                "label": "Key Fact",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_08.mp3",
                "duration": 17.28
        },
        {
                "step": 9,
                "narration": "So let's try to use this. The smallest prime dividing fifteen is three, but the index of H is five. Five is not three \u2014 so our first attempt hits a wall! The theorem doesn't apply to H. But don't give up.",
                "latex": "",
                "content": "The smallest prime dividing $15$ is $3$, and $[G:H] = 5 > 3$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_09.mp3",
                "duration": 13.05
        },
        {
                "step": 10,
                "narration": "Instead, let K be the cyclic subgroup generated by b. Then K has order five, and the index of K in G is three.",
                "latex": "",
                "content": "Let $K = \\langle b \\rangle$, so $|K| = 5$ and $[G:K] = 3$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_10.mp3",
                "duration": 7.99
        },
        {
                "step": 11,
                "narration": "And three IS the smallest prime dividing fifteen.",
                "latex": "",
                "content": "$3$ is the smallest prime dividing $|G| = 15$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_11.mp3",
                "duration": 3.16
        },
        {
                "step": 12,
                "narration": "Therefore, K is a normal subgroup of G!",
                "latex": "",
                "content": "Therefore $K \\trianglelefteq G$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_12.mp3",
                "duration": 2.93
        },
        {
                "step": 13,
                "narration": "Now, since the orders of H and K are three and five, and gcd of three and five is one:",
                "latex": "",
                "content": "Since $|H| = 3$ and $|K| = 5$, and $\\gcd(3,5) = 1$:",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_13.mp3",
                "duration": 5.43
        },
        {
                "step": 14,
                "narration": "H and K intersect only at the identity. Any element in both would have order dividing three and five, hence order one.",
                "latex": "",
                "content": "H \\cap K = \\{e\\}",
                "type": "math",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_14.mp3",
                "duration": 8.22
        },
        {
                "step": 15,
                "narration": "By the product formula, the size of H K equals three times five over one, which is fifteen. That's the entire group.",
                "latex": "",
                "content": "|HK| = \\frac{|H| \\cdot |K|}{|H \\cap K|} = \\frac{3 \\cdot 5}{1} = 15 = |G|",
                "type": "math",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_15.mp3",
                "duration": 8.36
        },
        {
                "step": 16,
                "narration": "So G equals H K, with trivial intersection and K normal in G.",
                "latex": "",
                "content": "So $G = HK$ with $H \\cap K = \\{e\\}$ and $K \\trianglelefteq G$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_16.mp3",
                "duration": 5.16
        },
        {
                "step": 17,
                "narration": "Now here's the key move. Since K is normal in G, conjugation by elements of H defines a group homomorphism from H into the automorphism group of K.",
                "latex": "",
                "content": "Since $K \\trianglelefteq G$, conjugation gives a homomorphism $\\varphi: H \\to \\text{Aut}(K)$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_17.mp3",
                "duration": 11.29
        },
        {
                "step": 18,
                "narration": "K is cyclic of order five, so its automorphism group is cyclic of order four \u2014 since each of the four nonidentity elements can serve as the image of a generator.",
                "latex": "",
                "content": "$K \\cong \\mathbb{Z}/5\\mathbb{Z}$, so $\\text{Aut}(K) \\cong \\mathbb{Z}/4\\mathbb{Z}$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_18.mp3",
                "duration": 10.31
        },
        {
                "step": 19,
                "narration": "H has order three, and the automorphism group has order four. For a homomorphism from a group of order three into a group of order four, the image must have order dividing gcd of three and four \u2014 which is one.",
                "latex": "",
                "content": "$|H| = 3$ and $|\\text{Aut}(K)| = 4$. Since $\\gcd(3,4) = 1$:",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_19.mp3",
                "duration": 14.86
        },
        {
                "step": 20,
                "narration": "So the homomorphism is trivial. Conjugation by any element of H does nothing to K.",
                "latex": "",
                "content": "$\\varphi$ is trivial: $hkh^{-1} = k$ for all $h \\in H$, $k \\in K$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_20.mp3",
                "duration": 6.18
        },
        {
                "step": 21,
                "narration": "In other words, h k equals k h. Every element of H commutes with every element of K.",
                "latex": "",
                "content": "hk = kh \\quad \\forall\\, h \\in H,\\; k \\in K",
                "type": "math",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_21.mp3",
                "duration": 7.8
        },
        {
                "step": 22,
                "narration": "Notice this argument depends on three not dividing four. If we tried this with a group of order twenty-one, we'd have Aut of Z mod 7 with order six, and three DOES divide six \u2014 so the argument breaks. And indeed, non-abelian groups of order twenty-one exist.",
                "latex": "",
                "content": "(For order 21 = 3\u00b77, this fails: $3 \\mid |\\text{Aut}(\\mathbb{Z}/7\\mathbb{Z})| = 6$, and indeed non-abelian groups of order 21 exist.)",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_22.mp3",
                "duration": 17.65
        },
        {
                "step": 23,
                "narration": "Now consider the element a b. We've just shown that a and b commute, and their orders three and five are coprime.",
                "latex": "",
                "content": "Consider $ab \\in G$. Since $ab = ba$ and $\\gcd(3,5) = 1$:",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_23.mp3",
                "duration": 7.66
        },
        {
                "step": 24,
                "narration": "By a standard result: when two commuting elements have coprime orders, the order of their product equals the product of their orders.",
                "latex": "",
                "content": "If $xy = yx$ and $\\gcd(\\text{ord}(x), \\text{ord}(y)) = 1$, then $\\text{ord}(xy) = \\text{ord}(x) \\cdot \\text{ord}(y)$.",
                "type": "box",
                "mode": "build",
                "label": "Fact",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_24.mp3",
                "duration": 7.66
        },
        {
                "step": 25,
                "narration": "So the order of a b is three times five, which is fifteen.",
                "latex": "",
                "content": "\\text{ord}(ab) = \\text{ord}(a) \\cdot \\text{ord}(b) = 3 \\cdot 5 = 15",
                "type": "math",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_25.mp3",
                "duration": 3.85
        },
        {
                "step": 26,
                "narration": "So a b generates all of G, which means G is cyclic.",
                "latex": "",
                "content": "$\\langle ab \\rangle = G$, so $G$ is cyclic. $\\blacksquare$",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_26.mp3",
                "duration": 4.37
        },
        {
                "step": 27,
                "narration": "Let's recap. We used Cauchy's theorem to find elements of order three and five. The index-smallest-prime theorem told us the order-five subgroup K is normal. Then, since the automorphism group of K has order four and three doesn't divide four, conjugation by H must be trivial \u2014 so H and K commute. Finally, coprime orders gave us an element of order fifteen, making G cyclic. And that completes our proof.",
                "latex": "",
                "content": "Cauchy $\\to$ elements of order 3, 5 $\\to$ $K \\trianglelefteq G$ (index = smallest prime) $\\to$ $\\text{Aut}(K) \\cong \\mathbb{Z}/4\\mathbb{Z}$, $3 \\nmid 4$ $\\to$ $H$, $K$ commute $\\to$ $\\text{ord}(ab) = 15$ $\\to$ $G$ cyclic.",
                "type": "box",
                "mode": "replace",
                "label": "Recap",
                "diagram": {},
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/group_order_15_v2/audio/step_27.mp3",
                "duration": 27.91
        }
]

        build_lines = []
        previous_replace = None
        total = len(steps)

        for idx, step in enumerate(steps):
            duration   = step.get("duration", 2.0)
            audio_path = step.get("audio_path", "")
            mode       = step.get("mode", "replace")
            stype      = step.get("type", "math")

            if audio_path and os.path.exists(audio_path):
                self.add_sound(audio_path)

            anim_time = max(0.8, duration * ANIMATION_RATIO)
            mob = _make_mobject(step)

            if mode == "build":
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace), run_time=0.3)
                    previous_replace = None

                build_lines.append(mob)

                if len(build_lines) > MAX_BUILD_LINES:
                    oldest = build_lines.pop(0)
                    self.play(FadeOut(oldest, shift=UP * 0.4), run_time=0.25)

                for i, ln in enumerate(build_lines):
                    target_y = TOP_Y - i * LINE_SPACING
                    ln.move_to([0, target_y, 0])

                mob.set_opacity(0)
                self.add(mob)
                self.play(mob.animate.set_opacity(1), run_time=anim_time)

            else:
                if build_lines:
                    self.play(
                        *[FadeOut(ln, shift=UP * 0.3) for ln in build_lines],
                        run_time=0.3
                    )
                    build_lines.clear()

                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP * 0.3), run_time=0.35)

                mob.move_to(ORIGIN)
                if stype in ("box", "diagram"):
                    self.play(FadeIn(mob, shift=UP * 0.3), run_time=anim_time)
                else:
                    self.play(Write(mob), run_time=anim_time)
                previous_replace = mob

            remaining = max(0.2, duration - anim_time - 0.35)
            self.wait(remaining)

            if idx < total - 1:
                self.wait(EXTRA_HOLD)

        # finale
        final_mob = previous_replace or (build_lines[-1] if build_lines else None)
        if final_mob:
            box = SurroundingRectangle(
                final_mob, color=NEON_GREEN, buff=0.3,
                stroke_width=4, corner_radius=0.1,
            )
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)
            extras = [FadeOut(box)]
            if previous_replace:
                extras.append(FadeOut(previous_replace))
            for ln in build_lines:
                extras.append(FadeOut(ln))
            self.play(*extras, run_time=0.5)


if __name__ == "__main__":
    print("Render with:  manim -ql this_file.py SyncedProofScene")
