"""
Auto-generated Manim scene (v3) with full visual support.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *
import json, os, math

# ── colours ──────────────────────────────────────────────────────
ORBITAL_VIOLET  = "#8B5CF6"
ORBITAL_CYAN    = "#22D3EE"
NEON_GREEN      = "#39FF14"
BOX_BORDER      = "#8B5CF6"
BOX_FILL        = "#1a1130"
LABEL_COLOR     = "#22D3EE"
CUT_LEFT        = "#4F46E5"
CUT_RIGHT       = "#F97316"
CUT_POINT       = "#FACC15"
SEQ_HIGHLIGHT   = "#F43F5E"
TABLE_HEADER    = "#8B5CF6"
TABLE_CELL      = "#1E1B4B"
GRAPH_BLUE      = "#3B82F6"
GRAPH_ORANGE    = "#F97316"
GRAPH_PINK      = "#EC4899"
GEOM_TEAL       = "#14B8A6"
SURFACE_LOW     = "#4F46E5"
SURFACE_HIGH    = "#F97316"

# ── layout constants ─────────────────────────────────────────────
MAX_BUILD_LINES  = 5
TOP_Y            = 3.0
LINE_SPACING     = 0.85
EXTRA_HOLD       = 0.8
ANIMATION_RATIO  = 0.35
WATERMARK_TEXT    = "ORBITAL"


# ═══════════════════════════════════════════════════════════════════
#  DIAGRAM BUILDERS (v2 — unchanged)
# ═══════════════════════════════════════════════════════════════════

def _build_number_line_cut(cfg: dict) -> VGroup:
    x_range   = cfg.get("x_range", [-4, 4, 1])
    cut_at    = cfg.get("cut_at", 0)
    left_lbl  = cfg.get("left_label", "A")
    right_lbl = cfg.get("right_label", "B")
    cut_lbl   = cfg.get("cut_label", "")
    show_pt   = cfg.get("show_point", True)

    nl = NumberLine(x_range=x_range, length=10, include_numbers=True,
                    include_tip=True, font_size=24, color=WHITE)
    group = VGroup(nl)

    left_start = nl.n2p(x_range[0])[0]
    cut_x      = nl.n2p(cut_at)[0]
    right_end  = nl.n2p(x_range[1])[0]
    line_y     = nl.get_center()[1]
    region_h = 0.5

    if cut_x - left_start > 0.1:
        left_rect = Rectangle(width=cut_x - left_start, height=region_h,
                              fill_color=CUT_LEFT, fill_opacity=0.35, stroke_width=0)
        left_rect.move_to([(left_start + cut_x) / 2, line_y, 0])
        group.add(left_rect)
        ll = MathTex(left_lbl, color=CUT_LEFT, font_size=36)
        ll.next_to(left_rect, UP, buff=0.3)
        group.add(ll)

    if right_end - cut_x > 0.1:
        right_rect = Rectangle(width=right_end - cut_x, height=region_h,
                               fill_color=CUT_RIGHT, fill_opacity=0.35, stroke_width=0)
        right_rect.move_to([(cut_x + right_end) / 2, line_y, 0])
        group.add(right_rect)
        rl = MathTex(right_lbl, color=CUT_RIGHT, font_size=36)
        rl.next_to(right_rect, UP, buff=0.3)
        group.add(rl)

    if show_pt:
        dot = Dot(nl.n2p(cut_at), color=CUT_POINT, radius=0.1)
        group.add(dot)
    if cut_lbl:
        cl = MathTex(cut_lbl, color=CUT_POINT, font_size=36)
        cl.next_to(nl.n2p(cut_at), DOWN, buff=0.35)
        group.add(cl)

    dash = DashedLine(start=nl.n2p(cut_at) + UP * 0.8, end=nl.n2p(cut_at) + DOWN * 0.2,
                      color=CUT_POINT, stroke_width=2)
    group.add(dash)
    group.scale(0.75)
    return group


def _build_set_containment(cfg: dict) -> VGroup:
    sets = cfg.get("sets", [
        {"label": "A", "radius": 1.5, "position": [-0.5, 0], "color": "#4F46E5"},
        {"label": "B", "radius": 1.5, "position": [0.5, 0], "color": "#F97316"},
    ])
    group = VGroup()
    for s in sets:
        circ = Circle(radius=s.get("radius", 1.5), color=s.get("color", WHITE),
                      fill_opacity=0.15, stroke_width=2)
        pos = s.get("position", [0, 0])
        circ.move_to([pos[0], pos[1], 0])
        lbl = MathTex(s.get("label", ""), color=s.get("color", WHITE), font_size=36)
        lbl.move_to(circ.get_center() + UP * (s.get("radius", 1.5) + 0.3))
        group.add(circ, lbl)
    group.scale(0.8)
    return group


def _build_sequence_list(cfg: dict) -> VGroup:
    items     = cfg.get("items", ["r_1", "r_2", "r_3", "\\dots"])
    highlight = cfg.get("highlight", [])
    label     = cfg.get("label", "")
    parts = []
    for i, item in enumerate(items):
        color = SEQ_HIGHLIGHT if i in highlight else WHITE
        m = MathTex(item, color=color, font_size=40)
        parts.append(m)
        if i < len(items) - 1:
            comma = MathTex(",", color=GREY, font_size=40)
            parts.append(comma)
    row = VGroup(*parts).arrange(RIGHT, buff=0.2)
    group = VGroup(row)
    if label:
        lbl = Tex(label, color=LABEL_COLOR, font_size=32)
        lbl.next_to(row, UP, buff=0.4)
        group.add(lbl)
    group.scale(0.85)
    return group


def _build_table(cfg: dict) -> VGroup:
    headers = cfg.get("headers", [])
    rows    = cfg.get("rows", [])
    hl      = cfg.get("highlight_cells", [])
    all_rows = []
    if headers:
        all_rows.append(headers)
    all_rows.extend(rows)

    group = VGroup()
    cell_w = 1.4
    cell_h = 0.6
    for r, row in enumerate(all_rows):
        for c, cell in enumerate(row):
            m = MathTex(cell, font_size=30)
            if r == 0 and headers:
                m.set_color(LABEL_COLOR)
            for hr, hc in hl:
                adj_r = hr + (1 if headers else 0)
                if r == adj_r and c == hc:
                    m.set_color(SEQ_HIGHLIGHT)
            x = (c - len(row) / 2 + 0.5) * cell_w
            y = -r * cell_h
            m.move_to([x, y, 0])
            bg = Rectangle(width=cell_w - 0.05, height=cell_h - 0.05,
                           fill_color=TABLE_HEADER if (r == 0 and headers) else TABLE_CELL,
                           fill_opacity=0.4, stroke_color=GREY_D, stroke_width=1)
            bg.move_to(m.get_center())
            group.add(bg, m)
    group.scale(0.8)
    return group


DIAGRAM_BUILDERS = {
    "number_line_cut": _build_number_line_cut,
    "set_containment": _build_set_containment,
    "sequence_list":   _build_sequence_list,
    "table":           _build_table,
}


# ═══════════════════════════════════════════════════════════════════
#  GRAPH BUILDERS (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_graph(cfg: dict) -> VGroup:
    """
    Function graphing with axes.
    cfg keys:
        kind: "function_plot" | "tangent_line" | "area_under" | "between_curves"
        x_range: [min, max, step]
        y_range: [min, max, step]
        functions: [{expr, color, label, dashed}]
        points: [{x, y, label, color}]
        shaded_area: {func_index, x_range, color, opacity}
        show_grid: bool
        axis_labels: [x_label, y_label]
    """
    kind       = cfg.get("kind", "function_plot")
    x_range    = cfg.get("x_range", [-5, 5, 1])
    y_range    = cfg.get("y_range", [-5, 5, 1])
    functions  = cfg.get("functions", [])
    points     = cfg.get("points", [])
    shaded     = cfg.get("shaded_area", None)
    show_grid  = cfg.get("show_grid", False)
    axis_labels = cfg.get("axis_labels", ["x", "y"])

    if show_grid:
        plane = NumberPlane(
            x_range=x_range, y_range=y_range,
            x_length=8, y_length=5,
            background_line_style={"stroke_color": GREY_D, "stroke_opacity": 0.4},
        )
        axes = plane
    else:
        axes = Axes(
            x_range=x_range, y_range=y_range,
            x_length=8, y_length=5,
            axis_config={"color": WHITE, "include_numbers": True, "font_size": 20},
        )

    group = VGroup(axes)

    # Axis labels
    if axis_labels:
        x_lbl = axes.get_x_axis_label(axis_labels[0], direction=RIGHT)
        y_lbl = axes.get_y_axis_label(axis_labels[1], direction=UP)
        group.add(x_lbl, y_lbl)

    # Plot functions
    # NOTE: expr strings are eval'd here. Input is controlled by our pipeline,
    # but this should be sandboxed if we ever accept user-provided expressions.
    default_colors = [ORBITAL_VIOLET, ORBITAL_CYAN, GRAPH_ORANGE, GRAPH_PINK, NEON_GREEN]
    plotted_funcs = []
    for i, fn in enumerate(functions):
        expr_str = fn.get("expr", "lambda x: x")
        color    = fn.get("color", default_colors[i % len(default_colors)])
        label    = fn.get("label", "")
        dashed   = fn.get("dashed", False)
        fn_obj   = eval(expr_str)  # Security: controlled input only

        if dashed:
            graph = DashedVMobject(axes.plot(fn_obj, color=color), num_dashes=40)
        else:
            graph = axes.plot(fn_obj, color=color)
        plotted_funcs.append((graph, fn_obj))
        group.add(graph)

        if label:
            lbl = MathTex(label, color=color, font_size=28)
            lbl.next_to(graph, UR, buff=0.15)
            group.add(lbl)

    # Shaded area — supports both "area_under" (single curve to x-axis)
    # and "between_curves" (shades between two functions)
    if shaded and plotted_funcs:
        fi = shaded.get("func_index", 0)
        fi2 = shaded.get("func_index_2", None)  # second function for between_curves
        sr = shaded.get("x_range", [x_range[0], x_range[1]])
        sc = shaded.get("color", NEON_GREEN)
        so = shaded.get("opacity", 0.3)
        if fi < len(plotted_funcs):
            fn_obj = plotted_funcs[fi][1]
            top_graph = axes.plot(fn_obj, color=sc)
            if fi2 is not None and fi2 < len(plotted_funcs):
                # Between curves: shade between func_index (top) and func_index_2 (bottom)
                fn_obj2 = plotted_funcs[fi2][1]
                bottom_graph = axes.plot(fn_obj2, color=sc)
                area = axes.get_area(
                    top_graph,
                    x_range=sr, color=sc, opacity=so,
                    bounded_graph=bottom_graph,
                )
            else:
                # Area under single curve to x-axis (original behavior)
                area = axes.get_area(
                    top_graph,
                    x_range=sr, color=sc, opacity=so,
                )
            group.add(area)

    # Points / dots
    for pt in points:
        px, py = pt.get("x", 0), pt.get("y", 0)
        pc = pt.get("color", CUT_POINT)
        pl = pt.get("label", "")
        dot = Dot(axes.c2p(px, py), color=pc, radius=0.08)
        group.add(dot)
        if pl:
            plbl = MathTex(pl, color=pc, font_size=24)
            plbl.next_to(dot, UR, buff=0.12)
            group.add(plbl)

    group.scale(0.75)
    return group


# ═══════════════════════════════════════════════════════════════════
#  TRANSFORM BUILDER (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_transform_data(cfg: dict) -> dict:
    """
    Returns a dict with 'from_mob', 'to_mob', 'intermediates' for the scene
    to animate. We return data rather than a single VGroup because transforms
    need to be animated sequentially in construct().
    """
    return cfg  # Handled specially in the scene — see _animate_transform


# ═══════════════════════════════════════════════════════════════════
#  GEOMETRIC BUILDERS (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_geometric(cfg: dict) -> VGroup:
    """
    Geometric constructions.
    cfg keys:
        shapes: [{type, ...params}]
          - polygon: vertices, color, label, fill_opacity
          - circle: center, radius, color, fill_opacity
          - line: start, end, color, dashed
          - angle: vertex, ray1, ray2, label, radius, color
        labels: [{text, position, color}]
    """
    shapes = cfg.get("shapes", [])
    labels = cfg.get("labels", [])
    group = VGroup()

    for s in shapes:
        stype = s.get("type", "line")

        if stype == "polygon":
            verts = s.get("vertices", [[0,0], [2,0], [1,1.7]])
            color = s.get("color", ORBITAL_VIOLET)
            fill_op = s.get("fill_opacity", 0.15)
            poly = Polygon(*[np.array([v[0], v[1], 0]) for v in verts],
                           color=color, fill_opacity=fill_op, stroke_width=2)
            group.add(poly)
            lbl = s.get("label", "")
            if lbl:
                # Label each vertex
                for i, char in enumerate(lbl):
                    if i < len(verts):
                        v = verts[i]
                        # Push label away from centroid
                        cx = sum(vv[0] for vv in verts) / len(verts)
                        cy = sum(vv[1] for vv in verts) / len(verts)
                        dx = v[0] - cx
                        dy = v[1] - cy
                        norm = max((dx**2 + dy**2)**0.5, 0.01)
                        t = MathTex(char, color=color, font_size=28)
                        t.move_to([v[0] + dx/norm*0.4, v[1] + dy/norm*0.4, 0])
                        group.add(t)

        elif stype == "circle":
            cx, cy = s.get("center", [0, 0])
            r = s.get("radius", 1.5)
            color = s.get("color", ORBITAL_CYAN)
            fill_op = s.get("fill_opacity", 0.1)
            circ = Circle(radius=r, color=color, fill_opacity=fill_op, stroke_width=2)
            circ.move_to([cx, cy, 0])
            group.add(circ)

        elif stype == "line":
            st = s.get("start", [-3, 0])
            en = s.get("end", [3, 0])
            color = s.get("color", WHITE)
            dashed = s.get("dashed", False)
            if dashed:
                ln = DashedLine([st[0], st[1], 0], [en[0], en[1], 0],
                                color=color, stroke_width=2)
            else:
                ln = Line([st[0], st[1], 0], [en[0], en[1], 0],
                          color=color, stroke_width=2)
            group.add(ln)

        elif stype == "angle":
            vertex = s.get("vertex", [0, 0])
            ray1   = s.get("ray1", [2, 0])
            ray2   = s.get("ray2", [1, 1.7])
            label  = s.get("label", "")
            radius = s.get("radius", 0.6)
            color  = s.get("color", GEOM_TEAL)

            v = np.array([vertex[0], vertex[1], 0])
            r1 = np.array([ray1[0], ray1[1], 0])
            r2 = np.array([ray2[0], ray2[1], 0])

            l1 = Line(v, r1, color=WHITE, stroke_width=2)
            l2 = Line(v, r2, color=WHITE, stroke_width=2)
            group.add(l1, l2)

            angle = Angle(l1, l2, radius=radius, color=color)
            group.add(angle)

            if label:
                mid_angle = (angle.get_start() + angle.get_end()) / 2
                direction = mid_angle - v
                norm = max(np.linalg.norm(direction), 0.01)
                lbl = MathTex(label, color=color, font_size=28)
                lbl.move_to(v + direction / norm * (radius + 0.35))
                group.add(lbl)

    # Extra labels
    for lb in labels:
        txt = lb.get("text", "")
        pos = lb.get("position", [0, 0])
        col = lb.get("color", WHITE)
        t = MathTex(txt, color=col, font_size=28)
        t.move_to([pos[0], pos[1], 0])
        group.add(t)

    group.scale(0.85)
    return group


# ═══════════════════════════════════════════════════════════════════
#  3D BUILDERS (v3)
# ═══════════════════════════════════════════════════════════════════

def _build_threed_data(cfg: dict) -> dict:
    """
    Returns config for 3D scene rendering. Handled in construct() because
    ThreeDScene needs camera manipulation.
    """
    return cfg  # Handled in scene construct()


# ═══════════════════════════════════════════════════════════════════
#  MOBJECT FACTORY
# ═══════════════════════════════════════════════════════════════════

def _make_mobject(step: dict):
    """Create the correct Manim object for a step type."""
    stype   = step.get("type", "math")
    content = step.get("content") or step.get("latex", "")
    label   = step.get("label", "")

    if stype == "math":
        mob = MathTex(content, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "text":
        mob = Text(content, color=WHITE, font_size=32)
        mob.scale(0.9)
        return mob

    if stype == "mixed":
        # Wrap in math mode if no $ present
        if "$" not in content:
            content = "$" + content + "$"
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "box":
        inner = MathTex(content, color=WHITE)
        inner.scale(0.85)
        box_rect = SurroundingRectangle(
            inner, color=BOX_BORDER, fill_color=BOX_FILL,
            fill_opacity=0.6, buff=0.35, corner_radius=0.12, stroke_width=2,
        )
        if label:
            lbl = Tex(r"\textbf{" + label + "}", color=LABEL_COLOR)
            lbl.scale(0.7)
            lbl.next_to(box_rect, UP, buff=0.15).align_to(box_rect, LEFT).shift(RIGHT * 0.2)
            return VGroup(box_rect, lbl, inner)
        return VGroup(box_rect, inner)

    if stype == "diagram":
        diagram_cfg = step.get("diagram", {})
        kind = diagram_cfg.get("kind", "number_line_cut")
        builder = DIAGRAM_BUILDERS.get(kind)
        if builder:
            return builder(diagram_cfg)
        return Text(f"[diagram: {kind}]", color=GREY, font_size=28)

    if stype == "graph":
        graph_cfg = step.get("graph", {})
        return _build_graph(graph_cfg)

    if stype == "geometric":
        geom_cfg = step.get("geometric", {})
        return _build_geometric(geom_cfg)

    # "transform" and "threed" are handled specially in construct()
    # but we provide a fallback static mob for safety
    if stype == "transform":
        from_latex = step.get("transform", {}).get("from_latex", content)
        mob = MathTex(from_latex, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "threed":
        mob = Text("[3D scene]", color=GREY, font_size=28)
        return mob

    # fallback
    mob = MathTex(content, color=WHITE)
    mob.scale(1.4)
    return mob


# ═══════════════════════════════════════════════════════════════════
#  SCENE
# ═══════════════════════════════════════════════════════════════════

class SyncedProofScene(Scene):
    def construct(self):
        self.camera.background_color = "#000000"

        wm = Text(WATERMARK_TEXT, font_size=14, color=WHITE).set_opacity(0.35)
        wm.to_corner(DR, buff=0.3)
        self.add(wm)

        steps = [
        {
                "step": 0,
                "narration": "Let's find the derivative of f(x) = 3x^2 + 2x - 5. Remember, the derivative tells us the rate of change of the function at any point x. We'll use the power rule, which is a fundamental tool for differentiation.",
                "latex": "Let's find the derivative of $\u0001$ = $\u0001$ + 2x - 5. Remember, the derivative tells us the rate of change of the function at any point x. We'll use the power rule, which is a fundamental tool for differentiation.",
                "content": "Let's find the derivative of $\u0001$ = $\u0001$ + 2x - 5. Remember, the derivative tells us the rate of change of the function at any point x. We'll use the power rule, which is a fundamental tool for differentiation.",
                "type": "text",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "transform": {},
                "audio_path": "",
                "duration": 17.0
        },
        {
                "step": 1,
                "narration": "First, write down the function clearly: f(x) = 3x^2 + 2x - 5. Notice it's a polynomial with three terms. We'll differentiate each term separately because the derivative of a sum is the sum of the derivatives.",
                "latex": "f(x) = 3x^2 + 2x - 5",
                "content": "f(x) = 3x^2 + 2x - 5",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "transform": {},
                "audio_path": "",
                "duration": 15.8
        },
        {
                "step": 2,
                "narration": "Apply the power rule to the first term, 3x^2. The power rule says: if you have x^n, its derivative is n * x^(n-1). Here, n = 2, so multiply by 2 and reduce the exponent by 1.",
                "latex": "\\frac{d}{dx}(3x^2) = 3 \\cdot 2x^{2-1} = 6x",
                "content": "\\frac{d}{dx}(3x^2) = 3 \\cdot 2x^{2-1} = 6x",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "transform": {},
                "audio_path": "",
                "duration": 15.8
        },
        {
                "step": 3,
                "narration": "Now, differentiate the second term, 2x. Think of this as 2x^1. Using the power rule with n = 1: multiply by 1 and reduce the exponent to 0, but x^0 = 1, so it simplifies to just 2.",
                "latex": "\\frac{d}{dx}(2x) = 2 \\cdot 1x^{1-1} = 2",
                "content": "\\frac{d}{dx}(2x) = 2 \\cdot 1x^{1-1} = 2",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "transform": {},
                "audio_path": "",
                "duration": 16.2
        },
        {
                "step": 4,
                "narration": "For the constant term -5, remember that the derivative of any constant is 0. This is because constants don't change, so their rate of change is zero. A common mistake is to forget this and include the constant in the derivative.",
                "latex": "\\frac{d}{dx}(-5) = 0",
                "content": "\\frac{d}{dx}(-5) = 0",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "transform": {},
                "audio_path": "",
                "duration": 17.4
        },
        {
                "step": 5,
                "narration": "Now, combine all the derivatives we found. Add the results from each term: 6x from the first term, 2 from the second, and 0 from the constant. This gives us the derivative f'(x).",
                "latex": "\\frac{d}{dx}(3x^2) + \\frac{d}{dx}(2x) + \\frac{d}{dx}(-5)",
                "content": "\\frac{d}{dx}(3x^2) + \\frac{d}{dx}(2x) + \\frac{d}{dx}(-5)",
                "type": "transform",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "transform": {
                        "from_latex": "\\frac{d}{dx}(3x^2) + \\frac{d}{dx}(2x) + \\frac{d}{dx}(-5)",
                        "to_latex": "f'(x) = 6x + 2 + 0"
                },
                "audio_path": "",
                "duration": 14.2
        },
        {
                "step": 6,
                "narration": "Simplify the expression by removing the zero. So, the derivative is f'(x) = 6x + 2. This is our final answer.",
                "latex": "f'(x) = 6x + 2",
                "content": "f'(x) = 6x + 2",
                "type": "box",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "transform": {},
                "audio_path": "",
                "duration": 9.4
        },
        {
                "step": 7,
                "narration": "Takeaway: To differentiate a polynomial like this, apply the power rule term by term. Remember: multiply by the exponent, reduce the exponent by 1, and derivatives of constants are zero. Practice this to avoid common errors like mishandling constants or exponents.",
                "latex": "Takeaway: To differentiate a polynomial like this, apply the power rule term by term. Remember: multiply by the exponent, reduce the exponent by 1, and derivatives of constants are zero. Practice this to avoid common errors like mishandling constants or exponents.",
                "content": "Takeaway: To differentiate a polynomial like this, apply the power rule term by term. Remember: multiply by the exponent, reduce the exponent by 1, and derivatives of constants are zero. Practice this to avoid common errors like mishandling constants or exponents.",
                "type": "text",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "transform": {},
                "audio_path": "",
                "duration": 17.4
        }
]

        build_lines = []
        previous_replace = None
        total = len(steps)

        for idx, step in enumerate(steps):
            duration   = step.get("duration", 2.0)
            audio_path = step.get("audio_path", "")
            mode       = step.get("mode", "replace")
            stype      = step.get("type", "math")

            if audio_path and os.path.exists(audio_path):
                self.add_sound(audio_path)

            anim_time = max(0.8, duration * ANIMATION_RATIO)

            # ── TRANSFORM (special animation) ────────────────────
            if stype == "transform":
                tcfg = step.get("transform", {})
                from_latex = tcfg.get("from_latex", "")
                to_latex   = tcfg.get("to_latex", "")
                intermediates = tcfg.get("intermediate_steps", [])
                highlights = tcfg.get("highlight_parts", [])

                # Clear previous
                if build_lines:
                    self.play(*[FadeOut(ln, shift=UP*0.3) for ln in build_lines], run_time=0.3)
                    build_lines.clear()
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP*0.3), run_time=0.35)

                # Show FROM expression
                from_mob = MathTex(from_latex, color=WHITE).scale(1.4)
                self.play(Write(from_mob), run_time=anim_time * 0.5)

                # Apply highlights
                for hl in highlights:
                    tex = hl.get("tex", "")
                    hcolor = hl.get("color", ORBITAL_VIOLET)
                    for part in from_mob:
                        for sub in part:
                            if hasattr(sub, 'get_tex_string') and tex in sub.get_tex_string():
                                sub.set_color(hcolor)

                # Build chain: from → intermediates → to
                chain = intermediates + [to_latex] if to_latex else intermediates
                current_mob = from_mob
                time_per_step = max(0.6, (duration - anim_time * 0.5) / max(len(chain), 1))

                for expr in chain:
                    next_mob = MathTex(expr, color=WHITE).scale(1.4)
                    self.play(TransformMatchingTex(current_mob, next_mob), run_time=time_per_step)
                    self.wait(0.3)
                    current_mob = next_mob

                previous_replace = current_mob
                remaining = max(0.1, duration - anim_time)
                self.wait(remaining)
                if idx < total - 1:
                    self.wait(EXTRA_HOLD)
                continue

            # ── THREED (special scene handling) ──────────────────
            if stype == "threed":
                tcfg = step.get("threed", {})
                kind = tcfg.get("kind", "surface")

                # Clear previous
                if build_lines:
                    self.play(*[FadeOut(ln, shift=UP*0.3) for ln in build_lines], run_time=0.3)
                    build_lines.clear()
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP*0.3), run_time=0.35)

                # Camera angle
                cam = tcfg.get("camera_angle", {"phi": 60, "theta": -45})
                phi = cam.get("phi", 60) * DEGREES
                theta = cam.get("theta", -45) * DEGREES
                self.set_camera_orientation(phi=phi, theta=theta)

                # 3D Axes
                if tcfg.get("axes", True):
                    axes_3d = ThreeDAxes(
                        x_range=tcfg.get("x_range", [-3, 3, 1]),
                        y_range=tcfg.get("y_range", [-3, 3, 1]),
                        z_range=tcfg.get("z_range", [-3, 3, 1]),
                    )
                    self.play(Create(axes_3d), run_time=anim_time * 0.4)

                if kind == "surface":
                    # Surface plot
                    # Security: eval controlled input only
                    func_str = tcfg.get("surface_func", "lambda u, v: np.array([u, v, u**2 + v**2])")
                    u_range = tcfg.get("u_range", [-2, 2])
                    v_range = tcfg.get("v_range", [-2, 2])
                    opacity = tcfg.get("opacity", 0.7)
                    colors = tcfg.get("color_gradient", [SURFACE_LOW, SURFACE_HIGH])

                    surf_func = eval(func_str)
                    surface = Surface(
                        surf_func,
                        u_range=u_range, v_range=v_range,
                        resolution=(32, 32),
                        fill_opacity=opacity,
                    )
                    surface.set_color_by_gradient(colors[0], colors[-1] if len(colors) > 1 else colors[0])
                    self.play(Create(surface), run_time=anim_time)
                    previous_replace = VGroup(axes_3d, surface) if tcfg.get("axes", True) else surface

                elif kind == "solid_of_revolution":
                    func_str = tcfg.get("curve_func", "lambda t: np.array([t, t**2, 0])")
                    t_range = tcfg.get("t_range", [0, 2])
                    opacity = tcfg.get("opacity", 0.6)
                    colors = tcfg.get("color_gradient", [SURFACE_LOW, SURFACE_HIGH])

                    curve_func = eval(func_str)
                    surface = Surface(
                        lambda u, v: np.array([
                            curve_func(u)[1] * np.cos(v),
                            curve_func(u)[1] * np.sin(v),
                            curve_func(u)[0],
                        ]),
                        u_range=t_range, v_range=[0, TAU],
                        resolution=(32, 32),
                        fill_opacity=opacity,
                    )
                    surface.set_color_by_gradient(colors[0], colors[-1] if len(colors) > 1 else colors[0])
                    self.play(Create(surface), run_time=anim_time)
                    previous_replace = VGroup(axes_3d, surface) if tcfg.get("axes", True) else surface

                elif kind == "coordinate_system":
                    # Just show the axes with labels
                    x_lbl = axes_3d.get_x_axis_label("x")
                    y_lbl = axes_3d.get_y_axis_label("y")
                    z_lbl = axes_3d.get_z_axis_label("z")
                    self.play(Write(x_lbl), Write(y_lbl), Write(z_lbl), run_time=0.5)
                    previous_replace = VGroup(axes_3d, x_lbl, y_lbl, z_lbl)

                else:
                    mob = Text(f"[3D: {kind}]", color=GREY, font_size=28)
                    self.play(FadeIn(mob), run_time=0.5)
                    previous_replace = mob

                remaining = max(0.2, duration - anim_time)
                self.wait(remaining)

                # Gentle camera rotation for visual interest
                if duration > 3:
                    self.begin_ambient_camera_rotation(rate=0.15)
                    self.wait(min(duration * 0.3, 2))
                    self.stop_ambient_camera_rotation()

                if idx < total - 1:
                    self.wait(EXTRA_HOLD)
                continue

            # ── STANDARD TYPES (text/math/mixed/box/diagram/graph/geometric) ─
            mob = _make_mobject(step)

            if mode == "build":
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace), run_time=0.3)
                    previous_replace = None

                build_lines.append(mob)
                if len(build_lines) > MAX_BUILD_LINES:
                    oldest = build_lines.pop(0)
                    self.play(FadeOut(oldest, shift=UP * 0.4), run_time=0.25)

                for i, ln in enumerate(build_lines):
                    target_y = TOP_Y - i * LINE_SPACING
                    ln.move_to([0, target_y, 0])

                mob.set_opacity(0)
                self.add(mob)
                self.play(mob.animate.set_opacity(1), run_time=anim_time)

            else:
                if build_lines:
                    self.play(*[FadeOut(ln, shift=UP * 0.3) for ln in build_lines], run_time=0.3)
                    build_lines.clear()

                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP * 0.3), run_time=0.35)

                mob.move_to(ORIGIN)
                if stype in ("box", "diagram", "graph", "geometric"):
                    self.play(FadeIn(mob, shift=UP * 0.3), run_time=anim_time)
                else:
                    self.play(Write(mob), run_time=anim_time)
                previous_replace = mob

            remaining = max(0.2, duration - anim_time - 0.35)
            self.wait(remaining)

            if idx < total - 1:
                self.wait(EXTRA_HOLD)

        # ── FINALE ──────────────────────────────────────────────
        final_mob = previous_replace or (build_lines[-1] if build_lines else None)
        if final_mob:
            box = SurroundingRectangle(
                final_mob, color=NEON_GREEN, buff=0.3,
                stroke_width=4, corner_radius=0.1,
            )
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)
            extras = [FadeOut(box)]
            if previous_replace:
                extras.append(FadeOut(previous_replace))
            for ln in build_lines:
                extras.append(FadeOut(ln))
            self.play(*extras, run_time=0.5)


if __name__ == "__main__":
    print("Render with:  manim -ql this_file.py SyncedProofScene")
