"""
Orbital Scene Generator v2 — Proof, Text & Diagram Support
============================================================
Step types:
  - "text"    → Tex (LaTeX text mode)
  - "math"    → MathTex (LaTeX math mode)  [default / backward compat]
  - "mixed"   → Tex with inline $...$ math
  - "box"     → labeled theorem/claim/key-fact box
  - "diagram" → visual diagrams (number_line_cut, set_containment, sequence_list, table)

Display modes:
  - "replace" → fade out previous, write new  [default]
  - "build"   → lines accumulate on screen (scroll when full)

Diagram sub-kinds (in step["diagram"]):
  - number_line_cut:  Number line split at a point with colored regions
  - set_containment:  Nested/overlapping circles (Venn-style)
  - sequence_list:    Show a sequence with ellipsis (for diagonal arguments)
  - table:            Rows/columns grid

Usage:
    from scene_v2 import create_synced_scene_v2
    create_synced_scene_v2(manifest, "scene.py", intro_duration=2.0)
"""

import json
import os


MAX_BUILD_LINES = 5
TOP_Y = 3.0
LINE_SPACING = 0.85


def create_synced_scene_v2(manifest: list, output_path: str, intro_duration: float = 2.0):
    """
    Write a Manim scene .py file that handles all step types.
    """

    manifest_json = json.dumps(manifest, indent=8)

    scene_code = '''"""
Auto-generated Manim scene (v2) with proof/text/diagram support.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *
import json, os

# ── colours ──────────────────────────────────────────────────────
ORBITAL_VIOLET  = "#8B5CF6"
ORBITAL_CYAN    = "#22D3EE"
NEON_GREEN      = "#39FF14"
BOX_BORDER      = "#8B5CF6"
BOX_FILL        = "#1a1130"
LABEL_COLOR     = "#22D3EE"
CUT_LEFT        = "#4F46E5"   # indigo — left region of Dedekind cut
CUT_RIGHT       = "#F97316"   # orange — right region
CUT_POINT       = "#FACC15"   # yellow — cut point
SEQ_HIGHLIGHT   = "#F43F5E"   # rose — highlighted element in sequence
TABLE_HEADER    = "#8B5CF6"
TABLE_CELL      = "#1E1B4B"

# ── layout constants ─────────────────────────────────────────────
MAX_BUILD_LINES  = ''' + str(MAX_BUILD_LINES) + '''
TOP_Y            = ''' + str(TOP_Y) + '''
LINE_SPACING     = ''' + str(LINE_SPACING) + '''
EXTRA_HOLD       = 0.8
ANIMATION_RATIO  = 0.35
WATERMARK_TEXT    = "ORBITAL"


# ═══════════════════════════════════════════════════════════════════
#  DIAGRAM BUILDERS
# ═══════════════════════════════════════════════════════════════════

def _build_number_line_cut(cfg: dict) -> VGroup:
    """
    Number line with a Dedekind cut.
    cfg keys:
        x_range: [min, max, step]  (default [-3, 3, 1])
        cut_at:  float             (where the cut happens)
        left_label:  str           (label for left region, e.g. "A")
        right_label: str           (label for right region, e.g. "B")
        cut_label:   str           (label at the cut point, e.g. "\\\\sqrt{2}")
        show_point:  bool          (draw dot at cut point, default True)
    """
    x_range   = cfg.get("x_range", [-4, 4, 1])
    cut_at    = cfg.get("cut_at", 0)
    left_lbl  = cfg.get("left_label", "A")
    right_lbl = cfg.get("right_label", "B")
    cut_lbl   = cfg.get("cut_label", "")
    show_pt   = cfg.get("show_point", True)

    nl = NumberLine(
        x_range=x_range,
        length=10,
        include_numbers=True,
        include_tip=True,
        font_size=24,
        color=WHITE,
    )

    group = VGroup(nl)

    # Colored regions (translucent rectangles behind the line)
    left_start = nl.n2p(x_range[0])[0]
    cut_x      = nl.n2p(cut_at)[0]
    right_end  = nl.n2p(x_range[1])[0]
    line_y     = nl.get_center()[1]

    region_h = 0.5
    if cut_x - left_start > 0.1:
        left_rect = Rectangle(
            width=cut_x - left_start, height=region_h,
            fill_color=CUT_LEFT, fill_opacity=0.35,
            stroke_width=0,
        )
        left_rect.move_to([(left_start + cut_x) / 2, line_y, 0])
        group.add(left_rect)

        ll = MathTex(left_lbl, color=CUT_LEFT, font_size=36)
        ll.next_to(left_rect, UP, buff=0.3)
        group.add(ll)

    if right_end - cut_x > 0.1:
        right_rect = Rectangle(
            width=right_end - cut_x, height=region_h,
            fill_color=CUT_RIGHT, fill_opacity=0.35,
            stroke_width=0,
        )
        right_rect.move_to([(cut_x + right_end) / 2, line_y, 0])
        group.add(right_rect)

        rl = MathTex(right_lbl, color=CUT_RIGHT, font_size=36)
        rl.next_to(right_rect, UP, buff=0.3)
        group.add(rl)

    # Cut point
    if show_pt:
        dot = Dot(nl.n2p(cut_at), color=CUT_POINT, radius=0.1)
        group.add(dot)

    if cut_lbl:
        cl = MathTex(cut_lbl, color=CUT_POINT, font_size=36)
        cl.next_to(nl.n2p(cut_at), DOWN, buff=0.35)
        group.add(cl)

    # Dashed vertical line at cut
    dash = DashedLine(
        start=nl.n2p(cut_at) + UP * 0.8,
        end=nl.n2p(cut_at) + DOWN * 0.2,
        color=CUT_POINT, stroke_width=2,
    )
    group.add(dash)

    group.scale(0.75)
    return group


def _build_set_containment(cfg: dict) -> VGroup:
    """
    Nested or overlapping circles.
    cfg keys:
        sets: list of {label, radius, position, color}
        — position is [x, y] offset from center
    """
    sets = cfg.get("sets", [
        {"label": "A", "radius": 1.5, "position": [-0.5, 0], "color": "#4F46E5"},
        {"label": "B", "radius": 1.5, "position": [0.5, 0], "color": "#F97316"},
    ])

    group = VGroup()
    for s in sets:
        circ = Circle(
            radius=s.get("radius", 1.5),
            color=s.get("color", WHITE),
            fill_opacity=0.15,
            stroke_width=2,
        )
        pos = s.get("position", [0, 0])
        circ.move_to([pos[0], pos[1], 0])
        lbl = MathTex(s.get("label", ""), color=s.get("color", WHITE), font_size=36)
        lbl.move_to(circ.get_center() + UP * (s.get("radius", 1.5) + 0.3))
        group.add(circ, lbl)

    group.scale(0.8)
    return group


def _build_sequence_list(cfg: dict) -> VGroup:
    """
    Show a sequence like  r₁, r₂, r₃, ...  with optional highlighting.
    cfg keys:
        items:     list of str (LaTeX)  e.g. ["r_1", "r_2", "r_3", "\\\\dots"]
        highlight: list of int (indices to highlight)
        label:     str (optional label above)
    """
    items     = cfg.get("items", ["r_1", "r_2", "r_3", "\\\\dots"])
    highlight = cfg.get("highlight", [])
    label     = cfg.get("label", "")

    parts = []
    for i, item in enumerate(items):
        color = SEQ_HIGHLIGHT if i in highlight else WHITE
        m = MathTex(item, color=color, font_size=40)
        parts.append(m)
        if i < len(items) - 1:
            comma = MathTex(",", color=GREY, font_size=40)
            parts.append(comma)

    row = VGroup(*parts).arrange(RIGHT, buff=0.2)

    group = VGroup(row)
    if label:
        lbl = Tex(label, color=LABEL_COLOR, font_size=32)
        lbl.next_to(row, UP, buff=0.4)
        group.add(lbl)

    group.scale(0.85)
    return group


def _build_table(cfg: dict) -> VGroup:
    """
    Simple table/grid.
    cfg keys:
        headers: list of str
        rows:    list of list of str
        highlight_cells: list of [row, col] to highlight
    """
    headers = cfg.get("headers", [])
    rows    = cfg.get("rows", [])
    hl      = cfg.get("highlight_cells", [])

    all_rows = []
    if headers:
        all_rows.append(headers)
    all_rows.extend(rows)

    # Build as MathTable
    entries = []
    for r, row in enumerate(all_rows):
        row_entries = []
        for c, cell in enumerate(row):
            m = MathTex(cell, font_size=30)
            # Highlight header row
            if r == 0 and headers:
                m.set_color(LABEL_COLOR)
            # Highlight specific cells
            for hr, hc in hl:
                adj_r = hr + (1 if headers else 0)
                if r == adj_r and c == hc:
                    m.set_color(SEQ_HIGHLIGHT)
            row_entries.append(m)
        entries.append(row_entries)

    # Use VGroup grid layout
    group = VGroup()
    cell_w = 1.4
    cell_h = 0.6
    for r, row in enumerate(entries):
        for c, entry in enumerate(row):
            x = (c - len(row) / 2 + 0.5) * cell_w
            y = -r * cell_h
            entry.move_to([x, y, 0])
            bg = Rectangle(
                width=cell_w - 0.05, height=cell_h - 0.05,
                fill_color=TABLE_HEADER if (r == 0 and headers) else TABLE_CELL,
                fill_opacity=0.4,
                stroke_color=GREY_D, stroke_width=1,
            )
            bg.move_to(entry.get_center())
            group.add(bg, entry)

    group.scale(0.8)
    return group


DIAGRAM_BUILDERS = {
    "number_line_cut": _build_number_line_cut,
    "set_containment": _build_set_containment,
    "sequence_list":   _build_sequence_list,
    "table":           _build_table,
}


# ═══════════════════════════════════════════════════════════════════
#  MOBJECT FACTORY
# ═══════════════════════════════════════════════════════════════════

def _make_mobject(step: dict):
    """Create the correct Manim object for a step type."""
    stype   = step.get("type", "math")
    content = step.get("content") or step.get("latex", "")
    label   = step.get("label", "")

    if stype == "math":
        mob = MathTex(content, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "text":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "mixed":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "box":
        inner = Tex(content, color=WHITE)
        inner.scale(0.85)
        lbl = Tex(r"\\textbf{" + label + "}", color=LABEL_COLOR)
        lbl.scale(0.7)

        box_rect = SurroundingRectangle(
            inner, color=BOX_BORDER, fill_color=BOX_FILL,
            fill_opacity=0.6, buff=0.35, corner_radius=0.12,
            stroke_width=2,
        )
        lbl.next_to(box_rect, UP, buff=0.15).align_to(box_rect, LEFT).shift(RIGHT * 0.2)
        group = VGroup(box_rect, lbl, inner)
        return group

    if stype == "diagram":
        diagram_cfg = step.get("diagram", {})
        kind = diagram_cfg.get("kind", "number_line_cut")
        builder = DIAGRAM_BUILDERS.get(kind)
        if builder:
            return builder(diagram_cfg)
        # fallback: show kind name
        return Text(f"[diagram: {kind}]", color=GREY, font_size=28)

    # fallback
    mob = MathTex(content, color=WHITE)
    mob.scale(1.4)
    return mob


# ═══════════════════════════════════════════════════════════════════
#  SCENE
# ═══════════════════════════════════════════════════════════════════

class SyncedProofScene(Scene):
    def construct(self):
        self.camera.background_color = "#000000"

        wm = Text(WATERMARK_TEXT, font_size=14, color=WHITE).set_opacity(0.35)
        wm.to_corner(DR, buff=0.3)
        self.add(wm)

        steps = MANIFEST_PLACEHOLDER

        build_lines = []
        previous_replace = None
        total = len(steps)

        for idx, step in enumerate(steps):
            duration   = step.get("duration", 2.0)
            audio_path = step.get("audio_path", "")
            mode       = step.get("mode", "replace")
            stype      = step.get("type", "math")

            if audio_path and os.path.exists(audio_path):
                self.add_sound(audio_path)

            anim_time = max(0.8, duration * ANIMATION_RATIO)
            mob = _make_mobject(step)

            if mode == "build":
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace), run_time=0.3)
                    previous_replace = None

                build_lines.append(mob)

                if len(build_lines) > MAX_BUILD_LINES:
                    oldest = build_lines.pop(0)
                    self.play(FadeOut(oldest, shift=UP * 0.4), run_time=0.25)

                for i, ln in enumerate(build_lines):
                    target_y = TOP_Y - i * LINE_SPACING
                    ln.move_to([0, target_y, 0])

                mob.set_opacity(0)
                self.add(mob)
                self.play(mob.animate.set_opacity(1), run_time=anim_time)

            else:
                if build_lines:
                    self.play(
                        *[FadeOut(ln, shift=UP * 0.3) for ln in build_lines],
                        run_time=0.3
                    )
                    build_lines.clear()

                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP * 0.3), run_time=0.35)

                mob.move_to(ORIGIN)
                if stype in ("box", "diagram"):
                    self.play(FadeIn(mob, shift=UP * 0.3), run_time=anim_time)
                else:
                    self.play(Write(mob), run_time=anim_time)
                previous_replace = mob

            remaining = max(0.2, duration - anim_time - 0.35)
            self.wait(remaining)

            if idx < total - 1:
                self.wait(EXTRA_HOLD)

        # finale
        final_mob = previous_replace or (build_lines[-1] if build_lines else None)
        if final_mob:
            box = SurroundingRectangle(
                final_mob, color=NEON_GREEN, buff=0.3,
                stroke_width=4, corner_radius=0.1,
            )
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)
            extras = [FadeOut(box)]
            if previous_replace:
                extras.append(FadeOut(previous_replace))
            for ln in build_lines:
                extras.append(FadeOut(ln))
            self.play(*extras, run_time=0.5)


if __name__ == "__main__":
    print("Render with:  manim -ql this_file.py SyncedProofScene")
'''

    # Inject the actual manifest data — fix JSON→Python booleans/null
    manifest_python = manifest_json.replace(": false", ": False").replace(": true", ": True").replace(": null", ": None")
    scene_code = scene_code.replace("MANIFEST_PLACEHOLDER", manifest_python)

    with open(output_path, "w") as f:
        f.write(scene_code)

    print(f"  ✓ Created v2 Manim scene: {output_path}")


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python scene_v2.py <script.json> [output.py]")
        sys.exit(1)

    with open(sys.argv[1]) as f:
        script = json.load(f)

    steps = script.get("steps", [])
    manifest = []
    for i, s in enumerate(steps):
        manifest.append({
            "step": i,
            "narration": s.get("narration", ""),
            "content": s.get("content", s.get("latex", "")),
            "latex": s.get("content", s.get("latex", "")),
            "type": s.get("type", "math"),
            "mode": s.get("mode", "replace"),
            "label": s.get("label", ""),
            "diagram": s.get("diagram", {}),
            "audio_path": "",
            "duration": 3.0,
        })

    out = sys.argv[2] if len(sys.argv) > 2 else "scene_v2_test.py"
    create_synced_scene_v2(manifest, out)
    print(f"Now run:  manim -ql {out} SyncedProofScene")
