"""
Orbital Scene Generator — Short-Form Vertical (9:16)
=====================================================
Wrapper around scene_v3.py that overrides layout constants
for 1080×1920 phone-first rendering.

Key differences from scene_v3:
- MAX_BUILD_LINES = 3  (less vertical space on phone)
- TOP_Y = 5.5          (tall canvas — 9:16 has way more vertical room)
- LINE_SPACING = 1.2   (more breathing room per line)
- Math equations scaled 2.2× (readable on a small phone screen)
- Font sizes bumped up across all step types
- Content centered in the middle band of the frame (avoid top/bottom crop zones)

Usage:
    from scene_short import create_synced_scene_short
    create_synced_scene_short(manifest, "scene.py", intro_duration=2.0)
"""

import json
import os


# ── Layout constants for 9:16 (1080×1920) ────────────────────────────────────
MAX_BUILD_LINES = 3        # Phone: fewer lines visible at once
TOP_Y           = 5.5      # Tall canvas — content starts higher
LINE_SPACING    = 1.2      # More spacing for readability
MATH_SCALE      = 2.2      # Bigger equations for phone screens
TEXT_FONT_SIZE  = 52       # Larger text throughout
BOX_FONT_SIZE   = 56       # Box labels bigger
LABEL_FONT_SIZE = 44       # Step labels
GRAPH_SCALE     = 0.85     # Graphs slightly smaller to fit width


def create_synced_scene_short(manifest: list, output_path: str, intro_duration: float = 2.0):
    """
    Write a Manim .py scene file optimised for 9:16 vertical format.
    Handles all step types from scene_v3 (math, text, mixed, box, graph, transform, etc.)
    but with adjusted layout constants for phone rendering.
    """

    has_3d = any(s.get("type") == "threed" for s in manifest)
    base_class = "ThreeDScene" if has_3d else "Scene"

    # Convert audio paths to absolute
    for step in manifest:
        ap = step.get("audio_path", "")
        if ap and not os.path.isabs(ap):
            step["audio_path"] = os.path.abspath(ap)
    manifest_json = json.dumps(manifest, indent=8)

    scene_code = f'''"""
Auto-generated Manim scene (short-form 9:16) with audio sync.
Generated by Orbital VideoFactory — Short-Form Pipeline.
"""

from manim import *
import json, os, math

# ── brand colours ─────────────────────────────────────────────────
ORBITAL_VIOLET  = "#8B5CF6"
ORBITAL_CYAN    = "#22D3EE"
NEON_GREEN      = "#39FF14"
BOX_BORDER      = "#8B5CF6"
BOX_FILL        = "#1a1130"
LABEL_COLOR     = "#22D3EE"
CUT_LEFT        = "#4F46E5"
CUT_RIGHT       = "#F97316"
CUT_POINT       = "#FACC15"
SEQ_HIGHLIGHT   = "#F43F5E"
TABLE_HEADER    = "#8B5CF6"
TABLE_CELL      = "#1E1B4B"
GRAPH_BLUE      = "#3B82F6"
GRAPH_ORANGE    = "#F97316"
GRAPH_PINK      = "#EC4899"
GEOM_TEAL       = "#14B8A6"

# ── 9:16 layout constants ─────────────────────────────────────────
MAX_BUILD_LINES  = {MAX_BUILD_LINES}
TOP_Y            = {TOP_Y}
LINE_SPACING     = {LINE_SPACING}
MATH_SCALE       = {MATH_SCALE}
TEXT_FONT_SIZE   = {TEXT_FONT_SIZE}
BOX_FONT_SIZE    = {BOX_FONT_SIZE}
LABEL_FONT_SIZE  = {LABEL_FONT_SIZE}
GRAPH_SCALE      = {GRAPH_SCALE}
EXTRA_HOLD       = 0.6
ANIMATION_RATIO  = 0.35
WATERMARK_TEXT   = "ORBITAL"

# ── content zone (avoid TikTok UI overlap at top/bottom) ──────────
CONTENT_CENTER_Y = 0.0      # center of the safe zone
CONTENT_TOP_Y    = 4.5      # top of safe zone
CONTENT_BOT_Y    = -4.5     # bottom of safe zone


# ─────────────────────────────────────────────────────────────────
#  DIAGRAM BUILDERS  (same logic as v3, tuned for phone)
# ─────────────────────────────────────────────────────────────────

def _build_graph_short(cfg: dict) -> VGroup:
    """Build a function graph scaled for 9:16 display."""
    import numpy as np

    kind       = cfg.get("kind", "function_plot")
    x_range    = cfg.get("x_range", [-4, 4, 1])
    y_range    = cfg.get("y_range", [-4, 4, 1])
    functions  = cfg.get("functions", [])
    points_cfg = cfg.get("points", [])
    shaded     = cfg.get("shaded_area", None)
    tangent    = cfg.get("tangent", None)
    show_grid  = cfg.get("show_grid", False)

    axes = Axes(
        x_range=x_range,
        y_range=y_range,
        x_length=7.5,
        y_length=7.5,
        axis_config={{
            "color": WHITE,
            "stroke_width": 2,
            "include_numbers": True,
            "font_size": 28,
        }},
        tips=True,
    )

    group = VGroup(axes)

    COLORS = [GRAPH_BLUE, GRAPH_ORANGE, GRAPH_PINK, NEON_GREEN, ORBITAL_VIOLET]

    for idx, fn_cfg in enumerate(functions):
        expr_str = fn_cfg.get("expr", "x")
        color    = fn_cfg.get("color", COLORS[idx % len(COLORS)])
        lw       = fn_cfg.get("stroke_width", 3)
        dashed   = fn_cfg.get("dashed", False)

        try:
            fn = lambda x, e=expr_str: eval(e, {{"x": x, "math": math, "np": np}})
            if dashed:
                curve = axes.plot(fn, color=color, stroke_width=lw,
                                  use_smoothing=True).set_style(stroke_dasharray=[0.15, 0.15])
            else:
                curve = axes.plot(fn, color=color, stroke_width=lw, use_smoothing=True)
            group.add(curve)

            lbl_txt = fn_cfg.get("label", "")
            if lbl_txt:
                x_lbl = x_range[1] * 0.6
                y_lbl = fn(x_lbl)
                lbl = MathTex(lbl_txt, color=color, font_size=32)
                lbl.move_to(axes.c2p(x_lbl, y_lbl) + UP * 0.4 + RIGHT * 0.3)
                group.add(lbl)
        except Exception:
            pass

    # Tangent line
    if tangent:
        at_x   = tangent.get("at_x", 0)
        t_len  = tangent.get("length", 3)
        t_col  = tangent.get("color", NEON_GREEN)
        try:
            expr_str = functions[0]["expr"] if functions else "x"
            dx = 1e-5
            fn = lambda x, e=expr_str: eval(e, {{"x": x, "math": math, "np": np}})
            slope = (fn(at_x + dx) - fn(at_x - dx)) / (2 * dx)
            y0    = fn(at_x)
            half  = t_len / 2
            x1, y1 = at_x - half, y0 - slope * half
            x2, y2 = at_x + half, y0 + slope * half
            tline = Line(axes.c2p(x1, y1), axes.c2p(x2, y2), color=t_col, stroke_width=3)
            group.add(tline)
            pt = Dot(axes.c2p(at_x, y0), color=t_col, radius=0.08)
            group.add(pt)
        except Exception:
            pass

    # Shaded area
    if shaded:
        fn_idx   = shaded.get("func_index", 0)
        s_xrange = shaded.get("x_range", [x_range[0], x_range[1]])
        s_color  = shaded.get("color", ORBITAL_CYAN)
        s_op     = shaded.get("opacity", 0.35)
        try:
            fn_expr = functions[fn_idx]["expr"] if functions else "x"
            fn = lambda x, e=fn_expr: eval(e, {{"x": x, "math": math, "np": np}})
            area = axes.get_area(
                axes.plot(fn, color=s_color),
                x_range=s_xrange,
                color=s_color,
                opacity=s_op,
            )
            group.add(area)
        except Exception:
            pass

    # Points
    for pt_cfg in points_cfg:
        px, py = pt_cfg.get("x", 0), pt_cfg.get("y", 0)
        pcol   = pt_cfg.get("color", NEON_GREEN)
        pd     = Dot(axes.c2p(px, py), color=pcol, radius=0.1)
        group.add(pd)
        plbl = pt_cfg.get("label", "")
        if plbl:
            lm = MathTex(plbl, color=pcol, font_size=30)
            lm.next_to(pd, UR, buff=0.15)
            group.add(lm)

    group.scale(GRAPH_SCALE)
    return group


# ─────────────────────────────────────────────────────────────────
#  MAIN SCENE CLASS
# ─────────────────────────────────────────────────────────────────

class SyncedShortScene({base_class}):
    """
    Short-form 9:16 scene with per-step audio sync and phone-optimised layout.
    """

    STEPS_DATA = {manifest_json}

    def construct(self):
        self.camera.background_color = "#000000"

        # Subtle watermark in corner
        wm = Text(WATERMARK_TEXT, font_size=22, color=WHITE).set_opacity(0.3)
        wm.to_corner(DR, buff=0.5)
        self.add(wm)

        steps       = self.STEPS_DATA
        build_lines = []   # for "build" mode accumulation
        previous    = None
        total       = len(steps)

        for i, step in enumerate(steps):
            step_type  = step.get("type", "math")
            content    = step.get("content", step.get("latex", ""))
            narration  = step.get("narration", "")
            mode       = step.get("mode", "replace")
            label      = step.get("label", "")
            diagram    = step.get("diagram", {{}})
            duration   = step.get("duration", 3.0)
            audio_path = step.get("audio_path", "")
            anim_time  = max(0.8, duration * ANIMATION_RATIO)

            # ── play audio ───────────────────────────────────────
            if audio_path and os.path.exists(audio_path):
                self.add_sound(audio_path)

            # ── build mobject ────────────────────────────────────
            if step_type == "graph":
                mob = _build_graph_short(diagram)
                mob.move_to([0, CONTENT_CENTER_Y, 0])

            elif step_type in ("transform",):
                mob = MathTex(content, color=WHITE, font_size=int(BOX_FONT_SIZE))
                mob.scale(MATH_SCALE * 0.85)
                mob.move_to([0, CONTENT_CENTER_Y, 0])

            elif step_type == "box":
                if label:
                    lbl_mob = Text(label, font_size=LABEL_FONT_SIZE, color=LABEL_COLOR)
                lbl_offset = 0.9 if label else 0
                inner = MathTex(content, color=WHITE, font_size=BOX_FONT_SIZE)
                inner.scale(MATH_SCALE * 0.80)
                inner.move_to([0, CONTENT_CENTER_Y - lbl_offset * 0.5, 0])
                box_rect = SurroundingRectangle(
                    inner,
                    color=BOX_BORDER,
                    buff=0.45,
                    stroke_width=4,
                    corner_radius=0.15,
                    fill_color=BOX_FILL,
                    fill_opacity=0.6,
                )
                if label:
                    lbl_mob.next_to(box_rect, UP, buff=0.25)
                    mob = VGroup(box_rect, inner, lbl_mob)
                else:
                    mob = VGroup(box_rect, inner)
                mob.move_to([0, CONTENT_CENTER_Y, 0])

            elif step_type in ("text", "mixed"):
                # Use Tex for text/mixed (supports LaTeX text mode + inline math)
                try:
                    mob = Tex(content, color=WHITE, font_size=TEXT_FONT_SIZE)
                except Exception:
                    mob = Text(content, font_size=TEXT_FONT_SIZE, color=WHITE)
                mob.scale(1.0)
                mob.move_to([0, CONTENT_CENTER_Y, 0])

            else:
                # "math" (default) — big MathTex
                try:
                    mob = MathTex(content, color=WHITE, font_size=60)
                except Exception:
                    mob = MathTex(r"\\text{{error}}", color=RED)
                mob.scale(MATH_SCALE)
                mob.move_to([0, CONTENT_CENTER_Y, 0])

            # ── mode: build (accumulate lines) ───────────────────
            if mode == "build":
                mob.scale(0.9)
                if len(build_lines) >= MAX_BUILD_LINES:
                    # Scroll — remove oldest line
                    old = build_lines.pop(0)
                    self.play(FadeOut(old, shift=UP * 0.5), run_time=0.3)
                    for bl in build_lines:
                        self.play(bl.animate.shift(UP * LINE_SPACING), run_time=0.2)
                # Position below existing lines
                if build_lines:
                    mob.next_to(build_lines[-1], DOWN, buff=LINE_SPACING * 0.7)
                else:
                    mob.move_to([0, CONTENT_TOP_Y - 1.0, 0])
                self.play(Write(mob), run_time=anim_time)
                build_lines.append(mob)
                hold = max(0.3, duration - anim_time)
                self.wait(hold)
                if i < total - 1:
                    self.wait(EXTRA_HOLD)
                previous = mob
                continue

            # ── mode: replace (default) ──────────────────────────
            if previous is not None:
                self.play(FadeOut(previous, shift=UP * 0.4), run_time=0.35)
                build_lines.clear()

            if step_type == "transform" and previous is not None:
                self.play(Write(mob), run_time=anim_time)
            elif step_type == "graph":
                self.play(Create(mob), run_time=max(1.2, anim_time))
            elif step_type == "box":
                box_r, inner_m = mob[0], mob[1]
                lbl_m = mob[2] if len(mob) > 2 else None
                self.play(
                    DrawBorderThenFill(box_r),
                    Write(inner_m),
                    run_time=anim_time,
                )
                if lbl_m:
                    self.play(FadeIn(lbl_m, shift=DOWN * 0.2), run_time=0.3)
            else:
                self.play(Write(mob), run_time=anim_time)

            remaining = max(0.3, duration - anim_time - 0.35)
            self.wait(remaining)

            if i < total - 1:
                self.wait(EXTRA_HOLD)

            previous = mob

        # ── final answer hold + neon box ─────────────────────────
        if previous is not None:
            if not isinstance(previous, VGroup) or not any(
                isinstance(c, SurroundingRectangle) for c in previous
            ):
                final_box = SurroundingRectangle(
                    previous,
                    color=NEON_GREEN,
                    buff=0.4,
                    stroke_width=5,
                    corner_radius=0.15,
                )
                self.play(Create(final_box), run_time=0.6)
                self.wait(2.0)
                self.play(FadeOut(previous), FadeOut(final_box), run_time=0.5)
            else:
                self.wait(2.5)
                self.play(FadeOut(previous), run_time=0.5)
'''

    with open(output_path, "w") as f:
        f.write(scene_code)

    print(f"  ✓ Created short-form Manim scene: {output_path}")
