"""
Auto-generated Manim scene — 9:16 TikTok 3-Zone Layout.
Generated by Orbital VideoFactory (Short-Form Pipeline).
Spec: TIKTOK-DESIGN-SPEC.md
"""

from manim import *
import json, os, math

# ── Brand colours ─────────────────────────────────────────────────────────────
ORBITAL_VIOLET  = "#8B5CF6"
ORBITAL_CYAN    = "#22D3EE"
NEON_GREEN      = "#39FF14"
BOX_BORDER      = "#8B5CF6"
BOX_FILL        = "#1a1130"
LABEL_COLOR     = "#22D3EE"
CUT_LEFT        = "#4F46E5"
CUT_RIGHT       = "#F97316"
CUT_POINT       = "#FACC15"
SEQ_HIGHLIGHT   = "#F43F5E"
TABLE_HEADER    = "#8B5CF6"
TABLE_CELL      = "#1E1B4B"
GRAPH_BLUE      = "#3B82F6"
GRAPH_ORANGE    = "#F97316"
GRAPH_PINK      = "#EC4899"
GEOM_TEAL       = "#14B8A6"
DIM_GRAY        = "#333333"

# ── Zone geometry (Manim units) ───────────────────────────────────────────────
ZONE_A_Y         = 5.0       # Hook text Y center
ZONE_B_TOP_Y     = 3.2   # First build line top anchor
ZONE_B_CENTER_Y  = 2.2 # Replace mode center
ZONE_C_CENTER_Y  = -2.5 # Graph hero center

# ── Size / width constants ────────────────────────────────────────────────────
MAX_WIDTH        = 5.2   # Hard limit — NOTHING wider than this (65% of frame)
GRAPH_WIDTH      = 6.0
GRAPH_HEIGHT     = 5.0

# ── Typography ────────────────────────────────────────────────────────────────
ZONE_A_FONT      = 30
MATH_FONT        = 48
BOX_FONT         = 44
LABEL_FONT       = 28

# ── Build mode ────────────────────────────────────────────────────────────────
MAX_BUILD_LINES  = 3
BUILD_SPACING    = 0.85

# ── Animation ────────────────────────────────────────────────────────────────
ANIMATION_RATIO  = 0.35
EXTRA_HOLD       = 0.5


# ═════════════════════════════════════════════════════════════════════════════
#  GRAPH BUILDER — Zone C
#  Adapted from scene_v3._build_graph; scaled and positioned for Zone C.
# ═════════════════════════════════════════════════════════════════════════════

def _build_graph_zone_c(cfg: dict) -> VGroup:
    """
    Build a function graph VGroup sized to fill Zone C (dominant visual).
    The graph axes span GRAPH_WIDTH × GRAPH_HEIGHT Manim units before scaling.
    Positioning (move_to) is handled by the scene — this returns the VGroup only.
    """
    import numpy as np

    kind        = cfg.get("kind", "function_plot")
    x_range     = cfg.get("x_range", [-5, 5, 1])
    y_range     = cfg.get("y_range", [-5, 5, 1])
    functions   = cfg.get("functions", [])
    points_cfg  = cfg.get("points", [])
    shaded      = cfg.get("shaded_area", None)
    tangent     = cfg.get("tangent", None)
    show_grid   = cfg.get("show_grid", False)
    axis_labels = cfg.get("axis_labels", ["x", "y"])

    default_colors = [ORBITAL_CYAN, GRAPH_ORANGE, GRAPH_PINK, NEON_GREEN, ORBITAL_VIOLET]

    if show_grid:
        axes = NumberPlane(
            x_range=x_range, y_range=y_range,
            x_length=GRAPH_WIDTH, y_length=GRAPH_HEIGHT,
            background_line_style={"stroke_color": DIM_GRAY, "stroke_opacity": 0.5},
        )
    else:
        axes = Axes(
            x_range=x_range,
            y_range=y_range,
            x_length=GRAPH_WIDTH,
            y_length=GRAPH_HEIGHT,
            axis_config={
                "color": WHITE,
                "stroke_width": 2,
                "include_numbers": True,
                "font_size": 24,
                "decimal_number_config": {"num_decimal_places": 0},
            },
            tips=True,
        )

    group = VGroup(axes)

    # Axis labels
    if axis_labels and len(axis_labels) >= 2:
        try:
            x_lbl = axes.get_x_axis_label(axis_labels[0], direction=RIGHT)
            y_lbl = axes.get_y_axis_label(axis_labels[1], direction=UP)
            group.add(x_lbl, y_lbl)
        except Exception:
            pass

    # Plot functions
    plotted_fn_objects = []
    for idx, fn_cfg in enumerate(functions):
        expr_str = fn_cfg.get("expr", "lambda x: x")
        color    = fn_cfg.get("color", default_colors[idx % len(default_colors)])
        dashed   = fn_cfg.get("dashed", False)
        lw       = fn_cfg.get("stroke_width", 3.5)
        try:
            fn_obj = eval(expr_str)  # Input controlled by our pipeline
            if dashed:
                graph_curve = DashedVMobject(
                    axes.plot(fn_obj, color=color, stroke_width=lw), num_dashes=40
                )
            else:
                graph_curve = axes.plot(fn_obj, color=color, stroke_width=lw)
            plotted_fn_objects.append(fn_obj)
            group.add(graph_curve)

            lbl_txt = fn_cfg.get("label", "")
            if lbl_txt:
                x_lbl_pt = x_range[1] * 0.55
                try:
                    y_lbl_pt = fn_obj(x_lbl_pt)
                    lbl_mob = MathTex(lbl_txt, color=color, font_size=30)
                    lbl_mob.move_to(axes.c2p(x_lbl_pt, y_lbl_pt) + UP * 0.45 + RIGHT * 0.35)
                    group.add(lbl_mob)
                except Exception:
                    pass
        except Exception:
            pass

    # Shaded area
    if shaded and plotted_fn_objects:
        fi    = shaded.get("func_index", 0)
        fi2   = shaded.get("func_index_2", None)
        sr    = shaded.get("x_range", [x_range[0], x_range[1]])
        sc    = shaded.get("color", ORBITAL_CYAN)
        so    = shaded.get("opacity", 0.3)
        try:
            if fi < len(plotted_fn_objects):
                top_fn = plotted_fn_objects[fi]
                top_graph = axes.plot(top_fn, color=sc)
                if fi2 is not None and fi2 < len(plotted_fn_objects):
                    bot_fn    = plotted_fn_objects[fi2]
                    bot_graph = axes.plot(bot_fn, color=sc)
                    area = axes.get_area(top_graph, x_range=sr, color=sc, opacity=so,
                                         bounded_graph=bot_graph)
                else:
                    area = axes.get_area(top_graph, x_range=sr, color=sc, opacity=so)
                group.add(area)
        except Exception:
            pass

    # Tangent line
    if tangent and plotted_fn_objects:
        at_x  = tangent.get("at_x", 0)
        t_len = tangent.get("length", 3.5)
        t_col = tangent.get("color", NEON_GREEN)
        try:
            fn_obj = plotted_fn_objects[tangent.get("func_index", 0)]
            dx     = 1e-5
            slope  = (fn_obj(at_x + dx) - fn_obj(at_x - dx)) / (2 * dx)
            y0     = fn_obj(at_x)
            half   = t_len / 2
            x1, y1 = at_x - half, y0 - slope * half
            x2, y2 = at_x + half, y0 + slope * half
            tline  = Line(axes.c2p(x1, y1), axes.c2p(x2, y2),
                          color=t_col, stroke_width=3)
            pt_dot = Dot(axes.c2p(at_x, y0), color=t_col, radius=0.1)
            group.add(tline, pt_dot)
        except Exception:
            pass

    # Points
    for pt_cfg in points_cfg:
        px, py = pt_cfg.get("x", 0), pt_cfg.get("y", 0)
        pcol   = pt_cfg.get("color", CUT_POINT)
        pd     = Dot(axes.c2p(px, py), color=pcol, radius=0.1)
        group.add(pd)
        plbl = pt_cfg.get("label", "")
        if plbl:
            lm = MathTex(plbl, color=pcol, font_size=28)
            lm.next_to(pd, UR, buff=0.15)
            group.add(lm)

    return group


# ═════════════════════════════════════════════════════════════════════════════
#  HELPERS
# ═════════════════════════════════════════════════════════════════════════════

def _clamp_width(mob, max_w: float = MAX_WIDTH):
    """Scale mob down if wider than max_w. Returns mob (mutated in-place)."""
    if mob.width > max_w:
        mob.scale(max_w / mob.width)
    return mob


def _zone_b_positions(n_lines: int) -> list:
    """
    Return a list of Y-positions for n_lines in Zone B,
    stacked downward from ZONE_B_TOP_Y with BUILD_SPACING between them.
    Lines are centered horizontally.
    """
    positions = []
    for i in range(n_lines):
        positions.append(ZONE_B_TOP_Y - i * BUILD_SPACING)
    return positions


# ═════════════════════════════════════════════════════════════════════════════
#  MAIN SCENE CLASS
# ═════════════════════════════════════════════════════════════════════════════

class SyncedShortScene(Scene):
    """
    9:16 TikTok short-form scene with 3-zone layout.

    Zone A (top)   : Hook/context text — fades in at start
    Zone B (middle): Math steps — build or replace mode
    Zone C (bottom): Graph/visual hero — appears first, stays throughout
    """

    STEPS_DATA = [{'type': 'graph', 'content': '', 'narration': '', 'mode': 'replace', 'zone': 'c', 'persistent': True, 'graph': {'kind': 'function_plot', 'x_range': [-3, 4, 1], 'y_range': [-6, 20, 4], 'functions': [{'expr': 'lambda x: 3*x**2 + 2*x - 5', 'color': '#22D3EE', 'label': 'f(x)'}]}}, {'type': 'math', 'content': 'f(x) = 3x^2 + 2x - 5', 'narration': '', 'mode': 'replace', 'zone': 'b'}, {'type': 'box', 'content': '\\frac{d}{dx}[x^n] = nx^{n-1}', 'narration': '', 'mode': 'replace', 'zone': 'b', 'label': 'Power Rule'}, {'type': 'math', 'content': '3x^2 \\to 6x', 'narration': '', 'mode': 'build', 'zone': 'b'}, {'type': 'math', 'content': '2x \\to 2', 'narration': '', 'mode': 'build', 'zone': 'b'}, {'type': 'math', 'content': '-5 \\to 0', 'narration': '', 'mode': 'build', 'zone': 'b'}, {'type': 'box', 'content': "f'(x) = 6x + 2", 'narration': '', 'mode': 'replace', 'zone': 'b', 'label': 'Answer'}]

    def construct(self):
        self.camera.background_color = "#000000"

        # ── Watermark: "ORBITAL" bottom-right, 40% opacity ────────────────────
        wm = Text("ORBITAL", font_size=22, color=WHITE).set_opacity(0.4)
        # Place in bottom-right safe zone: X ~+2.8, Y ~-6.2
        wm.move_to([2.6, -6.0, 0])
        self.add(wm)

        steps = self.STEPS_DATA
        total = len(steps)

        # ── Zone state tracking ───────────────────────────────────────────────
        zone_a_mob   = None          # Current Zone A mob (hook text)
        zone_b_build = []            # Zone B accumulated build lines
        zone_b_current = None        # Zone B current replace mob
        zone_c_mobs  = []            # Zone C persistent mobs (graphs, etc.)

        # ── Intro duration ─────────────────────────────────────────────────────
        intro_dur = 0
        if intro_dur > 0:
            self.wait(intro_dur)

        for i, step in enumerate(steps):
            step_type  = step.get("type", "math")
            content    = step.get("content", step.get("latex", ""))
            mode       = step.get("mode", "replace")
            label_txt  = step.get("label", "")
            duration   = step.get("duration", 3.0)
            audio_path = step.get("audio_path", "")
            persistent = step.get("persistent", False)
            collapse_to = step.get("collapse_to", None)
            colors     = step.get("colors", {})  # {latex_substr: hex_color}

            # Graph config — prefer "graph" key, fall back to "diagram"
            graph_cfg  = step.get("graph", step.get("diagram", {}))

            # Determine zone — explicit override or sensible default
            explicit_zone = step.get("zone", None)
            if explicit_zone:
                zone = explicit_zone.lower()
            elif step_type == "graph":
                zone = "c"
            else:
                zone = "b"

            anim_time = max(0.5, duration * ANIMATION_RATIO)

            # ── Play audio ─────────────────────────────────────────────────────
            if audio_path and os.path.exists(audio_path):
                self.add_sound(audio_path)

            # ══════════════════════════════════════════════════════════════════
            #  ZONE A  — Hook / context text
            # ══════════════════════════════════════════════════════════════════
            if zone == "a":
                # Fade out existing Zone A mob
                if zone_a_mob is not None:
                    self.play(FadeOut(zone_a_mob, shift=UP * 0.3), run_time=0.3)
                    zone_a_mob = None

                try:
                    mob = Tex(content, color=WHITE, font_size=ZONE_A_FONT)
                except Exception:
                    mob = Text(content, font_size=ZONE_A_FONT, color=WHITE)

                _clamp_width(mob)
                mob.move_to([0, ZONE_A_Y, 0])

                if persistent:
                    self.play(FadeIn(mob, shift=DOWN * 0.2), run_time=anim_time)
                    zone_a_mob = mob
                else:
                    self.play(FadeIn(mob, shift=DOWN * 0.2), run_time=anim_time)
                    hold = max(0.3, duration - anim_time)
                    self.wait(hold)
                    self.play(FadeOut(mob, shift=UP * 0.2), run_time=0.3)
                    zone_a_mob = None
                continue

            # ══════════════════════════════════════════════════════════════════
            #  ZONE C  — Graph / visual hero
            # ══════════════════════════════════════════════════════════════════
            if zone == "c":
                if step_type == "graph":
                    mob = _build_graph_zone_c(graph_cfg)
                    # Scale to fit Zone C without exceeding MAX_WIDTH
                    scale_w = min(1.0, MAX_WIDTH / mob.width) if mob.width > 0 else 1.0
                    # Also ensure height fits Zone C (~5 units)
                    max_h = 5.0
                    scale_h = min(1.0, max_h / mob.height) if mob.height > 0 else 1.0
                    scale   = min(scale_w, scale_h)
                    if scale < 1.0:
                        mob.scale(scale)
                    mob.move_to([0, ZONE_C_CENTER_Y, 0])

                    graph_anim_time = max(1.2, anim_time)
                    self.play(Create(mob), run_time=graph_anim_time)

                    hold = max(0.3, duration - graph_anim_time)
                    self.wait(hold)

                    if persistent:
                        zone_c_mobs.append(mob)
                    else:
                        # Non-persistent graphs fade out
                        self.play(FadeOut(mob), run_time=0.4)
                else:
                    # Non-graph content in Zone C (rare — just write it)
                    try:
                        mob = MathTex(content, color=WHITE, font_size=MATH_FONT)
                    except Exception:
                        mob = Text(content, font_size=MATH_FONT, color=WHITE)
                    _clamp_width(mob)
                    mob.move_to([0, ZONE_C_CENTER_Y, 0])
                    self.play(Write(mob), run_time=anim_time)
                    hold = max(0.3, duration - anim_time)
                    self.wait(hold)
                    if persistent:
                        zone_c_mobs.append(mob)
                    else:
                        self.play(FadeOut(mob), run_time=0.3)
                continue

            # ══════════════════════════════════════════════════════════════════
            #  ZONE B  — Math work (default zone for math/text/box/transform)
            # ══════════════════════════════════════════════════════════════════

            # ── Build the Zone B mobject ────────────────────────────────────
            if step_type == "box":
                # Labeled violet box with equation inside
                inner = MathTex(content, color=WHITE, font_size=BOX_FONT)
                _clamp_width(inner, MAX_WIDTH * 0.85)

                box_rect = SurroundingRectangle(
                    inner,
                    color=BOX_BORDER,
                    buff=0.4,
                    stroke_width=4,
                    corner_radius=0.15,
                    fill_color=BOX_FILL,
                    fill_opacity=0.7,
                )
                if label_txt:
                    lbl_mob = Text(label_txt, font_size=LABEL_FONT, color=LABEL_COLOR)
                    mob = VGroup(box_rect, inner, lbl_mob)
                    mob.arrange(DOWN, buff=0.25, center=True)
                    # Re-center inner inside box_rect after arrange
                    inner.move_to(box_rect.get_center())
                    if label_txt:
                        lbl_mob.next_to(box_rect, UP, buff=0.2)
                else:
                    mob = VGroup(box_rect, inner)

                _clamp_width(mob)

            elif step_type in ("text", "mixed"):
                try:
                    mob = Tex(content, color=WHITE, font_size=MATH_FONT)
                except Exception:
                    mob = Text(content, font_size=MATH_FONT, color=WHITE)
                _clamp_width(mob)

            elif step_type == "transform":
                try:
                    mob = MathTex(content, color=WHITE, font_size=MATH_FONT)
                except Exception:
                    mob = Text(content, font_size=MATH_FONT, color=WHITE)
                _clamp_width(mob)

            else:
                # "math" (default)
                try:
                    mob = MathTex(content, color=WHITE, font_size=MATH_FONT)
                except Exception:
                    mob = Text(content, font_size=MATH_FONT, color=WHITE)

                # Apply per-term color overrides if specified
                if colors and hasattr(mob, 'set_color_by_tex'):
                    for substr, hex_col in colors.items():
                        try:
                            mob.set_color_by_tex(substr, hex_col)
                        except Exception:
                            pass

                _clamp_width(mob)

            # ── BUILD MODE ──────────────────────────────────────────────────
            if mode == "build":
                # Check if we need to collapse first (too many lines)
                if len(zone_b_build) >= MAX_BUILD_LINES:
                    # Scroll: remove oldest, shift rest up
                    oldest = zone_b_build.pop(0)
                    anims_shift = [
                        bl.animate.shift(UP * BUILD_SPACING)
                        for bl in zone_b_build
                    ]
                    self.play(
                        FadeOut(oldest, shift=UP * 0.5),
                        *anims_shift,
                        run_time=0.35,
                    )

                # Position new line below existing ones
                if zone_b_build:
                    mob.next_to(zone_b_build[-1], DOWN, buff=BUILD_SPACING * 0.6)
                else:
                    mob.move_to([0, ZONE_B_TOP_Y, 0])

                # Clamp after positioning
                _clamp_width(mob)

                self.play(Write(mob), run_time=anim_time)
                hold = max(0.3, duration - anim_time)
                self.wait(hold)

                # Handle collapse_to: morph ALL build lines into result
                if collapse_to is not None:
                    zone_b_build.append(mob)
                    try:
                        result_mob = MathTex(collapse_to, color=NEON_GREEN,
                                             font_size=MATH_FONT)
                    except Exception:
                        result_mob = Text(collapse_to, font_size=MATH_FONT,
                                          color=NEON_GREEN)
                    _clamp_width(result_mob)
                    result_mob.move_to([0, ZONE_B_CENTER_Y, 0])

                    # Morph first build line, fade out the rest
                    first = zone_b_build[0]
                    rest  = zone_b_build[1:]
                    if rest:
                        self.play(
                            ReplacementTransform(first, result_mob),
                            *[FadeOut(b) for b in rest],
                            run_time=0.8,
                        )
                    else:
                        self.play(
                            ReplacementTransform(first, result_mob),
                            run_time=0.8,
                        )
                    zone_b_build.clear()
                    zone_b_current = result_mob
                    self.wait(EXTRA_HOLD)
                else:
                    zone_b_build.append(mob)
                    if i < total - 1:
                        self.wait(EXTRA_HOLD)

                continue

            # ── REPLACE MODE ────────────────────────────────────────────────
            # Clear any existing Zone B content
            anims_out = []
            if zone_b_build:
                for bl in zone_b_build:
                    anims_out.append(FadeOut(bl, shift=UP * 0.3))
                zone_b_build.clear()
            if zone_b_current is not None:
                anims_out.append(FadeOut(zone_b_current, shift=UP * 0.3))
                zone_b_current = None

            if anims_out:
                self.play(*anims_out, run_time=0.35)

            # Position mob in Zone B center
            mob.move_to([0, ZONE_B_CENTER_Y, 0])
            _clamp_width(mob)

            # Animate in
            if step_type == "box":
                box_r  = mob[0]
                inner_m = mob[1]
                lbl_m  = mob[2] if len(mob) > 2 else None
                anims_in = [DrawBorderThenFill(box_r), Write(inner_m)]
                self.play(*anims_in, run_time=anim_time)
                if lbl_m:
                    self.play(FadeIn(lbl_m, shift=DOWN * 0.15), run_time=0.3)

            elif step_type == "transform" and zone_b_current is not None:
                self.play(ReplacementTransform(zone_b_current, mob), run_time=anim_time)

            else:
                self.play(Write(mob), run_time=anim_time)

            hold = max(0.3, duration - anim_time - 0.35)
            self.wait(hold)

            if persistent:
                zone_c_mobs.append(mob)  # treat as persistent (unusual for Zone B)
            else:
                zone_b_current = mob

            if i < total - 1:
                self.wait(EXTRA_HOLD)

        # ── Final frame: hold, then neon-box the last answer ──────────────────
        last_mob = zone_b_current
        if last_mob is not None:
            # If the last mob isn't already a box, add a neon highlight
            already_boxed = (
                isinstance(last_mob, VGroup)
                and any(isinstance(c, SurroundingRectangle) for c in last_mob)
            )
            if not already_boxed:
                final_box = SurroundingRectangle(
                    last_mob,
                    color=NEON_GREEN,
                    buff=0.35,
                    stroke_width=5,
                    corner_radius=0.12,
                )
                self.play(Create(final_box), run_time=0.55)
                self.wait(2.0)
                self.play(FadeOut(last_mob), FadeOut(final_box), run_time=0.5)
            else:
                self.wait(2.5)
                self.play(FadeOut(last_mob), run_time=0.5)

        # Fade out Zone C persistent mobs last
        if zone_c_mobs:
            self.play(*[FadeOut(m) for m in zone_c_mobs], run_time=0.6)
        if zone_a_mob is not None:
            self.play(FadeOut(zone_a_mob), run_time=0.4)
