"""
Auto-generated Manim scene with audio-synced timings.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *

ORBITAL_VIOLET = "#8B5CF6"
ORBITAL_CYAN = "#22D3EE"

# Timing configuration
EXTRA_HOLD_PER_STEP = 0.8  # extra pause after each step
ANIMATION_RATIO = 0.35  # animation takes this % of step duration

class SyncedMathScene(Scene):
    """
    Math scene with timings synced to audio.
    Intro duration: 2.0s (handled separately)
    """
    
    def construct(self):
        self.camera.background_color = "#000000"
        
        # Step timings from audio (in seconds)
        steps = [
        {
                "step": 0,
                "narration": "Let's find the derivative of the function x squared plus three x.",
                "latex": "f(x) = x^{2} + 3x",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/952a62cf/audio/step_00.mp3",
                "duration": 4.27
        },
        {
                "step": 1,
                "narration": "To find the derivative, we'll use the power rule. The power rule says to bring down the exponent and decrease it by one.",
                "latex": "\\text{Power Rule: } \\frac{d}{dx}(x^{n}) = nx^{n-1}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/952a62cf/audio/step_01.mp3",
                "duration": 7.11
        },
        {
                "step": 2,
                "narration": "First, apply the power rule to x squared. Bring down the two and decrease the exponent by one.",
                "latex": "\\frac{d}{dx}(x^{2}) = 2x^{1}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/952a62cf/audio/step_02.mp3",
                "duration": 6.13
        },
        {
                "step": 3,
                "narration": "Next, apply the power rule to three x. The derivative of x is one, so multiply three by one.",
                "latex": "\\frac{d}{dx}(3x) = 3 \\cdot 1",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/952a62cf/audio/step_03.mp3",
                "duration": 6.32
        },
        {
                "step": 4,
                "narration": "Now, combine the derivatives. We have two x plus three.",
                "latex": "f'(x) = 2x + 3",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/952a62cf/audio/step_04.mp3",
                "duration": 3.71
        },
        {
                "step": 5,
                "narration": "So, the derivative of x squared plus three x is two x plus three.",
                "latex": "f'(x) = 2x + 3",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/952a62cf/audio/step_05.mp3",
                "duration": 5.34
        }
]
        
        previous = None
        total_steps = len(steps)
        
        for i, step in enumerate(steps):
            latex = step["latex"]
            duration = step["duration"]
            
            # Calculate animation time (slower write at 35% of duration)
            anim_time = max(1.2, duration * ANIMATION_RATIO)
            # Pause syncs with remaining audio time
            pause_time = max(0.3, duration - anim_time)
            
            # Create math object
            math = MathTex(latex, color=WHITE)
            math.scale(1.6)
            
            if previous is None:
                # First step: write on
                self.play(Write(math), run_time=anim_time)
            else:
                # Transform or fade transition
                self.play(
                    FadeOut(previous, shift=UP * 0.3),
                    run_time=0.4
                )
                self.play(Write(math), run_time=anim_time)
            
            # Pause to match audio duration
            self.wait(pause_time)
            
            # Extra hold time after each step (let viewer absorb)
            if i < total_steps - 1:  # not on final step
                self.wait(EXTRA_HOLD_PER_STEP)
            
            previous = math
        
        # Final answer: highlight box and hold
        if previous:
            box = SurroundingRectangle(previous, color=ORBITAL_VIOLET, buff=0.25)
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)  # hold final answer
            self.play(FadeOut(previous), FadeOut(box), run_time=0.5)


if __name__ == "__main__":
    print("Render with: manim -ql {this_file} SyncedMathScene")
