"""
Auto-generated Manim scene (v2) with proof/text/diagram support.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *
import json, os

# ── colours ──────────────────────────────────────────────────────
ORBITAL_VIOLET  = "#8B5CF6"
ORBITAL_CYAN    = "#22D3EE"
NEON_GREEN      = "#39FF14"
BOX_BORDER      = "#8B5CF6"
BOX_FILL        = "#1a1130"
LABEL_COLOR     = "#22D3EE"
CUT_LEFT        = "#4F46E5"   # indigo — left region of Dedekind cut
CUT_RIGHT       = "#F97316"   # orange — right region
CUT_POINT       = "#FACC15"   # yellow — cut point
SEQ_HIGHLIGHT   = "#F43F5E"   # rose — highlighted element in sequence
TABLE_HEADER    = "#8B5CF6"
TABLE_CELL      = "#1E1B4B"

# ── layout constants ─────────────────────────────────────────────
MAX_BUILD_LINES  = 5
TOP_Y            = 3.0
LINE_SPACING     = 0.85
EXTRA_HOLD       = 0.8
ANIMATION_RATIO  = 0.35
WATERMARK_TEXT    = "ORBITAL"


# ═══════════════════════════════════════════════════════════════════
#  DIAGRAM BUILDERS
# ═══════════════════════════════════════════════════════════════════

def _build_number_line_cut(cfg: dict) -> VGroup:
    """
    Number line with a Dedekind cut.
    cfg keys:
        x_range: [min, max, step]  (default [-3, 3, 1])
        cut_at:  float             (where the cut happens)
        left_label:  str           (label for left region, e.g. "A")
        right_label: str           (label for right region, e.g. "B")
        cut_label:   str           (label at the cut point, e.g. "\\sqrt{2}")
        show_point:  bool          (draw dot at cut point, default True)
    """
    x_range   = cfg.get("x_range", [-4, 4, 1])
    cut_at    = cfg.get("cut_at", 0)
    left_lbl  = cfg.get("left_label", "A")
    right_lbl = cfg.get("right_label", "B")
    cut_lbl   = cfg.get("cut_label", "")
    show_pt   = cfg.get("show_point", True)

    nl = NumberLine(
        x_range=x_range,
        length=10,
        include_numbers=True,
        include_tip=True,
        font_size=24,
        color=WHITE,
    )

    group = VGroup(nl)

    # Colored regions (translucent rectangles behind the line)
    left_start = nl.n2p(x_range[0])[0]
    cut_x      = nl.n2p(cut_at)[0]
    right_end  = nl.n2p(x_range[1])[0]
    line_y     = nl.get_center()[1]

    region_h = 0.5
    if cut_x - left_start > 0.1:
        left_rect = Rectangle(
            width=cut_x - left_start, height=region_h,
            fill_color=CUT_LEFT, fill_opacity=0.35,
            stroke_width=0,
        )
        left_rect.move_to([(left_start + cut_x) / 2, line_y, 0])
        group.add(left_rect)

        ll = MathTex(left_lbl, color=CUT_LEFT, font_size=36)
        ll.next_to(left_rect, UP, buff=0.3)
        group.add(ll)

    if right_end - cut_x > 0.1:
        right_rect = Rectangle(
            width=right_end - cut_x, height=region_h,
            fill_color=CUT_RIGHT, fill_opacity=0.35,
            stroke_width=0,
        )
        right_rect.move_to([(cut_x + right_end) / 2, line_y, 0])
        group.add(right_rect)

        rl = MathTex(right_lbl, color=CUT_RIGHT, font_size=36)
        rl.next_to(right_rect, UP, buff=0.3)
        group.add(rl)

    # Cut point
    if show_pt:
        dot = Dot(nl.n2p(cut_at), color=CUT_POINT, radius=0.1)
        group.add(dot)

    if cut_lbl:
        cl = MathTex(cut_lbl, color=CUT_POINT, font_size=36)
        cl.next_to(nl.n2p(cut_at), DOWN, buff=0.35)
        group.add(cl)

    # Dashed vertical line at cut
    dash = DashedLine(
        start=nl.n2p(cut_at) + UP * 0.8,
        end=nl.n2p(cut_at) + DOWN * 0.2,
        color=CUT_POINT, stroke_width=2,
    )
    group.add(dash)

    group.scale(0.75)
    return group


def _build_set_containment(cfg: dict) -> VGroup:
    """
    Nested or overlapping circles.
    cfg keys:
        sets: list of {label, radius, position, color}
        — position is [x, y] offset from center
    """
    sets = cfg.get("sets", [
        {"label": "A", "radius": 1.5, "position": [-0.5, 0], "color": "#4F46E5"},
        {"label": "B", "radius": 1.5, "position": [0.5, 0], "color": "#F97316"},
    ])

    group = VGroup()
    for s in sets:
        circ = Circle(
            radius=s.get("radius", 1.5),
            color=s.get("color", WHITE),
            fill_opacity=0.15,
            stroke_width=2,
        )
        pos = s.get("position", [0, 0])
        circ.move_to([pos[0], pos[1], 0])
        lbl = MathTex(s.get("label", ""), color=s.get("color", WHITE), font_size=36)
        lbl.move_to(circ.get_center() + UP * (s.get("radius", 1.5) + 0.3))
        group.add(circ, lbl)

    group.scale(0.8)
    return group


def _build_sequence_list(cfg: dict) -> VGroup:
    """
    Show a sequence like  r₁, r₂, r₃, ...  with optional highlighting.
    cfg keys:
        items:     list of str (LaTeX)  e.g. ["r_1", "r_2", "r_3", "\\dots"]
        highlight: list of int (indices to highlight)
        label:     str (optional label above)
    """
    items     = cfg.get("items", ["r_1", "r_2", "r_3", "\\dots"])
    highlight = cfg.get("highlight", [])
    label     = cfg.get("label", "")

    parts = []
    for i, item in enumerate(items):
        color = SEQ_HIGHLIGHT if i in highlight else WHITE
        m = MathTex(item, color=color, font_size=40)
        parts.append(m)
        if i < len(items) - 1:
            comma = MathTex(",", color=GREY, font_size=40)
            parts.append(comma)

    row = VGroup(*parts).arrange(RIGHT, buff=0.2)

    group = VGroup(row)
    if label:
        lbl = Tex(label, color=LABEL_COLOR, font_size=32)
        lbl.next_to(row, UP, buff=0.4)
        group.add(lbl)

    group.scale(0.85)
    return group


def _build_table(cfg: dict) -> VGroup:
    """
    Simple table/grid.
    cfg keys:
        headers: list of str
        rows:    list of list of str
        highlight_cells: list of [row, col] to highlight
    """
    headers = cfg.get("headers", [])
    rows    = cfg.get("rows", [])
    hl      = cfg.get("highlight_cells", [])

    all_rows = []
    if headers:
        all_rows.append(headers)
    all_rows.extend(rows)

    # Build as MathTable
    entries = []
    for r, row in enumerate(all_rows):
        row_entries = []
        for c, cell in enumerate(row):
            m = MathTex(cell, font_size=30)
            # Highlight header row
            if r == 0 and headers:
                m.set_color(LABEL_COLOR)
            # Highlight specific cells
            for hr, hc in hl:
                adj_r = hr + (1 if headers else 0)
                if r == adj_r and c == hc:
                    m.set_color(SEQ_HIGHLIGHT)
            row_entries.append(m)
        entries.append(row_entries)

    # Use VGroup grid layout
    group = VGroup()
    cell_w = 1.4
    cell_h = 0.6
    for r, row in enumerate(entries):
        for c, entry in enumerate(row):
            x = (c - len(row) / 2 + 0.5) * cell_w
            y = -r * cell_h
            entry.move_to([x, y, 0])
            bg = Rectangle(
                width=cell_w - 0.05, height=cell_h - 0.05,
                fill_color=TABLE_HEADER if (r == 0 and headers) else TABLE_CELL,
                fill_opacity=0.4,
                stroke_color=GREY_D, stroke_width=1,
            )
            bg.move_to(entry.get_center())
            group.add(bg, entry)

    group.scale(0.8)
    return group


DIAGRAM_BUILDERS = {
    "number_line_cut": _build_number_line_cut,
    "set_containment": _build_set_containment,
    "sequence_list":   _build_sequence_list,
    "table":           _build_table,
}


# ═══════════════════════════════════════════════════════════════════
#  MOBJECT FACTORY
# ═══════════════════════════════════════════════════════════════════

def _make_mobject(step: dict):
    """Create the correct Manim object for a step type."""
    stype   = step.get("type", "math")
    content = step.get("content") or step.get("latex", "")
    label   = step.get("label", "")

    if stype == "math":
        mob = MathTex(content, color=WHITE)
        mob.scale(1.4)
        return mob

    if stype == "text":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "mixed":
        mob = Tex(content, color=WHITE)
        mob.scale(0.9)
        return mob

    if stype == "box":
        inner = Tex(content, color=WHITE)
        inner.scale(0.85)
        lbl = Tex(r"\textbf{" + label + "}", color=LABEL_COLOR)
        lbl.scale(0.7)

        box_rect = SurroundingRectangle(
            inner, color=BOX_BORDER, fill_color=BOX_FILL,
            fill_opacity=0.6, buff=0.35, corner_radius=0.12,
            stroke_width=2,
        )
        lbl.next_to(box_rect, UP, buff=0.15).align_to(box_rect, LEFT).shift(RIGHT * 0.2)
        group = VGroup(box_rect, lbl, inner)
        return group

    if stype == "diagram":
        diagram_cfg = step.get("diagram", {})
        kind = diagram_cfg.get("kind", "number_line_cut")
        builder = DIAGRAM_BUILDERS.get(kind)
        if builder:
            return builder(diagram_cfg)
        # fallback: show kind name
        return Text(f"[diagram: {kind}]", color=GREY, font_size=28)

    # fallback
    mob = MathTex(content, color=WHITE)
    mob.scale(1.4)
    return mob


# ═══════════════════════════════════════════════════════════════════
#  SCENE
# ═══════════════════════════════════════════════════════════════════

class SyncedProofScene(Scene):
    def construct(self):
        self.camera.background_color = "#000000"

        wm = Text(WATERMARK_TEXT, font_size=14, color=WHITE).set_opacity(0.35)
        wm.to_corner(DR, buff=0.3)
        self.add(wm)

        steps = [
        {
                "step": 0,
                "narration": "Our goal is to show that the real numbers, constructed via Dedekind cuts, are uncountable.",
                "latex": "",
                "content": "Using Dedekind cuts, show that $\\mathbb{R}$ is uncountable.",
                "type": "box",
                "mode": "replace",
                "label": "Goal",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_00.mp3",
                "duration": 5.53
        },
        {
                "step": 1,
                "narration": "First, let's recall what a Dedekind cut is. A Dedekind cut is a partition of the rationals into two nonempty sets A and B,",
                "latex": "",
                "content": "A Dedekind cut is a pair $(A, B)$ where $A \\cup B = \\mathbb{Q}$, $A \\neq \\emptyset$, $B \\neq \\emptyset$,",
                "type": "box",
                "mode": "replace",
                "label": "Definition",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_01.mp3",
                "duration": 9.24
        },
        {
                "step": 2,
                "narration": "where every element of A is less than every element of B,",
                "latex": "",
                "content": "every element of $A$ is less than every element of $B$,",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_02.mp3",
                "duration": 3.99
        },
        {
                "step": 3,
                "narration": "and A has no greatest element.",
                "latex": "",
                "content": "and $A$ has no greatest element.",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_03.mp3",
                "duration": 2.23
        },
        {
                "step": 4,
                "narration": "Here's a picture. The number line is split into two regions. Everything to the left is A, everything to the right is B. The cut here represents the square root of two, which is irrational \u2014 it lives in the gap between A and B.",
                "latex": "",
                "content": "",
                "type": "diagram",
                "mode": "replace",
                "label": "",
                "diagram": {
                        "kind": "number_line_cut",
                        "x_range": [
                                -4,
                                4,
                                1
                        ],
                        "cut_at": 1.414,
                        "left_label": "A",
                        "right_label": "B",
                        "cut_label": "\\sqrt{2}",
                        "show_point": False
                },
                "audio_path": "jobs/dedekind_uncountable/audio/step_04.mp3",
                "duration": 17.04
        },
        {
                "step": 5,
                "narration": "Each such cut defines a real number alpha. This is how we construct the reals from the rationals.",
                "latex": "",
                "content": "Each cut $(A, B)$ defines a real number $\\alpha$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_05.mp3",
                "duration": 6.08
        },
        {
                "step": 6,
                "narration": "The set of all Dedekind cuts is the real numbers.",
                "latex": "",
                "content": "The set of all Dedekind cuts $\\textit{is}$ $\\mathbb{R}$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_06.mp3",
                "duration": 3.25
        },
        {
                "step": 7,
                "narration": "Now we prove our theorem: the reals are uncountable.",
                "latex": "",
                "content": "$\\mathbb{R}$ is uncountable.",
                "type": "box",
                "mode": "replace",
                "label": "Theorem",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_07.mp3",
                "duration": 3.67
        },
        {
                "step": 8,
                "narration": "Assume, for the sake of contradiction, that the reals are countable.",
                "latex": "",
                "content": "Assume for contradiction that $\\mathbb{R}$ is countable.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_08.mp3",
                "duration": 4.13
        },
        {
                "step": 9,
                "narration": "Then we could list every real number as alpha one, alpha two, alpha three, and so on.",
                "latex": "",
                "content": "Then we can list all real numbers as $\\alpha_1, \\alpha_2, \\alpha_3, \\dots$",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_09.mp3",
                "duration": 6.13
        },
        {
                "step": 10,
                "narration": "Here is our supposed complete listing of all real numbers.",
                "latex": "",
                "content": "",
                "type": "diagram",
                "mode": "replace",
                "label": "",
                "diagram": {
                        "kind": "sequence_list",
                        "items": [
                                "\\alpha_1",
                                "\\alpha_2",
                                "\\alpha_3",
                                "\\alpha_4",
                                "\\dots"
                        ],
                        "highlight": [],
                        "label": "Supposed enumeration of $\\mathbb{R}$"
                },
                "audio_path": "jobs/dedekind_uncountable/audio/step_10.mp3",
                "duration": 3.58
        },
        {
                "step": 11,
                "narration": "Remember, each alpha n is a Dedekind cut \u2014 a pair A n, B n partitioning the rationals.",
                "latex": "",
                "content": "Each $\\alpha_n$ is a Dedekind cut $(A_n, B_n)$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_11.mp3",
                "duration": 6.83
        },
        {
                "step": 12,
                "narration": "We will now construct a new Dedekind cut, A star and B star, that cannot appear anywhere in the list.",
                "latex": "",
                "content": "We will build a new cut $(A^*, B^*)$ not in the list.",
                "type": "box",
                "mode": "replace",
                "label": "Construction",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_12.mp3",
                "duration": 6.92
        },
        {
                "step": 13,
                "narration": "We'll use a nested intervals argument.",
                "latex": "",
                "content": "We use a nested intervals argument.",
                "type": "text",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_13.mp3",
                "duration": 2.23
        },
        {
                "step": 14,
                "narration": "Start by picking a closed interval a one, b one with rational endpoints, chosen so that alpha one does not lie in this interval.",
                "latex": "",
                "content": "Pick a closed interval $[a_1, b_1]$ with $a_1, b_1 \\in \\mathbb{Q}$ such that $\\alpha_1 \\notin [a_1, b_1]$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_14.mp3",
                "duration": 8.13
        },
        {
                "step": 15,
                "narration": "Next, pick a smaller interval a two, b two inside the first one, avoiding alpha two.",
                "latex": "",
                "content": "Pick $[a_2, b_2] \\subset [a_1, b_1]$ with $\\alpha_2 \\notin [a_2, b_2]$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_15.mp3",
                "duration": 5.67
        },
        {
                "step": 16,
                "narration": "Continue this process. We get a nested sequence of closed intervals, each one inside the last, each one avoiding the next alpha on our list.",
                "latex": "",
                "content": "Continue: $[a_1, b_1] \\supset [a_2, b_2] \\supset [a_3, b_3] \\supset \\cdots$",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_16.mp3",
                "duration": 9.38
        },
        {
                "step": 17,
                "narration": "At step n, the interval a n, b n is chosen to exclude alpha n.",
                "latex": "",
                "content": "At step $n$: $\\alpha_n \\notin [a_n, b_n]$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_17.mp3",
                "duration": 5.34
        },
        {
                "step": 18,
                "narration": "Now define A star as the set of all rationals q that are eventually less than some a n.",
                "latex": "",
                "content": "Define $A^* = \\{ q \\in \\mathbb{Q} : q < a_n \\text{ for some } n \\}$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_18.mp3",
                "duration": 6.27
        },
        {
                "step": 19,
                "narration": "Equivalently, A star is the union of all the sets of rationals less than a n.",
                "latex": "",
                "content": "Equivalently, $A^* = \\bigcup_{n=1}^{\\infty} \\{ q \\in \\mathbb{Q} : q < a_n \\}$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_19.mp3",
                "duration": 5.67
        },
        {
                "step": 20,
                "narration": "And B star is everything in the rationals not in A star.",
                "latex": "",
                "content": "Let $B^* = \\mathbb{Q} \\setminus A^*$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_20.mp3",
                "duration": 3.9
        },
        {
                "step": 21,
                "narration": "We claim that A star, B star is a valid Dedekind cut \u2014 that is, a real number.",
                "latex": "",
                "content": "$(A^*, B^*)$ is a valid Dedekind cut.",
                "type": "box",
                "mode": "replace",
                "label": "Claim",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_21.mp3",
                "duration": 5.39
        },
        {
                "step": 22,
                "narration": "A star is nonempty because it contains a one minus one. B star is nonempty because it contains b one.",
                "latex": "",
                "content": "$A^*$ is nonempty (contains $a_1 - 1$) and $B^*$ is nonempty (contains $b_1$).",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_22.mp3",
                "duration": 6.87
        },
        {
                "step": 23,
                "narration": "Every element of A star is less than every element of B star, by construction.",
                "latex": "",
                "content": "Every element of $A^*$ is less than every element of $B^*$.",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_23.mp3",
                "duration": 5.53
        },
        {
                "step": 24,
                "narration": "And A star has no greatest element \u2014 if q is less than a n, we can always find a rational q prime between q and a n.",
                "latex": "",
                "content": "$A^*$ has no greatest element (if $q < a_n$, then $q < q' < a_n$ for some $q'$).",
                "type": "text",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_24.mp3",
                "duration": 8.41
        },
        {
                "step": 25,
                "narration": "So A star, B star is a valid Dedekind cut, defining a real number alpha star.",
                "latex": "",
                "content": "So $(A^*, B^*)$ defines a real number $\\alpha^*$.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_25.mp3",
                "duration": 5.43
        },
        {
                "step": 26,
                "narration": "Now here's the key step. Alpha star is different from every alpha n on our list.",
                "latex": "",
                "content": "$\\alpha^* \\neq \\alpha_n$ for any $n$.",
                "type": "box",
                "mode": "replace",
                "label": "Key Step",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_26.mp3",
                "duration": 6.27
        },
        {
                "step": 27,
                "narration": "Why? Because alpha n was excluded from the interval a n, b n. But alpha star lies inside every interval a n, b n.",
                "latex": "",
                "content": "Since $\\alpha_n \\notin [a_n, b_n]$ but $\\alpha^* \\in [a_n, b_n]$ for all $n$:",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_27.mp3",
                "duration": 9.2
        },
        {
                "step": 28,
                "narration": "Therefore alpha star is not equal to alpha n, for any natural number n.",
                "latex": "",
                "content": "\\alpha^* \\neq \\alpha_n \\quad \\text{for all } n \\in \\mathbb{N}",
                "type": "math",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_28.mp3",
                "duration": 5.43
        },
        {
                "step": 29,
                "narration": "But alpha star is a real number, and it's not anywhere in our list.",
                "latex": "",
                "content": "But $\\alpha^* \\in \\mathbb{R}$ and $\\alpha^*$ is not in the list.",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_29.mp3",
                "duration": 4.5
        },
        {
                "step": 30,
                "narration": "This contradicts our assumption that the list contained every real number.",
                "latex": "",
                "content": "This contradicts the assumption that the list contains all of $\\mathbb{R}$.",
                "type": "mixed",
                "mode": "build",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_30.mp3",
                "duration": 4.13
        },
        {
                "step": 31,
                "narration": "Therefore, the reals are uncountable. And that completes our proof.",
                "latex": "",
                "content": "Therefore $\\mathbb{R}$ is uncountable. $\\blacksquare$",
                "type": "mixed",
                "mode": "replace",
                "label": "",
                "diagram": {},
                "audio_path": "jobs/dedekind_uncountable/audio/step_31.mp3",
                "duration": 4.04
        }
]

        build_lines = []
        previous_replace = None
        total = len(steps)

        for idx, step in enumerate(steps):
            duration   = step.get("duration", 2.0)
            audio_path = step.get("audio_path", "")
            mode       = step.get("mode", "replace")
            stype      = step.get("type", "math")

            if audio_path and os.path.exists(audio_path):
                self.add_sound(audio_path)

            anim_time = max(0.8, duration * ANIMATION_RATIO)
            mob = _make_mobject(step)

            if mode == "build":
                if previous_replace is not None:
                    self.play(FadeOut(previous_replace), run_time=0.3)
                    previous_replace = None

                build_lines.append(mob)

                if len(build_lines) > MAX_BUILD_LINES:
                    oldest = build_lines.pop(0)
                    self.play(FadeOut(oldest, shift=UP * 0.4), run_time=0.25)

                for i, ln in enumerate(build_lines):
                    target_y = TOP_Y - i * LINE_SPACING
                    ln.move_to([0, target_y, 0])

                mob.set_opacity(0)
                self.add(mob)
                self.play(mob.animate.set_opacity(1), run_time=anim_time)

            else:
                if build_lines:
                    self.play(
                        *[FadeOut(ln, shift=UP * 0.3) for ln in build_lines],
                        run_time=0.3
                    )
                    build_lines.clear()

                if previous_replace is not None:
                    self.play(FadeOut(previous_replace, shift=UP * 0.3), run_time=0.35)

                mob.move_to(ORIGIN)
                if stype in ("box", "diagram"):
                    self.play(FadeIn(mob, shift=UP * 0.3), run_time=anim_time)
                else:
                    self.play(Write(mob), run_time=anim_time)
                previous_replace = mob

            remaining = max(0.2, duration - anim_time - 0.35)
            self.wait(remaining)

            if idx < total - 1:
                self.wait(EXTRA_HOLD)

        # finale
        final_mob = previous_replace or (build_lines[-1] if build_lines else None)
        if final_mob:
            box = SurroundingRectangle(
                final_mob, color=NEON_GREEN, buff=0.3,
                stroke_width=4, corner_radius=0.1,
            )
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)
            extras = [FadeOut(box)]
            if previous_replace:
                extras.append(FadeOut(previous_replace))
            for ln in build_lines:
                extras.append(FadeOut(ln))
            self.play(*extras, run_time=0.5)


if __name__ == "__main__":
    print("Render with:  manim -ql this_file.py SyncedProofScene")
