"""
Auto-generated Manim scene with audio-synced timings.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *

ORBITAL_VIOLET = "#8B5CF6"
ORBITAL_CYAN = "#22D3EE"

# Timing configuration
EXTRA_HOLD_PER_STEP = 0.8  # extra pause after each step
ANIMATION_RATIO = 0.35  # animation takes this % of step duration

class SyncedMathScene(Scene):
    """
    Math scene with timings synced to audio.
    Intro duration: 2.0s (handled separately)
    """
    
    def construct(self):
        self.camera.background_color = "#000000"
        
        # Step timings from audio (in seconds)
        steps = [
        {
                "step": 0,
                "narration": "Let's solve for x in the equation two x plus seven equals fifteen.",
                "latex": "2x + 7 = 15",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_00.mp3",
                "duration": 5.2
        },
        {
                "step": 1,
                "narration": "Our goal is to get x by itself on one side of the equation. Right now, x is being multiplied by two and then having seven added to it.",
                "latex": "2x + 7 = 15",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_01.mp3",
                "duration": 8.5
        },
        {
                "step": 2,
                "narration": "First, let's undo the addition of seven. We do this by subtracting seven from both sides of the equation.",
                "latex": "2x + 7 - 7 = 15 - 7",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_02.mp3",
                "duration": 6.55
        },
        {
                "step": 3,
                "narration": "On the left side, seven minus seven is zero, so we're left with just two x.",
                "latex": "2x = 15 - 7",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_03.mp3",
                "duration": 4.88
        },
        {
                "step": 4,
                "narration": "On the right side, fifteen minus seven is eight.",
                "latex": "2x = 8",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_04.mp3",
                "duration": 2.79
        },
        {
                "step": 5,
                "narration": "Now we have two x equals eight. Since x is being multiplied by two, we need to undo that multiplication.",
                "latex": "2x = 8",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_05.mp3",
                "duration": 7.48
        },
        {
                "step": 6,
                "narration": "We divide both sides of the equation by two.",
                "latex": "\\frac{2x}{2} = \\frac{8}{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_06.mp3",
                "duration": 2.69
        },
        {
                "step": 7,
                "narration": "On the left side, two divided by two is one, so we're left with just x.",
                "latex": "x = \\frac{8}{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_07.mp3",
                "duration": 4.88
        },
        {
                "step": 8,
                "narration": "On the right side, eight divided by two is four.",
                "latex": "x = 4",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_08.mp3",
                "duration": 3.34
        },
        {
                "step": 9,
                "narration": "So our solution is x equals four. Let's check our work by plugging it back into the original equation.",
                "latex": "x = 4",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_09.mp3",
                "duration": 6.69
        },
        {
                "step": 10,
                "narration": "Original equation: two times x plus seven equals fifteen.",
                "latex": "2x + 7 = 15",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_10.mp3",
                "duration": 4.37
        },
        {
                "step": 11,
                "narration": "Substitute four for x: two times four plus seven.",
                "latex": "2(4) + 7",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_11.mp3",
                "duration": 3.85
        },
        {
                "step": 12,
                "narration": "Two times four is eight.",
                "latex": "8 + 7",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_12.mp3",
                "duration": 1.72
        },
        {
                "step": 13,
                "narration": "Eight plus seven is fifteen, which matches the right side of our original equation.",
                "latex": "15 = 15 \\quad \\checkmark",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_13.mp3",
                "duration": 4.78
        },
        {
                "step": 14,
                "narration": "Our solution checks out! So x equals four is correct.",
                "latex": "x = 4",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/0ef99b7b/audio/step_14.mp3",
                "duration": 3.53
        }
]
        
        previous = None
        total_steps = len(steps)
        
        for i, step in enumerate(steps):
            latex = step["latex"]
            duration = step["duration"]
            
            # Calculate animation time (slower write at 35% of duration)
            anim_time = max(1.2, duration * ANIMATION_RATIO)
            # Pause syncs with remaining audio time
            pause_time = max(0.3, duration - anim_time)
            
            # Create math object
            math = MathTex(latex, color=WHITE)
            math.scale(1.6)
            
            if previous is None:
                # First step: write on
                self.play(Write(math), run_time=anim_time)
            else:
                # Transform or fade transition
                self.play(
                    FadeOut(previous, shift=UP * 0.3),
                    run_time=0.4
                )
                self.play(Write(math), run_time=anim_time)
            
            # Pause to match audio duration
            self.wait(pause_time)
            
            # Extra hold time after each step (let viewer absorb)
            if i < total_steps - 1:  # not on final step
                self.wait(EXTRA_HOLD_PER_STEP)
            
            previous = math
        
        # Final answer: highlight box and hold
        if previous:
            box = SurroundingRectangle(previous, color=ORBITAL_VIOLET, buff=0.25)
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)  # hold final answer
            self.play(FadeOut(previous), FadeOut(box), run_time=0.5)


if __name__ == "__main__":
    print("Render with: manim -ql {this_file} SyncedMathScene")
