"""
Auto-generated Manim scene with audio-synced timings.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *

ORBITAL_VIOLET = "#8B5CF6"
ORBITAL_CYAN = "#22D3EE"

# Timing configuration
EXTRA_HOLD_PER_STEP = 0.8  # extra pause after each step
ANIMATION_RATIO = 0.35  # animation takes this % of step duration

class SyncedMathScene(Scene):
    """
    Math scene with timings synced to audio.
    Intro duration: 2.0s (handled separately)
    """
    
    def construct(self):
        self.camera.background_color = "#000000"
        
        # Step timings from audio (in seconds)
        steps = [
        {
                "step": 0,
                "narration": "Let's find the derivative of f of x equals x cubed plus two x squared minus five x plus one.",
                "latex": "f(x) = x^{3} + 2x^{2} - 5x + 1",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/2488e575/audio/step_00.mp3",
                "duration": 7.48
        },
        {
                "step": 1,
                "narration": "We'll use the power rule for derivatives. The power rule says that the derivative of x to the n is n times x to the n minus one.",
                "latex": "\\frac{d}{dx}(x^{n}) = nx^{n-1}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/2488e575/audio/step_01.mp3",
                "duration": 9.01
        },
        {
                "step": 2,
                "narration": "Let's apply the power rule to each term separately, starting with x cubed.",
                "latex": "\\frac{d}{dx}(x^{3}) = 3x^{2}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/2488e575/audio/step_02.mp3",
                "duration": 4.69
        },
        {
                "step": 3,
                "narration": "Next, the derivative of two x squared is two times the derivative of x squared.",
                "latex": "\\frac{d}{dx}(2x^{2}) = 2 \\cdot 2x^{1} = 4x",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/2488e575/audio/step_03.mp3",
                "duration": 5.43
        },
        {
                "step": 4,
                "narration": "For negative five x, remember that x is x to the first power.",
                "latex": "\\frac{d}{dx}(-5x) = -5 \\cdot 1x^{0} = -5",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/2488e575/audio/step_04.mp3",
                "duration": 4.69
        },
        {
                "step": 5,
                "narration": "Finally, the derivative of a constant like one is always zero.",
                "latex": "\\frac{d}{dx}(1) = 0",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/2488e575/audio/step_05.mp3",
                "duration": 4.27
        },
        {
                "step": 6,
                "narration": "Now let's put all these derivatives together.",
                "latex": "f'(x) = 3x^{2} + 4x - 5 + 0",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/2488e575/audio/step_06.mp3",
                "duration": 2.83
        },
        {
                "step": 7,
                "narration": "We can simplify by removing the plus zero, giving us our final answer.",
                "latex": "f'(x) = 3x^{2} + 4x - 5",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/2488e575/audio/step_07.mp3",
                "duration": 4.69
        }
]
        
        previous = None
        total_steps = len(steps)
        
        for i, step in enumerate(steps):
            latex = step["latex"]
            duration = step["duration"]
            
            # Calculate animation time (slower write at 35% of duration)
            anim_time = max(1.2, duration * ANIMATION_RATIO)
            # Pause syncs with remaining audio time
            pause_time = max(0.3, duration - anim_time)
            
            # Create math object
            math = MathTex(latex, color=WHITE)
            math.scale(1.6)
            
            if previous is None:
                # First step: write on
                self.play(Write(math), run_time=anim_time)
            else:
                # Transform or fade transition
                self.play(
                    FadeOut(previous, shift=UP * 0.3),
                    run_time=0.4
                )
                self.play(Write(math), run_time=anim_time)
            
            # Pause to match audio duration
            self.wait(pause_time)
            
            # Extra hold time after each step (let viewer absorb)
            if i < total_steps - 1:  # not on final step
                self.wait(EXTRA_HOLD_PER_STEP)
            
            previous = math
        
        # Final answer: highlight box and hold
        if previous:
            box = SurroundingRectangle(previous, color=ORBITAL_VIOLET, buff=0.25)
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)  # hold final answer
            self.play(FadeOut(previous), FadeOut(box), run_time=0.5)


if __name__ == "__main__":
    print("Render with: manim -ql {this_file} SyncedMathScene")
