"""
Auto-generated Manim scene with audio-synced timings.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *

ORBITAL_VIOLET = "#8B5CF6"
ORBITAL_CYAN = "#22D3EE"

# Timing configuration
EXTRA_HOLD_PER_STEP = 0.8  # extra pause after each step
ANIMATION_RATIO = 0.35  # animation takes this % of step duration

class SyncedMathScene(Scene):
    """
    Math scene with timings synced to audio.
    Intro duration: 2.0s (handled separately)
    """
    
    def construct(self):
        self.camera.background_color = "#000000"
        
        # Step timings from audio (in seconds)
        steps = [
        {
                "step": 0,
                "narration": "Let's find the derivative of f of x equals x cubed plus two x squared minus five x plus one.",
                "latex": "f(x) = x^{3} + 2x^{2} - 5x + 1",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/e087a019/audio/step_00.mp3",
                "duration": 6.92
        },
        {
                "step": 1,
                "narration": "We'll use the power rule for derivatives. The power rule says that the derivative of x to the n is n times x to the n minus one.",
                "latex": "\\frac{d}{dx} x^{n} = n x^{n-1}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/e087a019/audio/step_01.mp3",
                "duration": 9.1
        },
        {
                "step": 2,
                "narration": "The derivative of a sum is the sum of the derivatives. So we can differentiate each term separately.",
                "latex": "f'(x) = \\frac{d}{dx}(x^{3}) + \\frac{d}{dx}(2x^{2}) + \\frac{d}{dx}(-5x) + \\frac{d}{dx}(1)",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/e087a019/audio/step_02.mp3",
                "duration": 5.9
        },
        {
                "step": 3,
                "narration": "Now apply the power rule. For x cubed, we get three x squared. For two x squared, we get two times two x, which is four x. For negative five x, we get negative five. And the derivative of a constant is zero.",
                "latex": "f'(x) = 3x^{2} + 4x - 5 + 0",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/e087a019/audio/step_03.mp3",
                "duration": 17.0
        },
        {
                "step": 4,
                "narration": "Simplifying, we have three x squared plus four x minus five.",
                "latex": "f'(x) = 3x^{2} + 4x - 5",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/e087a019/audio/step_04.mp3",
                "duration": 4.78
        }
]
        
        previous = None
        total_steps = len(steps)
        
        for i, step in enumerate(steps):
            latex = step["latex"]
            duration = step["duration"]
            
            # Calculate animation time (slower write at 35% of duration)
            anim_time = max(1.2, duration * ANIMATION_RATIO)
            # Pause syncs with remaining audio time
            pause_time = max(0.3, duration - anim_time)
            
            # Create math object
            math = MathTex(latex, color=WHITE)
            math.scale(1.6)
            
            if previous is None:
                # First step: write on
                self.play(Write(math), run_time=anim_time)
            else:
                # Transform or fade transition
                self.play(
                    FadeOut(previous, shift=UP * 0.3),
                    run_time=0.4
                )
                self.play(Write(math), run_time=anim_time)
            
            # Pause to match audio duration
            self.wait(pause_time)
            
            # Extra hold time after each step (let viewer absorb)
            if i < total_steps - 1:  # not on final step
                self.wait(EXTRA_HOLD_PER_STEP)
            
            previous = math
        
        # Final answer: highlight box and hold
        if previous:
            box = SurroundingRectangle(previous, color=ORBITAL_VIOLET, buff=0.25)
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)  # hold final answer
            self.play(FadeOut(previous), FadeOut(box), run_time=0.5)


if __name__ == "__main__":
    print("Render with: manim -ql {this_file} SyncedMathScene")
