"""
Auto-generated Manim scene with audio-synced timings.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *

ORBITAL_VIOLET = "#8B5CF6"
ORBITAL_CYAN = "#22D3EE"

# Timing configuration
EXTRA_HOLD_PER_STEP = 0.8  # extra pause after each step
ANIMATION_RATIO = 0.35  # animation takes this % of step duration

class SyncedMathScene(Scene):
    """
    Math scene with timings synced to audio.
    Intro duration: 2.0s (handled separately)
    """
    
    def construct(self):
        self.camera.background_color = "#000000"
        
        # Step timings from audio (in seconds)
        steps = [
        {
                "step": 0,
                "narration": "Let's find the derivative of the function f of x equals x cubed plus two x squared minus five x plus one.",
                "latex": "f(x) = x^3 + 2x^2 - 5x + 1",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_00.mp3",
                "duration": 8.17
        },
        {
                "step": 1,
                "narration": "We'll use the power rule for derivatives. The power rule says: to take the derivative of x to the n, we bring down the exponent as a coefficient, then reduce the exponent by one.",
                "latex": "\\frac{d}{dx}(x^n) = n \\cdot x^{n-1}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_01.mp3",
                "duration": 11.52
        },
        {
                "step": 2,
                "narration": "We'll apply the power rule to each term separately. Let's start with the first term: x cubed.",
                "latex": "\\frac{d}{dx}(x^3)",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_02.mp3",
                "duration": 6.32
        },
        {
                "step": 3,
                "narration": "For x cubed, we bring down the three and multiply it by the coefficient, which is one.",
                "latex": "x^3 \\rightarrow 1 \\cdot 3 \\cdot x^{3-1}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_03.mp3",
                "duration": 5.53
        },
        {
                "step": 4,
                "narration": "One times three is three, and three minus one is two. So the derivative of x cubed is three x squared.",
                "latex": "1 \\cdot 3 \\cdot x^{3-1} = 3x^2",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_04.mp3",
                "duration": 7.48
        },
        {
                "step": 5,
                "narration": "Now let's move to the second term: two x squared.",
                "latex": "\\frac{d}{dx}(2x^2)",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_05.mp3",
                "duration": 3.53
        },
        {
                "step": 6,
                "narration": "For two x squared, we bring down the two from the exponent and multiply it by the coefficient two.",
                "latex": "2x^2 \\rightarrow 2 \\cdot 2 \\cdot x^{2-1}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_06.mp3",
                "duration": 5.8
        },
        {
                "step": 7,
                "narration": "Two times two is four, and two minus one is one. So we get four x to the first power, which is just four x.",
                "latex": "2 \\cdot 2 \\cdot x^{2-1} = 4x^1 = 4x",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_07.mp3",
                "duration": 8.59
        },
        {
                "step": 8,
                "narration": "Now for the third term: negative five x. Remember that x is the same as x to the first power.",
                "latex": "-5x = -5x^1",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_08.mp3",
                "duration": 6.97
        },
        {
                "step": 9,
                "narration": "For negative five x to the first power, we bring down the one and multiply it by negative five.",
                "latex": "-5x^1 \\rightarrow -5 \\cdot 1 \\cdot x^{1-1}",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_09.mp3",
                "duration": 5.9
        },
        {
                "step": 10,
                "narration": "Negative five times one is negative five, and one minus one is zero. So we get negative five times x to the zero power.",
                "latex": "-5 \\cdot 1 \\cdot x^{1-1} = -5x^0",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_10.mp3",
                "duration": 8.41
        },
        {
                "step": 11,
                "narration": "Since x to the zero power equals one, negative five times one is just negative five.",
                "latex": "-5x^0 = -5 \\cdot 1 = -5",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_11.mp3",
                "duration": 6.13
        },
        {
                "step": 12,
                "narration": "Finally, for the constant term: plus one. The derivative of any constant is always zero.",
                "latex": "\\frac{d}{dx}(1) = 0",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_12.mp3",
                "duration": 6.22
        },
        {
                "step": 13,
                "narration": "Now let's put all the pieces together. We have three x squared from the first term, plus four x from the second term, minus five from the third term, plus zero from the constant.",
                "latex": "3x^2 + 4x - 5 + 0",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_13.mp3",
                "duration": 11.42
        },
        {
                "step": 14,
                "narration": "Since adding zero doesn't change anything, our final derivative is three x squared plus four x minus five.",
                "latex": "f'(x) = 3x^2 + 4x - 5",
                "audio_path": "/Users/claudioatlas/Desktop/Orbital/orbital_factory/jobs/df7269a6/audio/step_14.mp3",
                "duration": 7.2
        }
]
        
        previous = None
        total_steps = len(steps)
        
        for i, step in enumerate(steps):
            latex = step["latex"]
            duration = step["duration"]
            
            # Calculate animation time (slower write at 35% of duration)
            anim_time = max(1.2, duration * ANIMATION_RATIO)
            # Pause syncs with remaining audio time
            pause_time = max(0.3, duration - anim_time)
            
            # Create math object
            math = MathTex(latex, color=WHITE)
            math.scale(1.6)
            
            if previous is None:
                # First step: write on
                self.play(Write(math), run_time=anim_time)
            else:
                # Transform or fade transition
                self.play(
                    FadeOut(previous, shift=UP * 0.3),
                    run_time=0.4
                )
                self.play(Write(math), run_time=anim_time)
            
            # Pause to match audio duration
            self.wait(pause_time)
            
            # Extra hold time after each step (let viewer absorb)
            if i < total_steps - 1:  # not on final step
                self.wait(EXTRA_HOLD_PER_STEP)
            
            previous = math
        
        # Final answer: highlight box and hold
        if previous:
            box = SurroundingRectangle(previous, color=ORBITAL_VIOLET, buff=0.25)
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)  # hold final answer
            self.play(FadeOut(previous), FadeOut(box), run_time=0.5)


if __name__ == "__main__":
    print("Render with: manim -ql {this_file} SyncedMathScene")
