"use client";

import { useState, useEffect, useRef } from "react";

interface VideoCarouselProps {
  isDark: boolean;
}

const videos = [
  {
    src: "/videos/sizzle-reel.mp4",
    title: "What is Orbital?",
    subtitle: "See the future of math education",
  },
  {
    src: "/videos/dedekind-proof.mp4",
    title: "The Reals are Uncountable",
    subtitle: "A full proof walkthrough — generated by AI",
  },
];

export function VideoCarousel({ isDark }: VideoCarouselProps) {
  const [activeIndex, setActiveIndex] = useState(0);
  const [playStates, setPlayStates] = useState<boolean[]>(videos.map((_, i) => i === 0));
  const [mutedStates, setMutedStates] = useState<boolean[]>(videos.map(() => true));
  const videoRefs = useRef<(HTMLVideoElement | null)[]>([]);

  useEffect(() => {
    videoRefs.current.forEach((video, i) => {
      if (!video) return;
      if (i === activeIndex) {
        video.play().catch(() => {});
        setPlayStates(prev => { const n = [...prev]; n[i] = true; return n; });
      } else {
        video.pause();
        setPlayStates(prev => { const n = [...prev]; n[i] = false; return n; });
      }
    });
  }, [activeIndex]);

  const toggleMute = (index: number) => {
    setMutedStates(prev => {
      const n = [...prev];
      n[index] = !n[index];
      const video = videoRefs.current[index];
      if (video) video.muted = n[index];
      return n;
    });
  };

  const togglePlay = (index: number) => {
    const video = videoRefs.current[index];
    if (!video) return;
    if (video.paused) {
      video.play();
      setPlayStates(prev => { const n = [...prev]; n[index] = true; return n; });
    } else {
      video.pause();
      setPlayStates(prev => { const n = [...prev]; n[index] = false; return n; });
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto">
      <div className="relative">
        {videos.map((video, index) => (
          <div
            key={video.src}
            className={index === activeIndex ? "block" : "hidden"}
          >
            <div
              className={`relative rounded-2xl overflow-hidden cursor-pointer ${
                isDark
                  ? "border border-violet-500/30 shadow-[0_0_40px_rgba(139,92,246,0.2)]"
                  : "ring-1 ring-violet-300 shadow-[0_0_30px_rgba(139,92,246,0.12)]"
              }`}
            >
              <video
                ref={(el) => { videoRefs.current[index] = el; }}
                src={video.src}
                muted={mutedStates[index]}
                autoPlay={index === 0}
                loop
                playsInline
                className="w-full aspect-video object-cover bg-black"
                onClick={() => togglePlay(index)}
              />

              {!playStates[index] && (
                <button
                  onClick={() => togglePlay(index)}
                  className="absolute inset-0 flex items-center justify-center bg-black/30"
                >
                  <div className="w-20 h-20 rounded-full bg-white/20 backdrop-blur-sm flex items-center justify-center border border-white/30">
                    <svg className="w-8 h-8 text-white ml-1" fill="currentColor" viewBox="0 0 24 24">
                      <path d="M8 5v14l11-7z" />
                    </svg>
                  </div>
                </button>
              )}

              <button
                onClick={(e) => { e.stopPropagation(); toggleMute(index); }}
                className={`absolute bottom-4 right-4 p-2.5 rounded-full transition-all backdrop-blur-sm ${
                  isDark
                    ? "bg-black/50 hover:bg-black/70 border border-white/10"
                    : "bg-white/80 hover:bg-white border border-gray-200/50"
                }`}
              >
                {mutedStates[index] ? (
                  <svg className={`w-5 h-5 ${isDark ? "text-white" : "text-gray-700"}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
                    <path strokeLinecap="round" strokeLinejoin="round" d="M17 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2" />
                  </svg>
                ) : (
                  <svg className={`w-5 h-5 ${isDark ? "text-white" : "text-gray-700"}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M15.536 8.464a5 5 0 010 7.072M18.364 5.636a9 9 0 010 12.728M5.586 15H4a1 1 0 01-1-1v-4a1 1 0 011-1h1.586l4.707-4.707C10.923 3.663 12 4.109 12 5v14c0 .891-1.077 1.337-1.707.707L5.586 15z" />
                  </svg>
                )}
              </button>
            </div>

            <div className="mt-4 text-center">
              <h3 className={`text-lg font-semibold ${isDark ? "text-white" : "text-gray-900"}`}>
                {video.title}
              </h3>
              <p className={`text-sm mt-1 ${isDark ? "text-gray-500" : "text-gray-500"}`}>
                {video.subtitle}
              </p>
            </div>
          </div>
        ))}
      </div>

      <div className="flex justify-center gap-2.5 mt-6">
        {videos.map((_, index) => (
          <button
            key={index}
            onClick={() => setActiveIndex(index)}
            className={`transition-all duration-300 rounded-full ${
              index === activeIndex
                ? "w-8 h-2.5 bg-violet-500"
                : `w-2.5 h-2.5 ${isDark ? "bg-white/20 hover:bg-white/40" : "bg-gray-300 hover:bg-gray-400"}`
            }`}
          />
        ))}
      </div>
    </div>
  );
}
