"""
Auto-generated Manim scene with audio-synced timings.
Generated by Orbital VideoFactory Pipeline.
"""

from manim import *

ORBITAL_VIOLET = "#8B5CF6"
ORBITAL_CYAN = "#22D3EE"

# Timing configuration
EXTRA_HOLD_PER_STEP = 0.8  # extra pause after each step
ANIMATION_RATIO = 0.35  # animation takes this % of step duration

class SyncedMathScene(Scene):
    """
    Math scene with timings synced to audio.
    Intro duration: 2.0s (handled separately)
    """
    
    def construct(self):
        self.camera.background_color = "#000000"
        
        # Step timings from audio (in seconds)
        steps = [
        {
                "step": 0,
                "narration": "Let's solve the equation, two x plus five equals eleven.",
                "latex": "2x + 5 = 11",
                "audio_path": "jobs/linear_equation_2x5_natural/audio/step_00.mp3",
                "duration": 4.18
        },
        {
                "step": 1,
                "narration": "To isolate x, we subtract five from both sides.",
                "latex": "2x + 5 - 5 = 11 - 5",
                "audio_path": "jobs/linear_equation_2x5_natural/audio/step_01.mp3",
                "duration": 3.9
        },
        {
                "step": 2,
                "narration": "This simplifies to, two x equals six.",
                "latex": "2x = 6",
                "audio_path": "jobs/linear_equation_2x5_natural/audio/step_02.mp3",
                "duration": 3.48
        },
        {
                "step": 3,
                "narration": "Now we divide both sides by two.",
                "latex": "\\frac{2x}{2} = \\frac{6}{2}",
                "audio_path": "jobs/linear_equation_2x5_natural/audio/step_03.mp3",
                "duration": 2.46
        },
        {
                "step": 4,
                "narration": "And we get our answer, x equals three.",
                "latex": "x = 3",
                "audio_path": "jobs/linear_equation_2x5_natural/audio/step_04.mp3",
                "duration": 2.83
        }
]
        
        previous = None
        total_steps = len(steps)
        
        for i, step in enumerate(steps):
            latex = step["latex"]
            duration = step["duration"]
            
            # Calculate animation time (slower write at 35% of duration)
            anim_time = max(1.2, duration * ANIMATION_RATIO)
            # Pause syncs with remaining audio time
            pause_time = max(0.3, duration - anim_time)
            
            # Create math object
            math = MathTex(latex, color=WHITE)
            math.scale(1.6)
            
            if previous is None:
                # First step: write on
                self.play(Write(math), run_time=anim_time)
            else:
                # Transform or fade transition
                self.play(
                    FadeOut(previous, shift=UP * 0.3),
                    run_time=0.4
                )
                self.play(Write(math), run_time=anim_time)
            
            # Pause to match audio duration
            self.wait(pause_time)
            
            # Extra hold time after each step (let viewer absorb)
            if i < total_steps - 1:  # not on final step
                self.wait(EXTRA_HOLD_PER_STEP)
            
            previous = math
        
        # Final answer: highlight box and hold
        if previous:
            box = SurroundingRectangle(previous, color=ORBITAL_VIOLET, buff=0.25)
            self.play(Create(box), run_time=0.6)
            self.wait(2.0)  # hold final answer
            self.play(FadeOut(previous), FadeOut(box), run_time=0.5)


if __name__ == "__main__":
    print("Render with: manim -ql {this_file} SyncedMathScene")
